// Separate disposable PostgreSQL database, published schema only. Auth/Storage
// facsimiles contain fictional metadata, no document bytes or copied CRM data.
import assert from 'node:assert/strict';
import {readFileSync,readdirSync,writeFileSync} from 'node:fs';
import {randomUUID} from 'node:crypto';
import {dirname,resolve} from 'node:path';
import {fileURLToPath} from 'node:url';
import pg from 'pg';
const root=resolve(dirname(fileURLToPath(import.meta.url)),'..'),status=JSON.parse(readFileSync('/private/tmp/oar-targeted-docs-local-status.json'));
assert(['localhost','127.0.0.1'].includes(new URL(status.DB_URL).hostname));assert.equal(process.env.IZORD_TEST_ACK,'IZORD_DISPOSABLE_LOCAL_ONLY');
const database='house_worker_removal_'+randomUUID().replaceAll('-',''),base=new pg.Client({connectionString:status.DB_URL});await base.connect();await base.query('create database '+database);await base.end();
const target=new URL(status.DB_URL);target.pathname='/'+database;let sql=new pg.Client({connectionString:target.toString()});await sql.connect();
const results=[],owner=randomUUID(),limited=randomUUID(),lease=randomUUID(),migrationFiles=readdirSync(root+'/supabase/migrations'),cleanupFiles=migrationFiles.filter(name=>name.endsWith('_permanently_remove_house_worker_documents.sql'));assert.equal(cleanupFiles.length,1);const cleanupFile=cleanupFiles[0];
const test=async(name,run)=>{await run();results.push({name,passed:true});};
const worker=(id,path='',extra={})=>({id,contactId:'fictional-contact',contactName:'Intervenant entièrement fictif',status:'Actif',hourlyRate:12.34,notes:'Historique fictif conservé',createdAt:'2025-01-01',createdBy:owner,updatedAt:'2025-02-01',updatedBy:owner,documentStoragePath:path,documentUrl:path?'https://fictional.invalid/'+path:'',documentFileName:path?'fictional.pdf':'',documentUploadedAt:path?'2025-01-03':'',...extra});
const sourcePath='oneaddress-riviera/house-workers/fictional-source/contract.pdf',sharedPath='oneaddress-riviera/house-workers/fictional-shared/contract.pdf';
const workers=[worker('fictional-source-worker',sourcePath),worker('fictional-empty-worker'),worker('fictional-shared-worker',sharedPath),worker('fictional-unrelated-worker','',{})];
const rpc=(name,args)=>sql.query(`select public.${name}(${args.map((_,i)=>'$'+(i+1)).join(',')}) result`,args).then(r=>r.rows[0].result);
const payload=()=>sql.query("select payload from public.crm_workspace_state where workspace_id='oneaddress-riviera'").then(r=>r.rows[0].payload);
const begin=async(path,ids,overrides={})=>{const object=(await sql.query("select *,updated_at::text exact_updated_at,md5(metadata::text) metadata_md5 from storage.objects where bucket_id='crm-documents' and name=$1",[path])).rows[0],p=await payload(),rows=await sql.query("select r->>'id' id,md5(r::text) revision from public.crm_workspace_state w cross join lateral jsonb_array_elements(w.payload->'houseTrackingWorkers') r where w.workspace_id='oneaddress-riviera' and r->>'id'=any($1::text[]) order by r->>'id'",[ids]);assert.equal(rows.rows.length,ids.length);const args=[randomUUID(),owner,'crm-documents',path,object.id,object.version,object.exact_updated_at,object.metadata_md5,JSON.stringify(rows.rows)];for(const [key,value]of Object.entries(overrides))args[Number(key)]=value;return {args,object,documents:p.houseTrackingWorkers.filter(w=>ids.includes(w.id)),job:await rpc('crm_house_worker_document_removal_begin',args)};};
try{
 await sql.query(readFileSync(root+'/tests/izord/sql-fixture.sql','utf8'));
 await sql.query("alter table auth.users add column deleted_at timestamptz,add column banned_until timestamptz;create table auth.sessions(id uuid primary key,user_id uuid references auth.users(id));create function auth.jwt() returns jsonb language sql stable as $$select coalesce(nullif(current_setting('request.jwt.claims',true),'')::jsonb,'{}'::jsonb)$$;alter table storage.objects add column updated_at timestamptz default clock_timestamp(),add column owner uuid,add column owner_id text,add column created_at timestamptz default clock_timestamp();create function public.fixture_touch_workspace() returns trigger language plpgsql as $$begin new.updated_at=clock_timestamp();return new;end$$;create trigger fixture_touch_workspace before update on public.crm_workspace_state for each row execute function public.fixture_touch_workspace();");
 for(const file of migrationFiles.sort().filter(file=>file.endsWith('.sql')&&file!==cleanupFile))await sql.query(readFileSync(root+'/supabase/migrations/'+file,'utf8'));
 assert.equal((await sql.query("select count(*) n from pg_proc where proname like 'crm_contact_document_drive_%'")).rows[0].n,'0','No pending Drive primitives');
 await sql.query('insert into auth.users(id,email,email_confirmed_at) values($1,$2,now()),($3,$4,now())',[owner,'owner@example.invalid',limited,'limited@example.invalid']);
 await sql.query('insert into public.crm_access_profiles(user_id,general_admin) values($1,true),($2,false)',[owner,limited]);
 await sql.query("insert into public.app_memberships(user_id,workspace_id,role) values($1,'oar','member'),($2,'oar','member')",[owner,limited]);
 const modules=['dashboard','contacts','leads','tasks','quotes','bookings','vendorQuotes','vendorInvoices','houseTracking','documents','planning','properties','vehicles','boats','publisher','monthlyCharges'];
 for(const moduleKey of modules)await sql.query('insert into public.crm_module_grants(user_id,module,level,sensitive) values($1,$2,$3,$4)',[owner,moduleKey,'contribute',JSON.stringify(moduleKey==='publisher'?{export:true,generate:true,mark_published:true}:moduleKey==='monthlyCharges'?{export:true}:{delete:true,export:true,bank_read:true,bank_write:true,payment:true})]);
 await sql.query("insert into public.crm_module_grants(user_id,module,level,sensitive) values($1,'houseTracking','contribute','{}')",[limited]);
 await sql.query("update public.crm_workspace_state set payload=$1 where workspace_id='oneaddress-riviera'",[JSON.stringify({contacts:[{id:'fictional-contact',name:'Personne fictive',kind:'Client'}],houseTrackingWorkers:workers,houseTimeEntries:[{id:'fictional-hours',workerId:workers[0].id,startTime:'08:07',endTime:'12:42',hourlyRate:12.34,date:'2025-01-03'}],housePayments:[{id:'fictional-payment',workerId:workers[0].id,amount:20}],vendorInvoices:[{id:'fictional-invoice',invoiceDocumentStoragePath:sharedPath}],documents:[],unrelated:{sentinel:'preserved'}})]);
 await sql.query("insert into storage.objects(bucket_id,name,metadata,owner) values('crm-documents',$1,'{\"size\":57,\"mimetype\":\"application/pdf\",\"eTag\":\"fictional-source-v1\"}',$3),('crm-documents',$2,'{\"size\":57,\"mimetype\":\"application/pdf\",\"eTag\":\"fictional-shared-v1\"}',$3)",[sourcePath,sharedPath,owner]);
 const extraPaths=['orphan','version','trash'].map(label=>'oneaddress-riviera/house-workers/fictional-'+label+'/old.pdf');
 for(const path of extraPaths)await sql.query("insert into storage.objects(bucket_id,name,metadata,owner,owner_id) values('crm-documents',$1,'{\"size\":57,\"mimetype\":\"application/pdf\"}',$2::uuid,$2::uuid::text)",[path,owner]);
 await sql.query("insert into public.crm_document_scopes(provider,resource_id,module,collection,record_id,title,bank,personal_contact) values('storage',$1,'houseTracking','houseTrackingWorkers',$2,'Fictif',false,false)",[sourcePath,workers[0].id]);
 const original=await payload();
 await sql.query(readFileSync(root+'/supabase/migrations/'+cleanupFile,'utf8'));
 await test('migration does not remove a byte/reference or modify nondocumentary historical data',async()=>{assert.deepEqual(await payload(),original);assert.equal((await sql.query("select count(*) n from storage.objects where name=any($1::text[])",[[sourcePath,sharedPath]])).rows[0].n,'2');assert.equal((await sql.query('select count(*) n from app_private.house_worker_document_removal_jobs')).rows[0].n,'0');});
 await test('all job RPCs service-only; new document/import/classification/full-save reintroduction permanently closed',async()=>{const funcs=['begin(uuid,uuid,text,text,uuid,text,timestamp with time zone,text,jsonb,timestamp with time zone,jsonb)','check(uuid,uuid)','complete(uuid,uuid)','release(uuid,uuid)'];for(const signature of funcs){const row=(await sql.query("select has_function_privilege('authenticated',$1,'execute') authenticated,has_function_privilege('anon',$1,'execute') anon,has_function_privilege('service_role',$1,'execute') service",['public.crm_house_worker_document_removal_'+signature])).rows[0];assert.deepEqual(row,{authenticated:false,anon:false,service:true});}await sql.query("select set_config('request.jwt.claim.sub',$1,false)",[owner]);await assert.rejects(rpc('crm_new_document',['houseTrackingWorkers',workers[0].id,'Upload interdit',false]),/worker_documents_permanently_disabled/);await assert.rejects(rpc('crm_classify_document',['storage','classified/fictional','houseTrackingWorkers',workers[0].id,'Upload interdit',false]),/worker_documents_permanently_disabled/);const p=await payload();p.houseTrackingWorkers[0].documentStoragePath+='-changed';await assert.rejects(sql.query("update public.crm_workspace_state set payload=$1 where workspace_id='oneaddress-riviera'",[p]),/worker_documents_permanently_disabled/);assert(!('documentStoragePath' in (await sql.query("select fields from app_private.module_collections where collection='houseTrackingWorkers'")).rows[0].fields));await assert.rejects(sql.query("insert into storage.objects(bucket_id,name) values('crm-documents','oneaddress-riviera/house-workers/new/upload.pdf')"),/worker_documents_permanently_disabled/);await assert.rejects(sql.query("update storage.objects set metadata=metadata||'{\"size\":58}' where name=$1",[sourcePath]),/worker_documents_permanently_disabled/);await sql.query("select set_config('request.jwt.claim.sub','',false)");});
 await test('exact ID/version/hash and positive worker scope required; names/orphan paths confer no authorization',async()=>{await assert.rejects(begin(sourcePath,[workers[0].id],{5:'wrong-version'}),/object_changed/);await assert.rejects(begin(sourcePath,[workers[1].id]),/positive_scope_required/);await assert.rejects(begin(sourcePath,[workers[0].id],{1:limited}),/forbidden/);assert.equal((await sql.query('select count(*) n from app_private.house_worker_document_removal_jobs')).rows[0].n,'0');});
 const deletion=await begin(sourcePath,[workers[0].id,workers[1].id]);
 await test('prepare is durable, failure leaves refs, check leases target and blocks races',async()=>{assert.equal(deletion.job.action,'delete');const checked=await rpc('crm_house_worker_document_removal_check',[deletion.job.operation_id,lease]);assert.equal(checked.object_id,deletion.object.id);assert.equal(checked.object_version,deletion.object.version);assert.equal(checked.object_missing,false);await assert.rejects(rpc('crm_house_worker_document_removal_check',[deletion.job.operation_id,randomUUID()]),/busy/);await assert.rejects(rpc('crm_house_worker_document_removal_complete',[deletion.job.operation_id,lease]),/storage_not_confirmed/);assert.deepEqual(await payload(),original);const p=await payload();p.vendorInvoices.push({id:'illegal-new-ref',invoiceDocumentStoragePath:sourcePath});await assert.rejects(sql.query("update public.crm_workspace_state set payload=$1 where workspace_id='oneaddress-riviera'",[p]),/reference_locked/);assert.deepEqual(await rpc('crm_house_worker_document_removal_release',[deletion.job.operation_id,lease]),{released:true});const renewed=await rpc('crm_house_worker_document_removal_begin',deletion.args);assert.equal(renewed.operation_id,deletion.job.operation_id);});
 await test('nondocument edits, notes, hours and payments survive while old docrefs stay until confirmed',async()=>{await sql.query("select set_config('request.jwt.claim.sub',$1,false)",[owner]);const revision=(await sql.query("select updated_at::text revision from public.crm_workspace_state where workspace_id='oneaddress-riviera'")).rows[0].revision;const result=await rpc('crm_update_house_worker',[workers[0].id,JSON.stringify({hourlyRate:25.50,notes:'Nouvelle note fictive'}),revision]);assert.equal(result.worker.hourlyRate,25.5);assert.equal(result.worker.documentStoragePath,sourcePath);const p=await payload();assert.deepEqual(p.houseTimeEntries,original.houseTimeEntries);assert.deepEqual(p.housePayments,original.housePayments);assert.equal(p.houseTrackingWorkers[0].notes,'Nouvelle note fictive');await sql.query("select set_config('request.jwt.claim.sub','',false)");});
 const keeping=await begin(sharedPath,[workers[2].id]);
 await test('shared physical object is retained, worker refs alone detached, complete idempotent',async()=>{assert.equal(keeping.job.action,'keep');const token=randomUUID();await rpc('crm_house_worker_document_removal_check',[keeping.job.operation_id,token]);const before=await payload();const result=await rpc('crm_house_worker_document_removal_complete',[keeping.job.operation_id,token]);assert.equal(result.action,'keep');assert.equal(result.refs_removed,1);assert.equal((await sql.query('select count(*) n from storage.objects where id=$1',[keeping.object.id])).rows[0].n,'1');const after=await payload();assert.deepEqual(after.vendorInvoices,before.vendorInvoices);assert.deepEqual(after.houseTrackingWorkers[2],Object.fromEntries(Object.entries(before.houseTrackingWorkers[2]).filter(([key])=>!key.startsWith('document'))));assert.deepEqual(await rpc('crm_house_worker_document_removal_complete',[keeping.job.operation_id,token]),result);const stale=await payload();stale.houseTrackingWorkers[2]=before.houseTrackingWorkers[2];await assert.rejects(sql.query("update public.crm_workspace_state set payload=$1 where workspace_id='oneaddress-riviera'",[stale]),/permanently_disabled/);});
 await test('pending deletion survives reconnect and refuses completion without API absence; expiration renewable',async()=>{const reconnect=new pg.Client({connectionString:target.toString()});await reconnect.connect();assert.equal((await reconnect.query('select status from app_private.house_worker_document_removal_jobs where operation_id=$1',[deletion.job.operation_id])).rows[0].status,'pending');await reconnect.end();const token=randomUUID();await rpc('crm_house_worker_document_removal_check',[deletion.job.operation_id,token]);await sql.query("update app_private.house_worker_document_removal_jobs set expires_at=clock_timestamp()-interval '1 second' where operation_id=$1",[deletion.job.operation_id]);await assert.rejects(rpc('crm_house_worker_document_removal_check',[deletion.job.operation_id,token]),/expired/);await rpc('crm_house_worker_document_removal_begin',deletion.args);assert.equal((await rpc('crm_house_worker_document_removal_check',[deletion.job.operation_id,token])).object_missing,false);await assert.rejects(rpc('crm_house_worker_document_removal_complete',[deletion.job.operation_id,token]),/storage_not_confirmed/);await rpc('crm_house_worker_document_removal_release',[deletion.job.operation_id,token]);});
 const proofJob=async(path,changes={})=>{const o=(await sql.query("select *,created_at::text exact_created_at,updated_at::text exact_updated_at,md5(metadata::text) metadata_md5 from storage.objects where bucket_id='crm-documents' and name=$1",[path])).rows[0],proof={kind:'storage-upload-event-metadata',projectRef:'jcmnwvlmysecrahupfkk',bucketId:'crm-documents',path,objectId:o.id,ownerId:o.owner_id,objectCreatedAt:o.exact_created_at,method:'POST',status:200,origin:'https://oneaddress-riviera-crm.vercel.app/',postTimestamp:o.exact_created_at,event:'ObjectCreated:Post',eventTimestamp:o.exact_created_at,eventPath:path,evidenceStatus:'attested-former-worker-upload-path',...changes},args=[randomUUID(),owner,'crm-documents',path,o.id,o.version,o.exact_updated_at,o.metadata_md5,'[]',new Date(Date.now()+15*60*1000).toISOString(),JSON.stringify(proof)];return {args,object:o,job:await rpc('crm_house_worker_document_removal_begin',args)};};
 await test('old uploads require service-attested exact POST/event/owner/time provenance; no name-only or empty-worker authorization',async()=>{await assert.rejects(begin(extraPaths[0],[]),/positive_scope_required/);for(const changes of [{ownerId:randomUUID()},{path:'wrong-path'},{status:201},{event:'ObjectCreated:Copy'},{postTimestamp:'2020-01-01'},{origin:'https://other.invalid/'}])await assert.rejects(proofJob(extraPaths[0],changes),/positive_scope_required/);});
 await test('existing superseded-version and private trash snapshots retain the same physical object',async()=>{await sql.query("select set_config('app.contact_document_mutation','confirmed',false)");await sql.query("insert into public.crm_document_scopes(provider,resource_id,module,collection,record_id,title,bank,personal_contact,superseded_by) values('storage','fictional-older-version','vendorInvoices','vendorInvoices','fictional-invoice','Fictif',false,false,$1)",[extraPaths[1]]);await sql.query("insert into app_private.document_drive_trash(operation_id,record_id,resource_id,parent_record_id,parent_resource_id,is_folder,actor_id,snapshot,folder_title,start_workspace_revision,status,completed_at,drive_confirmation) values($1,'fictional-trash-row','fictional-drive-resource','fictional-parent','fictional-parent-drive',false,$2,$3,'Fictif',clock_timestamp(),'completed',clock_timestamp(),'{\"id\":\"fictional-drive-resource\",\"trashed\":true,\"explicitlyTrashed\":true}')",[randomUUID(),owner,JSON.stringify({historicalPath:extraPaths[2]})]);assert.equal((await proofJob(extraPaths[1])).job.action,'keep');assert.equal((await proofJob(extraPaths[2])).job.action,'keep');await sql.query("select set_config('app.contact_document_mutation','',false)");});
 await test('fresh actor permissions are rechecked after admission; failed worker and Storage removals leave references intact',async()=>{const token=randomUUID();await rpc('crm_house_worker_document_removal_release',[deletion.job.operation_id,lease]);await rpc('crm_house_worker_document_removal_check',[deletion.job.operation_id,token]);await sql.query('update public.crm_access_profiles set active=false where user_id=$1',[owner]);await assert.rejects(rpc('crm_house_worker_document_removal_check',[deletion.job.operation_id,token]),/forbidden/);await assert.rejects(rpc('crm_house_worker_document_removal_complete',[deletion.job.operation_id,token]),/forbidden/);await sql.query('update public.crm_access_profiles set active=true where user_id=$1',[owner]);const before=await payload();await sql.query("select set_config('app.worker_document_removal','confirmed',false)");const removed=structuredClone(before);removed.houseTrackingWorkers[0]=Object.fromEntries(Object.entries(removed.houseTrackingWorkers[0]).filter(([key])=>!key.startsWith('document')));await assert.rejects(sql.query("update public.crm_workspace_state set payload=$1 where workspace_id='oneaddress-riviera'",[removed]),/permanently_disabled/);await sql.query("select set_config('app.worker_document_removal','',false)");assert.deepEqual(await payload(),before);await rpc('crm_house_worker_document_removal_release',[deletion.job.operation_id,token]);});
 const orphan=await proofJob(extraPaths[0]);
 await test('pending job blocks worker disappearance, scope version pointers and trash snapshot reintroduction',async()=>{const p=await payload();p.houseTrackingWorkers=p.houseTrackingWorkers.filter(row=>row.id!==workers[0].id);await assert.rejects(sql.query("update public.crm_workspace_state set payload=$1 where workspace_id='oneaddress-riviera'",[p]),/worker_locked/);await assert.rejects(sql.query("update public.crm_document_scopes set superseded_by=$1 where resource_id='fictional-older-version'",[sourcePath]),/reference_locked/);await assert.rejects(sql.query("update app_private.document_drive_trash set snapshot=$1 where resource_id='fictional-drive-resource'",[JSON.stringify({path:sourcePath})]),/reference_locked/);});
 // Simulated Storage API absence in this schema-only facsimile: no DELETE SQL,
 // no document bytes, and no real Storage service. The physical-operation proof
 // belongs to the separately tested server Storage.remove boundary.
 await sql.query("alter table storage.objects rename to fixture_storage_objects;create table public.fixture_storage_api_removed(id uuid primary key);create view storage.objects as select o.* from storage.fixture_storage_objects o where not exists(select 1 from public.fixture_storage_api_removed r where r.id=o.id);");
 await sql.end();sql=new pg.Client({connectionString:target.toString()});await sql.connect();
 await test('confirmed API absence detaches document fields only; lost response resumes and old full saves cannot resurrect',async()=>{const before=await payload(),token=randomUUID();await rpc('crm_house_worker_document_removal_check',[deletion.job.operation_id,token]);await sql.query('insert into public.fixture_storage_api_removed(id) values($1)',[deletion.object.id]);const reload=await rpc('crm_house_worker_document_removal_check',[deletion.job.operation_id,token]);assert.equal(reload.object_missing,true);const result=await rpc('crm_house_worker_document_removal_complete',[deletion.job.operation_id,token]);assert.equal(result.refs_removed,2);assert.equal((await sql.query('select count(*) n from public.crm_document_scopes where resource_id=$1',[sourcePath])).rows[0].n,'0');const after=await payload();for(const index of [0,1])assert.deepEqual(after.houseTrackingWorkers[index],Object.fromEntries(Object.entries(before.houseTrackingWorkers[index]).filter(([key])=>!key.startsWith('document'))));for(const key of Object.keys(after).filter(key=>key!=='houseTrackingWorkers'))assert.deepEqual(after[key],before[key]);assert.equal(after.houseTrackingWorkers[0].hourlyRate,25.5);assert.deepEqual(await rpc('crm_house_worker_document_removal_complete',[deletion.job.operation_id,token]),result);assert.equal((await rpc('crm_house_worker_document_removal_begin',deletion.args)).status,'completed');const stored=(await sql.query('select worker_documents,worker_revisions from app_private.house_worker_document_removal_jobs where operation_id=$1',[deletion.job.operation_id])).rows[0];assert(stored.worker_documents.every(row=>Object.keys(row).length===1&&row.id));assert.deepEqual(stored.worker_revisions,[]);await assert.rejects(sql.query("update public.crm_workspace_state set payload=$1 where workspace_id='oneaddress-riviera'",[before]),/permanently_disabled/);});
 await test('orphan job completes with zero worker refs and never updates workspace timestamps or payload',async()=>{const before=(await sql.query("select payload,updated_at::text exact_updated_at from public.crm_workspace_state where workspace_id='oneaddress-riviera'")).rows[0],token=randomUUID();await rpc('crm_house_worker_document_removal_check',[orphan.job.operation_id,token]);await sql.query('insert into public.fixture_storage_api_removed(id) values($1)',[orphan.object.id]);const result=await rpc('crm_house_worker_document_removal_complete',[orphan.job.operation_id,token]);assert.equal(result.refs_removed,0);assert.deepEqual((await sql.query("select payload,updated_at::text exact_updated_at from public.crm_workspace_state where workspace_id='oneaddress-riviera'")).rows[0],before);assert.deepEqual((await sql.query('select worker_documents from app_private.house_worker_document_removal_jobs where operation_id=$1',[orphan.job.operation_id])).rows[0].worker_documents,[]);});
 const summary={migrationFile:cleanupFile,boundary:'separate disposable PostgreSQL / published migrations + cleanup; metadata-only Storage/Auth facsimile; no physical deletion or Google',groups:results.length,passed:true,results};writeFileSync('/private/tmp/oar-house-worker-document-removal-sql-results.json',JSON.stringify(summary,null,2)+'\n',{mode:0o600});writeFileSync('/private/tmp/oar-house-worker-document-removal-sql-status.private.json',JSON.stringify({database,url:target.toString()},null,2)+'\n',{mode:0o600});console.log(JSON.stringify({groups:results.length,passed:true,boundary:summary.boundary}));
}finally{await sql.end();}
