require('./register-typescript.cjs');
const test=require('node:test'),assert=require('node:assert/strict');
const {LanguagePreference,accountPreferenceKey,PREFERENCE_PREFIX}=require('../../lib/i18n/preference.ts');
const {formatScreenDate,formatScreenMoney}=require('../../lib/i18n/format.ts');
const A='00000000-0000-4000-8000-000000000001',B='00000000-0000-4000-8000-000000000002';
function store(initial={}){const values=new Map(Object.entries(initial));return {values,getItem:key=>values.get(key)||null,setItem:(key,value)=>values.set(key,value)};}
test('default FR and only strict language codes/UUID keys',()=>{const s=store({[accountPreferenceKey(A)]:'de'}),p=new LanguagePreference(()=>s);p.hydrate();p.bindAccount(A);assert.equal(p.getSnapshot().language,'fr');p.choose('de');assert.equal(s.values.get(accountPreferenceKey(A)),'de');p.choose('en');assert.equal(s.values.get(accountPreferenceKey(A)),'en');assert.equal(accountPreferenceKey('email@example.invalid'),null);assert.equal(accountPreferenceKey('../token'),null);assert.deepEqual([...s.values.values()].filter(v=>v!=='de'),['en']);});
test('two account choices remain separate through switching, token refresh and reload',()=>{const s=store(),p=new LanguagePreference(()=>s);p.hydrate();p.bindAccount(A);p.choose('en');p.bindAccount(B);assert.equal(p.getSnapshot().language,'fr');p.choose('fr');p.bindAccount(A);assert.equal(p.getSnapshot().language,'en');const previous=p.getSnapshot();p.bindAccount(A);assert.equal(p.getSnapshot(),previous);const q=new LanguagePreference(()=>s);q.bindAccount(A);q.hydrate();assert.equal(q.getSnapshot().language,'en');q.bindAccount(B);assert.equal(q.getSnapshot().language,'fr');});
test('explicit anonymous choice seeds only unsaved account and never overwrites saved account',()=>{const s=store({[accountPreferenceKey(A)]:'fr'}),p=new LanguagePreference(()=>s);p.hydrate();p.choose('en');p.bindAccount(A);assert.equal(p.getSnapshot().language,'fr');assert.equal(s.getItem(accountPreferenceKey(A)),'fr');p.bindAccount(null);p.choose('en');p.bindAccount(B);assert.equal(p.getSnapshot().language,'en');assert.equal(s.getItem(accountPreferenceKey(B)),'en');});
test('remembered anonymous setting alone does not seed a new account or leak previous account',()=>{const s=store({[PREFERENCE_PREFIX+'anonymous']:'en'}),p=new LanguagePreference(()=>s);p.hydrate();assert.equal(p.getSnapshot().language,'en');p.bindAccount(A);assert.equal(p.getSnapshot().language,'fr');p.choose('en');p.bindAccount(B);assert.equal(p.getSnapshot().language,'fr');p.bindAccount(null);assert.equal(p.getSnapshot().language,'en');p.bindAccount(B);assert.equal(p.getSnapshot().language,'fr');});
test('unavailable browser storage retains account scoped session choices',()=>{const p=new LanguagePreference(()=>{throw new Error('blocked')});p.hydrate();p.choose('en');p.bindAccount(A);assert.equal(p.getSnapshot().language,'en');p.bindAccount(B);assert.equal(p.getSnapshot().language,'fr');p.choose('en');p.bindAccount(A);assert.equal(p.getSnapshot().language,'en');});
test('language notifications do not fire on auth refresh or same choice',()=>{const p=new LanguagePreference(()=>store());let calls=0;p.subscribe(()=>calls++);p.hydrate();p.bindAccount(A);p.choose('en');p.bindAccount(A);p.choose('en');assert.equal(calls,2);});
test('civil dates stay on the same day; instant dates use Paris and 24h',()=>{assert.match(formatScreenDate('2026-03-29','en',{day:'numeric',month:'long',year:'numeric'}),/29 March 2026/);assert.match(formatScreenDate('2026-03-29','fr',{day:'numeric',month:'long',year:'numeric'}),/29 mars 2026/);assert.equal(formatScreenDate('2026-10-08T21:15:00Z','en',{hour:'2-digit',minute:'2-digit'}),'23:15');assert.equal(formatScreenDate('','fr'),'—');});
test('amounts stay euros with identical numerical value',()=>{assert.match(formatScreenMoney(1234.56,'fr'),/1.234,56/);assert.equal(formatScreenMoney(1234.56,'en'),'€1,234.56');});

test("screen money retains existing cent rounding",()=>{const {normalizeEuroAmount}=require("../../lib/currency.ts");for(const value of [10.075,1.005,-10.075,1234.56]) assert.equal(formatScreenMoney(value,"en"),new Intl.NumberFormat("en-GB",{style:"currency",currency:"EUR",maximumFractionDigits:2}).format(normalizeEuroAmount(value)));});
