/** Actual integrated candidate + fictitious transport. No real Auth/RPC/Drive proof. */
import assert from 'node:assert/strict';
import {createRequire} from 'node:module';
import {mkdirSync,writeFileSync} from 'node:fs';
import {installFixture,groups,modules} from './fixture.mjs';
const require=createRequire(import.meta.url),{chromium,webkit}=require(process.env.PLAYWRIGHT_MODULE||'/Users/vg/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const origin='http://127.0.0.1:3299',out='/private/tmp/oar-bilingual-20261008/browser/modules';mkdirSync(out,{recursive:true});
const results=[];const mobile=page=>page.viewportSize().width<1024,menu=page=>page.locator(mobile(page)?'.unified-more-panel':'.sidebar');
async function more(page){if(mobile(page)&&!await menu(page).isVisible())await page.locator('#unified-more-trigger').click();}
async function closeMore(page){if(mobile(page)&&await menu(page).isVisible())await menu(page).locator('.unified-more-close').click();}
async function choose(page,language){const name=language==='en'?'English — EN':'Français — FR';if(await page.getByRole('dialog').isVisible().catch(()=>false)){if(mobile(page)&&!await menu(page).isVisible())await page.locator('#unified-more-trigger').evaluate(button=>button.click());await menu(page).locator('[data-language-selector]').getByRole('button',{name,exact:true}).evaluate(button=>button.click());await page.waitForFunction(lang=>document.documentElement.lang===lang,language==='en'?'en-GB':'fr');if(mobile(page)&&await menu(page).isVisible())await menu(page).locator('.unified-more-close').evaluate(button=>button.click());return;}await more(page);await menu(page).locator('[data-language-selector]').getByRole('button',{name,exact:true}).click();await page.waitForFunction(lang=>document.documentElement.lang===lang,language==='en'?'en-GB':'fr');}
async function navigate(page,id){await more(page);const group=groups.find(g=>g.modules.includes(id));if(group){const button=menu(page).locator(`[data-navigation-group="${group.id}"]`);if(await button.getAttribute('aria-expanded')!=='true')await button.click();}await menu(page).locator(`[data-navigation-module="${id}"]`).click();await page.waitForFunction(id=>[...document.querySelectorAll('[data-navigation-module]')].some(n=>n.dataset.navigationModule===id&&n.getAttribute('aria-current')==='page'),id);await closeMore(page);}
async function login(page,fixture){await page.goto(origin);await page.locator('input[type="email"]').fill(fixture.user.email);await page.locator('input[autocomplete="current-password"]').fill('Bilingual-Fictive-2026!');await page.locator('form button:not([type="button"])').first().click();await page.locator('[data-navigation-module="contacts"]').first().waitFor({state:'attached'});await navigate(page,'contacts');await page.getByText('Alice Alice Exemple',{exact:true}).first().waitFor();}
async function fillContactSearch(page,value){if(mobile(page)){await page.locator('.mobile-crm-header .mobile-icon-button').first().click();await page.locator('.mobile-search-sheet input[type=search]').fill(value);await page.locator('.mobile-search-sheet .primary-button').click();}else await page.locator('.crm-topbar-search').fill(value);return page.locator('.crm-topbar-search');}
// Existing periodic session/user checks remain enabled; they are reads, not language-triggered Auth mutations.
function auditSince(fixture){return {authMutations:fixture.audit.auth.filter(value=>value!=='simulated user').length,writes:fixture.audit.writes.length,blocked:fixture.audit.blocked.length};}
for(const engine of (process.env.I18N_ENGINE?[process.env.I18N_ENGINE]:['chromium','webkit'])){
 const browser=await(engine==='chromium'?chromium.launch({headless:true,channel:'chrome'}):webkit.launch({headless:true}));
 try{for(const width of process.env.I18N_WIDTH?[Number(process.env.I18N_WIDTH)]:[1440,390]){
  const context=await browser.newContext({viewport:{width,height:width===390?667:900},isMobile:width===390,hasTouch:width===390}),fixture=await installFixture(context,'full',origin),page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));const name=engine+'-'+width;
  try{
   await login(page,fixture);
   const destinations={};
   for(const destination of modules.filter(id=>id!=='izord')){
    await navigate(page,destination);await choose(page,'fr');await closeMore(page);const url=page.url();await page.locator('h1,h2').first().waitFor({state:'attached'});await page.waitForLoadState('networkidle');await page.waitForTimeout(250);const before=auditSince(fixture),headFr=await page.locator('h1,h2').allTextContents();
    await choose(page,'en');await closeMore(page);assert.equal(page.url(),url);assert.deepEqual(auditSince(fixture),before,'Language toggle has no sign-in, sign-out, token request, write, or external call');const headEn=await page.locator('h1,h2').allTextContents();if(destination==='contacts')assert.equal(await page.locator('.shared-db-status-desktop span').textContent(),'Shared database loaded from Supabase.','Message follows current render language');console.log('MODULE '+name+' '+destination);
    assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+2),true,destination+' no viewport overflow');
    if(['contacts','tasks','houseTracking','monthlyCharges'].includes(destination)){await page.screenshot({path:`${out}/${name}-${destination}-en.png`});await choose(page,'fr');await closeMore(page);await page.screenshot({path:`${out}/${name}-${destination}-fr.png`});}
    await choose(page,'fr');await closeMore(page);assert.deepEqual(await page.locator('h1,h2').allTextContents(),headFr,'FR round trip headings restored');destinations[destination]={url,headFr,headEn};
   }
   // Contact fields are the same DOM nodes, canonical option values and text are retained.
   await navigate(page,'contacts');const form=page.locator('form.contact-create-form'),field=form.locator('input[name="name"]');await field.fill('Brouillon français — André');const kind=form.locator('select[name="kind"]');await kind.selectOption('Propriétaire');const original=await field.elementHandle();const search=await fillContactSearch(page,'alice');
   await choose(page,'en');await closeMore(page);assert.equal(await field.inputValue(),'Brouillon français — André');assert.equal(await kind.inputValue(),'Propriétaire');assert.equal(await original.evaluate(node=>node.isConnected),true);assert.equal(await search.inputValue(),'alice');assert.equal(await kind.locator('option[value="Propriétaire"]').textContent(),'Owner');
   await page.getByText('Alice Alice Exemple',{exact:true}).first().waitFor();assert.equal(await page.getByText('Bruno Démonstration',{exact:true}).count(),0,'Contact filter retained');
   await choose(page,'fr');await closeMore(page);await field.fill('');await kind.selectOption('Client');await fillContactSearch(page,'');page.on('dialog',dialog=>dialog.accept());
   await navigate(page,'tasks');assert.equal(await page.getByText('TÂCHE PRIVÉE HORS PROJECTION',{exact:false}).count(),0,'Private stale tasks absent');
   const newTask=page.getByRole('button',{name:/Ajouter une tâche/}).first();if(await newTask.count()){await newTask.click();const dialog=page.getByRole('dialog');await dialog.waitFor();const title=dialog.locator('input').first();await title.fill('Tâche partagée en français');const handle=await title.elementHandle();await choose(page,'en');await closeMore(page);assert.equal(await dialog.isVisible(),true);assert.equal(await title.inputValue(),'Tâche partagée en français');assert.equal(await handle.evaluate(node=>node.isConnected),true);await choose(page,'fr');await closeMore(page);await dialog.getByRole('button',{name:/Annuler|Fermer/}).last().click();}
   // An unsaved IZORD project keeps raw decimal strings and generated-slide content.
   await navigate(page,'izord');await choose(page,'fr');await closeMore(page);await page.getByRole('button',{name:'Nouveau projet',exact:true}).click();
   await page.locator('#izord-project').fill('Projet français — Antibes');await page.locator('#izord-acq').fill('1234,56');await page.locator('#izord-works').fill('123.45');
   const izordName=await page.locator('#izord-project').elementHandle(),izordUrl=page.url();const izordBefore=auditSince(fixture);const previewFr=await page.locator('[data-izord-generator]').locator('[class*=slide]').allTextContents();assert.ok(previewFr.length>1,'Real French slides present');
   await choose(page,'en');await closeMore(page);assert.equal(page.url(),izordUrl);assert.deepEqual(auditSince(fixture),izordBefore,'IZORD language change does not save or generate');
   assert.equal(await page.locator('#izord-project').inputValue(),'Projet français — Antibes');assert.equal(await page.locator('#izord-acq').inputValue(),'1234,56');assert.equal(await page.locator('#izord-works').inputValue(),'123.45');assert.equal(await izordName.evaluate(n=>n.isConnected),true);assert.deepEqual(await page.locator('[data-izord-generator]').locator('[class*=slide]').allTextContents(),previewFr,'Generated presentation content stays French');
   await page.screenshot({path:`${out}/${name}-izord-en.png`});await choose(page,'fr');await closeMore(page);assert.equal(await page.locator('#izord-acq').inputValue(),'1234,56');await page.screenshot({path:`${out}/${name}-izord-fr.png`});destinations.izord={url:izordUrl,rawDecimalsRetained:true,generatedPresentationUnchanged:true};
   assert.deepEqual(errors,[],'No browser exceptions');assert.deepEqual(fixture.audit.writes,[],'No business mutation or generation attempted');assert.deepEqual(fixture.audit.blocked,[],'No external connection attempted');results.push({name,status:'passed',browserVersion:browser.version(),destinations,audit:fixture.audit,errors});console.log('PASS '+name);
  }catch(error){await page.screenshot({path:`${out}/${name}-failure.png`});results.push({name,status:'failed',error:String(error),audit:fixture.audit,errors});throw error;}
  finally{writeFileSync(`${out}/results.json`,JSON.stringify(results,null,2));await context.close();}
 }}finally{await browser.close();}
}
