import assert from 'node:assert/strict';
import {writeFileSync} from 'node:fs';
import {connect,sql,grant,user,rpc,dir} from './local.mjs';
await connect();const u=await user('matrix');const ok=r=>{assert.ok([200,204].includes(r.status),JSON.stringify(r));return r.data;};const denied=r=>assert.ok(r.status>=400,JSON.stringify(r));const payload=async()=>(await sql.query("select payload from crm_workspace_state where workspace_id='oneaddress-riviera'")).rows[0].payload;const results=[];
try{
 await grant(u,{tasks:{level:'contribute'},contacts:{level:'contribute',sensitive:{bank_read:true,bank_write:true}}});const before=await payload();const t=ok(await rpc('crm_read_module',u.token,{p_module:'tasks'}));
 for(const args of [{p_patch:null},{p_delete:null},{p_patch:[],p_delete:false},{p_patch:'x'}])denied(await rpc('crm_mutate_record',u.token,{p_module:'tasks',p_collection:'tasks',p_id:'unified-tasks',p_revision:t.revision,p_patch:{},...args}));
 const c=ok(await rpc('crm_read_module',u.token,{p_module:'contacts'}));denied(await rpc('crm_bank_action',u.token,{p_contact:'unified-contacts',p_action:null,p_account:{id:'bank-fictional'},p_revision:c.revision}));assert.deepEqual(await payload(),before);results.push({name:'Null/array/scalar patches and null deletion/action cannot mutate any payload field',status:'passed'});
 // Own new fixtures only; they are removed after the test without replacing shared state.
 const records=[{id:'unified-boundary-draft',title:'DRAFT_MUST_STAY_PRIVATE',status:'Draft',bookingStatus:'À préparer'},{id:'unified-boundary-accepted',title:'Réservation autorisée',status:'Accepted',bookingStatus:'À préparer'}];await sql.query("update crm_workspace_state set payload=jsonb_set(payload,'{quotes}',(select coalesce(jsonb_agg(r),'[]') from jsonb_array_elements(payload->'quotes')r where r->>'id' not like 'unified-boundary-%')||$1::jsonb) where workspace_id='oneaddress-riviera'",[JSON.stringify(records)]);
 await grant(u,{bookings:{level:'contribute'}});let b=ok(await rpc('crm_read_module',u.token,{p_module:'bookings'}));assert.ok(!JSON.stringify(b).includes('DRAFT_MUST_STAY_PRIVATE'));assert.ok(b.collections.bookings.some(r=>r.id==='unified-boundary-accepted'));denied(await rpc('crm_mutate_record',u.token,{p_module:'bookings',p_collection:'quotes',p_id:'unified-boundary-accepted',p_patch:{bookingStatus:'Confirmé'},p_revision:b.revision}));await grant(u,{bookings:{level:'contribute'},quotes:{level:'contribute'}});b=ok(await rpc('crm_read_module',u.token,{p_module:'bookings'}));const changed=ok(await rpc('crm_mutate_record',u.token,{p_module:'bookings',p_collection:'quotes',p_id:'unified-boundary-accepted',p_patch:{bookingStatus:'Confirmé'},p_revision:b.revision}));assert.equal(changed.collections.bookings.find(r=>r.id==='unified-boundary-accepted').bookingStatus,'Confirmé');denied(await rpc('crm_mutate_record',u.token,{p_module:'bookings',p_collection:'quotes',p_id:'unified-boundary-draft',p_patch:{bookingStatus:'Confirmé'},p_revision:changed.revision}));results.push({name:'Bookings expose only Accepted quotes; coupled edits require both modules and native status values',status:'passed'});
 console.log(JSON.stringify(results));writeFileSync(dir+'/boundaries.json',JSON.stringify(results,null,2));
}finally{await sql.query("update crm_workspace_state set payload=jsonb_set(payload,'{quotes}',(select coalesce(jsonb_agg(r),'[]') from jsonb_array_elements(payload->'quotes')r where r->>'id' not like 'unified-boundary-%')) where workspace_id='oneaddress-riviera'");await sql.end();}
