import assert from 'node:assert/strict';
import {createRequire} from 'node:module';
import {readFileSync,writeFileSync} from 'node:fs';
import {connect,sql,user,grant,dir} from './local.mjs';
const require=createRequire(import.meta.url);const {chromium}=require('/tmp/izord-playwright-runtime-20260917/node_modules/playwright');
await connect();const browser=await chromium.launch({headless:true,channel:'chrome'}),results=[];
async function context(){const c=await browser.newContext({viewport:{width:1440,height:1000}});await c.route('**/*',r=>{const u=new URL(r.request().url());return u.hostname==='127.0.0.1'||['data:','blob:'].includes(u.protocol)?r.continue():r.abort();});return c;}
async function login(page,name){const u=await user(name);await page.goto('http://127.0.0.1:3160');await page.getByLabel('Email',{exact:true}).fill(u.email);await page.getByLabel('Mot de passe',{exact:true}).fill(u.password);await page.getByRole('button',{name:'Se connecter',exact:true}).click();return u;}
async function test(name,fn){try{await fn();results.push({name,status:'passed'});console.log('PASS '+name);}catch(e){results.push({name,status:'failed',error:e.message});throw e;}finally{writeFileSync(dir+'/browser-flows.json',JSON.stringify(results,null,2));}}
try{
 await test('Local email invitation verification and explicit acceptance in real browser',async()=>{const c=await context(),page=await c.newPage();const mail=JSON.parse(readFileSync(dir+'/mail.private.json'));await page.goto(mail.link);await page.getByLabel('Choisissez un mot de passe').fill('Local-Invitation-2026!');await page.getByRole('button',{name:'Accepter mon invitation'}).click();await page.getByRole('heading',{name:'Tâches',exact:true}).first().waitFor({timeout:15000});const grants=(await sql.query('select g.module,g.level from crm_module_grants g join auth.users u on u.id=g.user_id where u.email=$1',[mail.email])).rows;assert.deepEqual(grants,[{module:'tasks',level:'read'}]);assert.equal(await page.getByRole('button',{name:'Ajouter — Tâches'}).count(),0);await c.close();});
 await test('Administration saves actual rights; dirty navigation can be cancelled',async()=>{const c=await context(),page=await c.newPage();await login(page,'admin');await page.getByRole('navigation',{name:'Navigation principale',exact:true}).getByRole('button',{name:'Administration'}).click();await page.getByRole('button',{name:/unified-tasks@example.invalid/}).click();await page.getByLabel('Droit Tâches',{exact:true}).selectOption('read');await page.getByRole('button',{name:'Enregistrer',exact:true}).click();await page.getByText('Droits enregistrés et confirmés par le serveur.').waitFor();const target=await user('tasks');assert.equal((await sql.query("select level from crm_module_grants where user_id=$1 and module='tasks'",[target.id])).rows[0].level,'read');await page.getByLabel('Droit Tâches',{exact:true}).selectOption('contribute');await page.getByRole('button',{name:'Enregistrer',exact:true}).click();await page.getByText('Droits enregistrés et confirmés par le serveur.').waitFor();await c.close();
 const h=await context(),p=await h.newPage();await login(p,'house');await p.getByRole('button',{name:'Ajouter — Maisons',exact:true}).click();await p.locator('form').getByLabel('Nom',{exact:true}).fill('Saisie à conserver');p.once('dialog',d=>d.dismiss());await p.getByRole('navigation',{name:'Navigation principale',exact:true}).getByRole('button',{name:'Planning'}).click();assert.equal(await p.locator('form').getByLabel('Nom',{exact:true}).inputValue(),'Saisie à conserver');await h.close();});
 await test('Single-module edit persists with actual RPC and preserves foreign collections',async()=>{const c=await context(),p=await c.newPage();await login(p,'tasks');await p.getByRole('button',{name:'Ajouter — Tâches'}).click();await p.locator('form').getByLabel('Titre',{exact:true}).fill('Tâche saisie dans la démonstration');await p.locator('form').getByLabel('Statut',{exact:true}).fill('À faire');await p.locator('form').getByLabel('Échéance',{exact:true}).fill('2026-09-20');const before=(await sql.query("select payload-'tasks' rest from crm_workspace_state where workspace_id='oneaddress-riviera'")).rows[0].rest;await p.getByRole('button',{name:'Enregistrer',exact:true}).click();await p.getByRole('cell',{name:'Tâche saisie dans la démonstration',exact:true}).waitFor();assert.deepEqual((await sql.query("select payload-'tasks' rest from crm_workspace_state where workspace_id='oneaddress-riviera'")).rows[0].rest,before);await c.close();});
 await test('Revocation cancels a delayed real module response; no stale data is rendered',async()=>{const u=await user('revoked');await grant(u,{contacts:{level:'read'}});const c=await context(),p=await c.newPage();let held,release;const received=new Promise(r=>held=r);const gate=new Promise(r=>release=r);await p.route('**/rest/v1/rpc/crm_read_module',async route=>{const response=await route.fetch();held();await gate;try{await route.fulfill({response});}catch{/* An aborted fetch is expected after the verified revocation. */}});await login(p,'revoked');await received;await sql.query('update crm_access_profiles set active=false,revision=revision+1 where user_id=$1',[u.id]);await p.evaluate(()=>window.dispatchEvent(new Event('focus')));await p.getByRole('heading',{name:'Aucun accès autorisé'}).waitFor({timeout:15000});release();await p.waitForTimeout(250);assert.ok(!(await p.locator('body').innerText()).includes('Camille Démonstration'));assert.equal(await p.locator('.module-workspace table').count(),0);await p.getByRole('heading',{name:'Aucun accès autorisé'}).waitFor();await c.close();});
}finally{await browser.close();await sql.end();}
