import assert from 'node:assert/strict';
import {writeFileSync} from 'node:fs';
import {connect,sql,user,grant,rpc,fullGrants,dir} from './local.mjs';
await connect();const results=[];const ok=r=>{assert.ok(r.status>=200&&r.status<300,JSON.stringify(r.data));return r.data;};const deny=r=>assert.ok(r.status>=400,JSON.stringify(r.data));
const payload=async()=>(await sql.query("select payload from crm_workspace_state where workspace_id='oneaddress-riviera'")).rows[0].payload;
async function check(name,fn){if(process.env.UNIFIED_TEST_FILTER&&!name.includes(process.env.UNIFIED_TEST_FILTER))return;try{await fn();results.push({name,status:'passed'});console.log('PASS '+name);}catch(e){results.push({name,status:'failed',error:e.message});throw e;}finally{writeFileSync(dir+(process.env.UNIFIED_TEST_FILTER?'/finalisation-sql-reprise.json':'/finalisation-sql.json'),JSON.stringify(results,null,2));}}
try{
 const u=await user('business'),admin=await user('admin');await grant(u,Object.fromEntries(Object.entries(fullGrants).filter(([k])=>k!=='izord')));await grant(admin,fullGrants,true,'admin');
 const before=await payload();const next=structuredClone(before);const fixture={
 contacts:[{id:'review-contact',name:'Entreprise fictive',firstName:'Camille',companyName:'Entreprise fictive',kind:'Prestataire',email:'business@example.invalid',phone:'',city:'Nice',postalAddress:'Adresse fictive\nDeuxième ligne',budget:0,source:'Test local',notes:'PRIVATE-PRESERVE',supplierCategory:'Jardinier',supplierStatus:'Actif',supplierBankAccounts:[{id:'review-bank',iban:'FICTIONAL-NOT-AN-IBAN',accountHolder:'Fictif',status:'À vérifier',isPrimary:false,createdAt:'2026-09-18'}]}],
 tasks:[{id:'review-task',title:'Organiser la visite fictive',status:'À faire',owner:'Matteo',linkedTo:'review-lead',dueDate:'2026-09-25',privateMetadata:{keep:true}}],
 leads:[{id:'review-lead',category:'Villa',contactName:'Entreprise fictive',assetType:'Property',assetId:'review-property',status:'Nouveau',value:100,priority:'Moyenne',nextAction:'Appeler',dueDate:'2026-09-25',rentalStartDate:'2026-09-25',rentalEndDate:'2026-09-27',notes:'PRIVATE-LEAD'}],
 properties:[{id:'review-property',name:'Villa de démonstration',city:'Nice',type:'Villa',status:'Disponible',price:100,owner:'Entreprise fictive',bedrooms:2,surface:80}],
 vendorInvoices:[{id:'review-invoice',contactId:'review-contact',contactName:'Entreprise fictive',title:'Facture de démonstration',invoiceReference:'LOCAL-18',invoiceDate:'2026-09-18',dueDate:'2026-09-25',amount:100,paidAmount:10,status:'Partiellement payé',category:'Jardinier',notes:'PRIVATE-INVOICE',invoiceDocumentStoragePath:'legacy-unclassified',paymentBankAccountId:'review-bank',sourceQuoteId:'review-vquote',privatePayments:[{keep:1}]}],
 vendorQuotes:[{id:'review-vquote',contactId:'review-contact',contactName:'Entreprise fictive',title:'Entretien de démonstration',quoteReference:'LOCAL-DEV-18',quoteDate:'2026-09-18',validUntil:'2026-09-25',amount:100,status:'Validé',linkedInvoiceId:'review-invoice',category:'Jardinier'}],
 houseTrackingHouses:[{id:'review-house',name:'Maison de démonstration',address:'Adresse fictive',notes:'PRIVATE-HOUSE'}],
 houseTrackingWorkers:[{id:'review-worker',contactName:'Camille fictif',contactId:'review-contact',role:'Jardinier',status:'Actif',hourlyRate:20,notes:'PRIVATE-WORKER'}],
 houseTimeEntries:[{id:'review-hours',houseId:'review-house',houseName:'Maison de démonstration',workerId:'review-worker',workerName:'Camille fictif',date:'2026-09-18',startTime:'09:00',endTime:'10:00',breakMinutes:0,hourlyRate:20,privateInfo:{keep:1}}],
 housePayments:[{id:'review-hpayment',houseId:'review-house',houseName:'Maison de démonstration',workerId:'review-worker',workerName:'Camille fictif',date:'2026-09-18',amount:10,method:'Autre',privateProof:'KEEP'}],
 quotes:[{id:'review-quote',clientName:'Entreprise fictive',title:'Séjour de démonstration',location:'Nice',guestCount:'2',categories:['Villa'],items:[{id:'review-line',category:'Villa',description:'Location fictive',unitPrice:100,billingUnit:'day',deposit:10}],unitPrice:100,startDate:'2026-09-25',endDate:'2026-09-27',validityDate:'2026-09-24',paymentTerms:'',cancellationTerms:'',included:'',excluded:'',notes:'PRIVATE-QUOTE',status:'Accepted',createdAt:'2026-09-18',bookingStatus:'À préparer'}],
 planningEntries:[{id:'review-planning',title:'Visite de démonstration',type:'Autre',planningCategory:'Villa',status:'Prévu',priority:'Normal',contactName:'Entreprise fictive',assetType:'Property',assetId:'review-property',startDate:'2026-09-25',endDate:'2026-09-25',startTime:'10:00',endTime:'11:00',blocksAvailability:true,notes:'PRIVATE-PLANNING'}]
 };
 for(const [c,rows]of Object.entries(fixture))next[c]=[...(next[c]??[]).filter(r=>!rows.some(x=>x.id===r.id)),...rows];await sql.query("update crm_workspace_state set payload=$1 where workspace_id='oneaddress-riviera'",[next]);
 const rev=async m=>ok(await rpc('crm_read_module',u.token,{p_module:m})).revision;
 const mutate=async(m,c,id,patch,remove=false)=>rpc('crm_mutate_record',u.token,{p_module:m,p_collection:c,p_id:id,p_patch:patch,p_revision:await rev(m),p_delete:remove});
 await check('Partial row edits preserve omitted RIB, private notes, payment/document links and house subcollections',async()=>{for(const [m,c,id,p]of [['contacts','contacts','review-contact',{city:'Cannes'}],['vendorInvoices','vendorInvoices','review-invoice',{title:'Facture de démonstration modifiée'}],['houseTracking','houseTimeEntries','review-hours',{breakMinutes:15}],['houseTracking','housePayments','review-hpayment',{method:'Espèces'}]]){const old=await payload();ok(await mutate(m,c,id,p));const after=await payload();for(const key of Object.keys(old))if(key!==c)assert.deepEqual(after[key],old[key]);const a=after[c].find(r=>r.id===id),b=old[c].find(r=>r.id===id);for(const k of Object.keys(b))if(!Object.keys(p).includes(k)&&!['updatedAt','updatedBy'].includes(k))assert.deepEqual(a[k],b[k],c+'.'+k);}});
 await check('Direct deletion preserves banking, paid invoice, nested references and worker history',async()=>{for(const [m,c,id]of [['contacts','contacts','review-contact'],['vendorInvoices','vendorInvoices','review-invoice'],['houseTracking','houseTrackingWorkers','review-worker'],['quotes','quotes','review-quote']]){if(c==='quotes'){const w=await payload();w.quotes.find(r=>r.id===id).depositReceived=10;await sql.query("update crm_workspace_state set payload=$1 where workspace_id='oneaddress-riviera'",[w]);}const old=await payload();deny(await mutate(m,c,id,{},true));assert.deepEqual(await payload(),old);}});
 await check('Enums, dates, references and malformed quote lines rejected without writes',async()=>{for(const [m,c,id,p]of [['tasks','tasks','review-task',{status:'invented'}],['planning','planningEntries','review-planning',{startDate:'2026-02-30'}],['houseTracking','houseTimeEntries','review-hours',{startTime:'09:17'}],['tasks','tasks','review-task',{linkedTo:'missing'}],['quotes','quotes','review-quote',{items:[{unitPrice:10,billingUnit:'invented'}]}]]){const old=await payload();deny(await mutate(m,c,id,p));assert.deepEqual(await payload(),old);}});
 await check('Existing contact conversion clears stale supplier classification, address omission preserves and explicit empty clears',async()=>{ok(await mutate('contacts','contacts','review-contact',{kind:'Client'}));let row=(await payload()).contacts.find(r=>r.id==='review-contact');assert.equal(row.supplierCategory,'');assert.notEqual(row.relationshipStatus,'Prestataire');assert.equal(row.postalAddress,fixture.contacts[0].postalAddress);ok(await mutate('contacts','contacts','review-contact',{postalAddress:''}));row=(await payload()).contacts.find(r=>r.id==='review-contact');assert.equal(row.postalAddress,'');ok(await mutate('contacts','contacts','review-contact',{kind:'Prestataire',supplierCategory:'Jardinier',postalAddress:fixture.contacts[0].postalAddress}));});
 await check('Minimal reference RPC excludes bank, private notes, email and unknown nested values',async()=>{const refs=ok(await rpc('crm_reference_options',u.token,{p_module:'contacts'}));const text=JSON.stringify(refs);for(const field of ['supplierBankAccounts','PRIVATE-PRESERVE','postalAddress','email'])assert.ok(!text.includes(field));const none=await user('none');deny(await rpc('crm_reference_options',none.token,{p_module:'contacts'}));});
 await check('Ordinary invitation does not widen existing IZORD roles or assignments',async()=>{const x=await user('review-izord');await grant(x,{},false,'reader');const i=ok(await rpc('crm_invite_prepare',admin.token,{p_email:x.email,p_grants:{izord:{level:'contribute'}},p_izord_role:'admin'}));deny(await rpc('crm_invite_accept',x.token,{p_token:i.token}));assert.equal((await sql.query("select role from app_memberships where user_id=$1 and workspace_id='izord'",[x.id])).rows[0].role,'reader');ok(await rpc('crm_invite_revoke',admin.token,{p_id:i.id}));});
 await check('Pending invitations listed without secret; revocation, retry supersession and expiry enforced',async()=>{const x=await user('review-invite');await grant(x,{});const a=ok(await rpc('crm_invite_prepare',admin.token,{p_email:x.email,p_grants:{tasks:{level:'read'}}}));const b=ok(await rpc('crm_invite_prepare',admin.token,{p_email:x.email,p_grants:{tasks:{level:'read'}}}));deny(await rpc('crm_invite_accept',x.token,{p_token:a.token}));const list=ok(await rpc('crm_admin_users',admin.token));assert.ok(list.invitations.some(i=>i.id===b.id));assert.ok(!JSON.stringify(list).includes(b.token));ok(await rpc('crm_invite_revoke',admin.token,{p_id:b.id}));deny(await rpc('crm_invite_accept',x.token,{p_token:b.token}));});
 await check('Limited workflow quote lines and calendar patch succeed without global access',async()=>{const raw=ok(await rpc('crm_read_module',u.token,{p_module:'quotes'}));assert.equal(raw.collections.quotes.find(q=>q.id==='review-quote').items[0].unitPrice,100);ok(await mutate('quotes','quotes','review-quote',{title:'Séjour de démonstration'}));ok(await mutate('planning','planningEntries','review-planning',{startDate:'2026-09-26',endDate:'2026-09-26'}));assert.equal(ok(await rpc('crm_access_snapshot',u.token)).fullAccess,false);});
}finally{await sql.end();}
