import assert from 'node:assert/strict';
import {createRequire} from 'node:module';
import {writeFileSync} from 'node:fs';
import {connect,sql,user,grant,dir} from './local.mjs';
const require=createRequire(import.meta.url),{chromium}=require('/tmp/izord-playwright-runtime-20260917/node_modules/playwright');
await connect();const browser=await chromium.launch({channel:'chrome',headless:true}),results=[];
async function context(){const c=await browser.newContext({viewport:{width:1440,height:1000}});await c.route('**/*',r=>new URL(r.request().url()).hostname==='127.0.0.1'?r.continue():r.abort());return c;}
async function login(p,name){const u=await user(name);await p.goto('http://127.0.0.1:3160');await p.getByLabel('Email',{exact:true}).fill(u.email);await p.getByLabel('Mot de passe',{exact:true}).fill(u.password);await p.getByRole('button',{name:'Se connecter',exact:true}).click();return u;}
async function switchAccount(p,u){await p.evaluate(async(credentials)=>{let client;window.webpackChunk_N_E.push([[Math.random()],{},require=>{const modules=require.c?Object.values(require.c):Object.entries(require.m).filter(([,f])=>String(f).includes('http://127.0.0.1:55431')).map(([id])=>({exports:require(id)}));for(const e of modules){for(const v of Object.values(e.exports||{})){if(v&&typeof v==='object'&&v.auth&&typeof v.auth.refreshSession==='function'&&typeof v.from==='function'){client=v;break;}}if(client)break;}}]);if(!client)throw Error('SDK missing');const r=await client.auth.signInWithPassword(credentials);if(r.error)throw Error('Local Auth account switch failed');},{email:u.email,password:u.password});}
async function test(name,fn){if(process.env.UNIFIED_TEST_FILTER&&!process.env.UNIFIED_TEST_FILTER.split('|').some(f=>name.includes(f)))return;try{await fn();results.push({name,status:'passed'});console.log('PASS '+name);}catch(e){results.push({name,status:'failed',error:e.message});console.error('FAIL '+name+': '+e.message);}finally{writeFileSync(dir+(process.env.UNIFIED_TEST_FILTER?'/finalisation-browser-reprise.json':'/finalisation-browser.json'),JSON.stringify(results,null,2));}}
try{
 const none=await user('none');await grant(none,{});
 await test('U2 delayed real export is neutralized after real Auth A to B switch',async()=>{const a=await user('late-export');await grant(a,{tasks:{level:'contribute',sensitive:{export:true}}});const c=await context(),p=await c.newPage();try{const downloads=[];p.on('download',d=>downloads.push(d.suggestedFilename()));let got,release;const reached=new Promise(r=>got=r),gate=new Promise(r=>release=r);await p.route('**/rest/v1/rpc/crm_export_module',async route=>{const response=await route.fetch();got();await gate;try{await route.fulfill({response});}catch{}});await login(p,'late-export');await p.getByRole('button',{name:'Exporter ce module'}).click();await reached;await switchAccount(p,none);await p.getByRole('heading',{name:'Aucun accès autorisé'}).waitFor();release();await p.waitForTimeout(500);assert.deepEqual(downloads,[]);}finally{await c.close();}});
 await test('U2 delayed real document reservation cannot start Storage upload under B',async()=>{const a=await user('late-document');await grant(a,{documents:{level:'contribute'},tasks:{level:'contribute'}});const c=await context(),p=await c.newPage();try{p.on('dialog',d=>d.accept());let uploads=0;p.on('request',r=>{if(r.url().includes('/storage/v1/object/')&&r.method()==='POST')uploads++;});let got,release;const reached=new Promise(r=>got=r),gate=new Promise(r=>release=r);await p.route('**/rest/v1/rpc/crm_new_document',async route=>{const response=await route.fetch();got();await gate;try{await route.fulfill({response});}catch{}});await login(p,'late-document');await p.locator('#task-create-form').waitFor();await p.getByRole('navigation',{name:'Navigation principale',exact:true}).getByRole('button',{name:'Documents',exact:true}).click();await p.locator('form label').filter({hasText:/^Module propriétaire/}).locator('select').selectOption('tasks');await p.locator('form label').filter({hasText:/^Élément propriétaire/}).locator('select').selectOption('review-task');await p.getByLabel('Fichier',{exact:true}).setInputFiles({name:'late-fictif.pdf',mimeType:'application/pdf',buffer:Buffer.from('%PDF-1.4\nLocal fictitious file\n%%EOF')});await p.getByRole('button',{name:'Envoyer le document'}).click();await reached;await switchAccount(p,none);await p.getByRole('heading',{name:'Aucun accès autorisé'}).waitFor();release();await p.waitForTimeout(500);assert.equal(uploads,0);}finally{await c.close();}});
 await test('Existing task form saves owner and authorized lead reference via targeted RPC only',async()=>{const u=await user('business');const c=await context(),p=await c.newPage();try{const paths=[];p.on('request',r=>{if(r.url().includes('/rest/v1/'))paths.push(r.url());});await login(p,'business');await p.getByRole('navigation',{name:'Navigation principale',exact:true}).getByRole('button',{name:'Tâches',exact:true}).click();await p.locator('#task-create-form').waitFor();const f=p.locator('#task-create-form');await f.locator('[name=title]').fill('Tâche métier finalisée');await f.locator('[name=owner]').fill('Vincent');await f.locator('[name=linkedTo]').selectOption('review-lead');await f.locator('[name=dueDate]').fill('2026-09-25');const before=(await sql.query("select payload-'tasks' p from crm_workspace_state where workspace_id='oneaddress-riviera'")).rows[0].p;await f.getByRole('button',{name:/Ajouter/}).click();await p.getByText('Enregistrement confirmé par le serveur.',{exact:true}).waitFor();const payload=(await sql.query("select payload from crm_workspace_state where workspace_id='oneaddress-riviera'")).rows[0].payload;const task=payload.tasks.find(t=>t.title==='Tâche métier finalisée');assert.equal(task.owner,'Vincent');assert.equal(task.linkedTo,'review-lead');delete payload.tasks;assert.deepEqual(payload,before);assert.ok(!paths.some(s=>s.includes('crm_workspace_state')));await p.screenshot({path:dir+'/finalisation-taches.png'});}finally{await c.close();}});
 await test('Existing house quarter-hours, planning calendar, quote lines and contact multiline forms available to restricted business profile',async()=>{const c=await context(),p=await c.newPage();const errors=[];p.on('pageerror',e=>errors.push(e.message));p.on('dialog',d=>d.accept());try{await login(p,'business');const nav=p.getByRole('navigation',{name:'Navigation principale',exact:true});for(const targetModule of ['Suivi maison','Planning','Devis','Contacts','Biens','Voitures','Bateaux','Factures prestataires','Devis prestataires','Documents']){await nav.getByRole('button',{name:targetModule,exact:true}).click();await p.waitForTimeout(500);assert.ok(!(await p.locator('body').innerText()).includes('Lecture indisponible'),targetModule);assert.deepEqual(errors,[],targetModule);if(targetModule==='Suivi maison'){await p.screenshot({path:dir+'/finalisation-maison.png'});}if(targetModule==='Planning'){assert.ok(await p.locator('[name=blocksAvailability]').count()>0);await p.screenshot({path:dir+'/finalisation-planning.png'});}if(targetModule==='Devis'){assert.ok(await p.locator('[name=priceVilla]').count()>0);await p.screenshot({path:dir+'/finalisation-devis.png'});}if(targetModule==='Contacts')assert.ok(await p.locator('textarea[name=postalAddress]').count()>0);}await p.setViewportSize({width:390,height:844});assert.ok(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));}finally{await c.close();}});
}finally{await browser.close();await sql.end();if(results.some(r=>r.status==='failed'))process.exitCode=1;}
