import assert from 'node:assert/strict';
import {createRequire} from 'node:module';
import {writeFileSync} from 'node:fs';
import {connect,sql,user,grant,fullGrants,dir} from './local.mjs';
const require=createRequire(import.meta.url),{chromium}=require('/tmp/izord-playwright-runtime-20260917/node_modules/playwright');
await connect();const u=await user('business');await grant(u,Object.fromEntries(Object.entries(fullGrants).filter(([k])=>k!=='izord')));const browser=await chromium.launch({headless:true,channel:'chrome'}),results=[];
async function page(){const c=await browser.newContext({viewport:{width:1440,height:1000}});await c.route('**/*',r=>new URL(r.request().url()).hostname==='127.0.0.1'||['data:','blob:'].includes(new URL(r.request().url()).protocol)?r.continue():r.abort());const p=await c.newPage();p.on('dialog',d=>d.accept());await p.goto('http://127.0.0.1:3160');await p.getByLabel('Email',{exact:true}).fill(u.email);await p.getByLabel('Mot de passe',{exact:true}).fill(u.password);await p.getByRole('button',{name:'Se connecter',exact:true}).click();await p.getByRole('heading',{name:'Centre de commandement',exact:true}).waitFor();return {c,p,nav:p.getByRole('navigation',{name:'Navigation principale',exact:true})};}
const payload=async()=>(await sql.query("select payload from crm_workspace_state where workspace_id='oneaddress-riviera'")).rows[0].payload;
async function test(name,fn){if(process.env.UNIFIED_TEST_FILTER&&!process.env.UNIFIED_TEST_FILTER.split('|').some(f=>name.includes(f)))return;try{await fn();results.push({name,status:'passed'});console.log('PASS '+name);}catch(e){results.push({name,status:'failed',error:e.message});console.error('FAIL '+name+': '+e.message);}finally{writeFileSync(dir+(process.env.UNIFIED_TEST_FILTER?'/finalisation-business-browser-reprise.json':'/finalisation-business-browser.json'),JSON.stringify(results,null,2));}}
try{
 await test('Final candidate house form saves named worker and quarter-hour record using real RPC',async()=>{const{c,p,nav}=await page();try{await nav.getByRole('button',{name:'Suivi maison',exact:true}).click();await p.getByRole('button',{name:'Heures',exact:true}).click();const f=p.locator('form').filter({has:p.getByRole('button',{name:'Ajouter les heures',exact:true})});await f.locator('label').filter({hasText:/^Maison/}).locator('select').selectOption('review-house');await f.locator('label').filter({hasText:/^Intervenant/}).locator('select').selectOption('review-worker');assert.equal(await f.locator('label').filter({hasText:/^Début/}).locator('select').locator('option').count(),96);await f.locator('label').filter({hasText:/^Début/}).locator('select').selectOption('13:15');await f.locator('label').filter({hasText:/^Fin/}).locator('select').selectOption('14:30');await f.getByRole('button',{name:'Ajouter les heures'}).click();await p.getByText('Enregistrement confirmé par le serveur.',{exact:true}).waitFor();assert.ok((await payload()).houseTimeEntries.some(r=>r.workerId==='review-worker'&&r.houseId==='review-house'&&r.startTime==='13:15'&&r.endTime==='14:30'));await p.screenshot({path:dir+'/finalisation-maison-saisie.png'});}finally{await c.close();}});
 await test('Final candidate calendar saves resource and availability through existing form',async()=>{const{c,p,nav}=await page();try{await nav.getByRole('button',{name:'Planning',exact:true}).click();const f=p.locator('.planning-entry-form');await f.locator('[name=title]').fill('Intervention finale fictive');await f.locator('[name=assetKey]').selectOption('Property:review-property');await f.locator('[name=startDate]').fill('2026-09-27');await f.locator('[name=endDate]').fill('2026-09-27');await f.locator('[name=blocksAvailability]').selectOption('true');await f.getByRole('button',{name:'Ajouter au planning'}).click();await p.getByText('Enregistrement confirmé par le serveur.',{exact:true}).waitFor();const row=(await payload()).planningEntries.find(r=>r.title==='Intervention finale fictive');assert.equal(row.assetId,'review-property');assert.equal(row.blocksAvailability,true);}finally{await c.close();}});
 await test('Final candidate existing quote editor saves structured line, terms and authorized customer',async()=>{const{c,p,nav}=await page();try{await nav.getByRole('button',{name:'Devis',exact:true}).click();const f=p.locator('form').filter({has:p.getByRole('button',{name:'Créer le devis',exact:true})});await f.locator('[name=clientName]').fill('Client fictif de démonstration');await f.locator('[name=title]').fill('Devis final fictif');await f.locator('[name=startDate]').fill('2026-09-27');await f.locator('[name=endDate]').fill('2026-09-29');await f.locator('[name=categories][value=Villa]').check();await f.locator('[name=priceVilla]').fill('125');await f.locator('[name=descriptionVilla]').fill('Prestation fictive');await f.locator('[name=paymentTerms]').fill('Conditions fictives');await f.getByRole('button',{name:'Créer le devis',exact:true}).click();await p.getByText('Enregistrement confirmé par le serveur.',{exact:true}).waitFor();const row=(await payload()).quotes.find(r=>r.title==='Devis final fictif');assert.equal(row.items[0].unitPrice,125);assert.equal(row.paymentTerms,'Conditions fictives');await p.screenshot({path:dir+'/finalisation-devis-saisie.png'});}finally{await c.close();}});
 await test('Final candidate Dashboard quick-entry reuses existing parser and atomic targeted writes; mobile no overflow',async()=>{const{c,p}=await page();try{p.removeAllListeners('dialog');let prompts=0;p.on('dialog',d=>d.type()==='prompt'?d.accept(++prompts===1?'5':'Nom : Camille Message Fictif\nRecherche villa\nBudget : 1200\nDates : 27/09/2026 - 29/09/2026'):d.accept());const requests=[];p.on('request',r=>{if(r.url().includes('/rest/v1/'))requests.push(r.url());});await p.getByRole('button',{name:'Créer depuis message',exact:true}).click();await p.getByRole('heading',{name:'Leads',exact:true}).first().waitFor();const w=await payload();assert.ok(w.contacts.some(r=>r.name==='Camille Message Fictif'));assert.ok(w.leads.some(r=>r.contactName==='Camille Message Fictif'&&r.value===1200));assert.ok(!requests.some(s=>s.includes('crm_workspace_state')));await p.setViewportSize({width:390,height:844});assert.ok(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));await p.screenshot({path:dir+'/finalisation-mobile-metier.png'});}finally{await c.close();}});
}finally{await browser.close();await sql.end();if(results.some(r=>r.status==='failed'))process.exitCode=1;}
