import assert from 'node:assert/strict';
import {createRequire} from 'node:module';
import {writeFileSync} from 'node:fs';
import {connect,sql,user,rpc,dir} from './local.mjs';
const require=createRequire(import.meta.url),{chromium}=require('/tmp/izord-playwright-runtime-20260917/node_modules/playwright');
await connect();const browser=await chromium.launch({headless:true,channel:'chrome'}),results=[];
async function login(name){const u=await user(name),c=await browser.newContext({viewport:{width:1440,height:1000}});await c.route('**/*',r=>new URL(r.request().url()).hostname==='127.0.0.1'?r.continue():r.abort());const p=await c.newPage();p.setDefaultTimeout(12000);p.on('dialog',d=>d.accept());await p.goto('http://127.0.0.1:3160');await p.getByLabel('Email',{exact:true}).fill(u.email);await p.getByLabel('Mot de passe',{exact:true}).fill(u.password);await p.getByRole('button',{name:'Se connecter',exact:true}).click();return{c,p,u,nav:p.getByRole('navigation',{name:'Navigation principale',exact:true})};}
async function test(name,fn){try{await fn();results.push({name,status:'passed'});console.log('PASS '+name);}catch(e){results.push({name,status:'failed',error:e.message});throw e;}finally{writeFileSync(dir+'/finalisation-last-browser.json',JSON.stringify(results,null,2));}}
try{
 await test('Final read-only planning retains working filters and disables all mutation controls',async()=>{const{c,p,nav}=await login('house');try{await nav.getByRole('button',{name:'Planning',exact:true}).click();await p.locator('.planning-filter-card form input[type=date]').first().waitFor();assert.equal(await p.locator('.planning-filter-card form input[type=date]').first().isDisabled(),false);assert.equal(await p.locator('.planning-entry-form input[name=title]').isDisabled(),true);await p.setViewportSize({width:390,height:844});assert.ok(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));await p.screenshot({path:dir+'/finalisation-planning-lecture-mobile.png'});}finally{await c.close();}});
 await test('Final Administration lists pending invitation and confirms real server revocation',async()=>{const admin=await user('admin'),email='ui-revoke-'+Date.now()+'@example.invalid';const r=await rpc('crm_invite_prepare',admin.token,{p_email:email,p_grants:{tasks:{level:'read'}}});assert.equal(r.status,200);const{c,p,nav}=await login('admin');try{await nav.getByRole('button',{name:'Administration',exact:true}).click();const row=p.locator('section.panel p').filter({hasText:email});await row.getByRole('button',{name:'Révoquer l’invitation'}).click();await p.getByText('Révocation confirmée par le serveur.').waitFor();assert.ok((await sql.query('select revoked_at from crm_access_invitations where id=$1',[r.data.id])).rows[0].revoked_at);}finally{await c.close();}});
 await test('Final restricted document UI creates replacement version with real Storage bytes',async()=>{const{c,p,nav}=await login('business');try{await nav.getByRole('button',{name:'Documents',exact:true}).click();await p.getByLabel('Rechercher',{exact:true}).fill('Version fictive.pdf');const item=p.locator('article').filter({has:p.getByRole('heading',{name:'Version fictive.pdf',exact:true})});await item.getByLabel('Remplacer (nouvelle version)').setInputFiles({name:'Version navigateur fictive.pdf',mimeType:'application/pdf',buffer:Buffer.from('%PDF-1.4\nVersion navigateur fictive\n')});await p.getByText('Nouvelle version confirmée. L’original est conservé.').waitFor();assert.ok((await sql.query("select superseded_by from crm_document_scopes where title='Version fictive.pdf'")).rows.some(r=>r.superseded_by));await p.getByLabel('Rechercher',{exact:true}).fill('fictive');await p.screenshot({path:dir+'/finalisation-documents-versions.png'});}finally{await c.close();}});
}finally{await browser.close();await sql.end();}
