import assert from 'node:assert/strict';
import {writeFileSync} from 'node:fs';
import {connect,sql,user,grant,rpc,dir} from './local.mjs';
await connect();const results=[],u=await user('review-finance');
const ok=r=>{assert.ok([200,204].includes(r.status),JSON.stringify(r));return r.data;},deny=r=>assert.ok(r.status>=400,JSON.stringify(r));
const payload=async()=>(await sql.query("select payload from crm_workspace_state where workspace_id='oneaddress-riviera'")).rows[0].payload;
const rev=async m=>ok(await rpc('crm_read_module',u.token,{p_module:m})).revision;
const grants={vendorQuotes:{level:'contribute',sensitive:{delete:true}},vendorInvoices:{level:'contribute',sensitive:{delete:true}}};
async function seed(){const w=await payload();w.vendorQuotes=w.vendorQuotes.filter(r=>r.id!=='review-empty-q');w.vendorInvoices=w.vendorInvoices.filter(r=>!r.id.startsWith('review-empty-i'));w.vendorQuotes.push({id:'review-empty-q',title:'Devis fictif',status:'Validé',linkedInvoiceId:'review-empty-i'});w.vendorInvoices.push({id:'review-empty-i',title:'Facture attendue · Fictif',amount:100,paidAmount:0,status:'En attente de facture',sourceQuoteId:'review-empty-q',sourceQuoteReference:'LOCAL',notes:'Créée automatiquement depuis le devis fictif'});await sql.query("update crm_workspace_state set payload=$1 where workspace_id='oneaddress-riviera'",[w]);}
async function check(name,fn){if(process.env.UNIFIED_TEST_FILTER&&!name.includes(process.env.UNIFIED_TEST_FILTER))return;try{await fn();results.push({name,status:'passed'});console.log('PASS '+name);}catch(e){results.push({name,status:'failed',error:e.message});throw e;}finally{writeFileSync(dir+(process.env.UNIFIED_TEST_FILTER?'/finalisation-finance-reprise.json':'/finalisation-finance.json'),JSON.stringify(results,null,2));}}
try{
 await grant(u,grants);await seed();
 await check('Quote rejection cancels only empty automatic invoice and requires its module write',async()=>{await grant(u,{vendorQuotes:grants.vendorQuotes});const before=await payload();deny(await rpc('crm_reject_vendor_quote',u.token,{p_quote:'review-empty-q',p_revision:await rev('vendorQuotes')}));assert.deepEqual(await payload(),before);await grant(u,grants);ok(await rpc('crm_reject_vendor_quote',u.token,{p_quote:'review-empty-q',p_revision:await rev('vendorQuotes')}));assert.equal((await payload()).vendorInvoices.find(r=>r.id==='review-empty-i').status,'Annulé');});
 await check('Explicit deletion choices and both delete permissions; empty automatic invoice only',async()=>{await seed();const args=async()=>({p_quote:'review-empty-q',p_choice:'delete-both',p_revision:await rev('vendorQuotes'),p_invoice_revision:await rev('vendorInvoices')});deny(await rpc('crm_delete_vendor_quote',u.token,{...await args(),p_choice:null}));await grant(u,{vendorQuotes:grants.vendorQuotes,vendorInvoices:{level:'contribute'}});deny(await rpc('crm_delete_vendor_quote',u.token,await args()));await grant(u,grants);const before=await payload();ok(await rpc('crm_delete_vendor_quote',u.token,await args()));const after=await payload();assert.ok(!after.vendorInvoices.some(r=>r.id==='review-empty-i'));assert.ok(!after.vendorQuotes.some(r=>r.id==='review-empty-q'));for(const k of Object.keys(before))if(!['vendorQuotes','vendorInvoices'].includes(k))assert.deepEqual(after[k],before[k]);});
 await check('Populated legacy payment metadata blocks delete-both; keep-invoice preserves it byte for byte',async()=>{await seed();await sql.query("update crm_workspace_state set payload=jsonb_set(payload,'{vendorInvoices}',(select jsonb_agg(case when r->>'id'='review-empty-i' then r||'{\"legacyPayment\":{\"protected\":true}}'::jsonb else r end) from jsonb_array_elements(payload->'vendorInvoices') r)) where workspace_id='oneaddress-riviera'");const before=await payload();deny(await rpc('crm_delete_vendor_quote',u.token,{p_quote:'review-empty-q',p_choice:'delete-both',p_revision:await rev('vendorQuotes'),p_invoice_revision:await rev('vendorInvoices')}));assert.deepEqual(await payload(),before);ok(await rpc('crm_delete_vendor_quote',u.token,{p_quote:'review-empty-q',p_choice:'keep-invoice',p_revision:await rev('vendorQuotes')}));assert.deepEqual((await payload()).vendorInvoices,before.vendorInvoices);});
 await check('Empty orphan cleanup rejects used invoice and keeps recurring sibling',async()=>{await seed();await sql.query("update crm_workspace_state set payload=jsonb_set(payload,'{vendorInvoices}',(select jsonb_agg(case when r->>'id'='review-empty-i' then r||'{\"legacyPayment\":{\"protected\":true}}'::jsonb else r end) from jsonb_array_elements(payload->'vendorInvoices') r)) where workspace_id='oneaddress-riviera'");const args=async()=>({p_invoice:'review-empty-i',p_revision:await rev('vendorInvoices')});deny(await rpc('crm_delete_orphan_invoice',u.token,await args()));await seed();const w=await payload();w.vendorQuotes=w.vendorQuotes.filter(r=>r.id!=='review-empty-q');w.vendorInvoices.push({...w.vendorInvoices.find(r=>r.id==='review-empty-i'),id:'review-recurring-sibling',sourceQuoteId:'another-quote'});await sql.query("update crm_workspace_state set payload=$1 where workspace_id='oneaddress-riviera'",[w]);ok(await rpc('crm_delete_orphan_invoice',u.token,await args()));assert.deepEqual((await payload()).vendorInvoices.find(r=>r.id==='review-recurring-sibling'),w.vendorInvoices.find(r=>r.id==='review-recurring-sibling'));});
}finally{await sql.end();}
