import assert from 'node:assert/strict';
import {readFileSync,writeFileSync} from 'node:fs';
import {randomUUID} from 'node:crypto';
import {connect,sql,request,rpc,user,grant,modules,fullGrants,dir,status} from './local.mjs';
await connect();
const users=JSON.parse(readFileSync(dir+'/users.private.json','utf8'));
// Refresh JWTs rather than retain a stale local login.
for(const name of Object.keys(users))users[name]=await user(name);
writeFileSync(dir+'/users.private.json',JSON.stringify(users),{mode:0o600});
const results=[];
async function test(name,fn){if(process.env.UNIFIED_TEST_FILTER&&!name.includes(process.env.UNIFIED_TEST_FILTER))return;try{await fn();results.push({name,status:'passed'});console.log('PASS '+name);}catch(e){results.push({name,status:'failed',error:e.message});console.error('FAIL '+name+': '+e.message);throw e;}finally{writeFileSync(dir+'/security.json',JSON.stringify(results,null,2));}}
const ok=(r)=>{assert.ok(r.status===200||r.status===204,JSON.stringify(r));return r.data;};
const denied=r=>assert.ok(r.status>=400,JSON.stringify(r));
const getPayload=async()=>(await sql.query("select payload from public.crm_workspace_state where workspace_id='oneaddress-riviera'")).rows[0].payload;
try{
 await test('Full administrator preserves complete payload and administration',async()=>{const a=ok(await rpc('crm_access_snapshot',users.admin.token));assert.equal(a.fullAccess,true);assert.equal(a.generalAdmin,true);assert.equal(Object.keys(a.modules).length,15);assert.ok(ok(await request('/rest/v1/crm_workspace_state?select=payload',users.admin.token))[0].payload.contacts.length);ok(await rpc('crm_admin_users',users.admin.token));});
 await test('Direct legacy tables, backups, raw state and Drive registry denied to restricted user',async()=>{for(const table of ['crm_workspace_state','crm_backups','crm_contacts','crm_leads','crm_tasks','crm_properties','crm_vehicles','crm_boats','crm_quotes','crm_drive_folder_registry']){const r=await request('/rest/v1/'+table+'?select=*',users.tasks.token);assert.ok(r.status>=400||r.data.length===0,table);}const before=await getPayload();const write=await request('/rest/v1/crm_workspace_state?workspace_id=eq.oneaddress-riviera',users.tasks.token,{payload:{contacts:[]}},'PATCH');assert.ok(write.status>=400||write.status===204);assert.deepEqual(await getPayload(),before);denied(await rpc('crm_drive_folder_claim',users.tasks.token,{p_workspace_id:'oneaddress-riviera',p_logical_key:'vendor:unified-contacts',p_parent_id:'fake',p_lease_token:randomUUID()}));});
 await test('Invoice read projection excludes other collections, contacts, private notes and RIB',async()=>{const r=ok(await rpc('crm_read_module',users.invoices.token,{p_module:'vendorInvoices'}));assert.deepEqual(Object.keys(r.collections),['vendorInvoices']);const text=JSON.stringify(r);for(const marker of ['PRIVATE_','FICTIONAL-NOT','supplierBankAccounts','paymentBankAccountId'])assert.ok(!text.includes(marker),marker);denied(await rpc('crm_export_module',users.invoices.token,{p_module:'vendorInvoices'}));});
 const catalog=JSON.parse(readFileSync('lib/access/collections.json','utf8'));
 for(const moduleId of modules.filter(m=>m!=='izord'))await test('Matrix none/read/contribute: '+moduleId,async()=>{
  const target=users.matrix;await grant(target,{});denied(await rpc('crm_read_module',target.token,{p_module:moduleId}));
  await grant(target,{[moduleId]:{level:'read'}});const view=ok(await rpc('crm_read_module',target.token,{p_module:moduleId}));
  const c=catalog.find(c=>c.module===moduleId);const collection=c?.collection??'quotes';
  denied(await rpc('crm_mutate_record',target.token,{p_module:moduleId,p_collection:collection,p_id:'unified-'+collection,p_patch:{},p_revision:view.revision}));
  await grant(target,{[moduleId]:{level:'contribute'}});
  if(!c){if(moduleId==='bookings')denied(await rpc('crm_mutate_record',target.token,{p_module:moduleId,p_collection:'quotes',p_id:'unified-quotes',p_patch:{bookingStatus:'Confirmée'},p_revision:view.revision}));return;}
  const before=await getPayload();const field=Object.keys(c.fields).find(f=>!f.toLowerCase().includes('date')&&!f.toLowerCase().includes('time')&&!['houseId','workerId'].includes(f));const value=c.fields[field].enum?.[0]??(c.fields[field].type==='number'?105:'Fictif '+field);
  ok(await rpc('crm_mutate_record',target.token,{p_module:moduleId,p_collection:collection,p_id:'unified-'+collection,p_patch:{[field]:value},p_revision:view.revision}));
  const after=await getPayload();for(const key of Object.keys(before))if(key!==collection)assert.deepEqual(after[key],before[key],key);
  const row=after[collection].find(r=>r.id==='unified-'+collection);assert.equal(row.updatedBy,target.id);assert.equal(row[field],value);
  const current=ok(await rpc('crm_read_module',target.token,{p_module:moduleId}));for(const patch of [{supplierBankAccounts:[]},{permissions:{admin:true}},{updatedBy:users.admin.id},{unknown:'x'}])denied(await rpc('crm_mutate_record',target.token,{p_module:moduleId,p_collection:collection,p_id:row.id,p_patch:patch,p_revision:current.revision}));
 });
 await test('Same-moduleId concurrent writes conflict; cross-moduleId writes preserve each other',async()=>{await grant(users.matrix,{tasks:{level:'contribute'},properties:{level:'contribute'}});const t=ok(await rpc('crm_read_module',users.matrix.token,{p_module:'tasks'}));const mutation=title=>rpc('crm_mutate_record',users.matrix.token,{p_module:'tasks',p_collection:'tasks',p_id:'unified-tasks',p_patch:{title},p_revision:t.revision});const both=await Promise.all([mutation('Concurrent A'),mutation('Concurrent B')]);assert.equal(both.filter(r=>r.status===200).length,1);assert.equal(both.filter(r=>r.data.code==='40001').length,1);const task=ok(await rpc('crm_read_module',users.matrix.token,{p_module:'tasks'}));const prop=ok(await rpc('crm_read_module',users.matrix.token,{p_module:'properties'}));const results=await Promise.all([rpc('crm_mutate_record',users.matrix.token,{p_module:'tasks',p_collection:'tasks',p_id:'unified-tasks',p_patch:{title:'Préparer la visite fictive'},p_revision:task.revision}),rpc('crm_mutate_record',users.matrix.token,{p_module:'properties',p_collection:'properties',p_id:'unified-properties',p_patch:{name:'Villa fictive'},p_revision:prop.revision})]);results.forEach(ok);});
 await test('No rights and IZORD administrator cannot self-escalate through REST/RPC or user metadata',async()=>{for(const name of ['none','izord-admin']){denied(await rpc('crm_admin_users',users[name].token));denied(await request('/rest/v1/crm_access_profiles',users[name].token,{user_id:users[name].id,general_admin:true}));denied(await rpc('crm_admin_save',users[name].token,{p_user:users[name].id,p_revision:1,p_active:true,p_general_admin:true,p_grants:fullGrants,p_izord_role:'admin',p_assignments:[]}));}const u=users['izord-admin'];ok(await request('/auth/v1/user',u.token,{data:{general_admin:true,role:'admin'}},'PUT'));assert.equal(ok(await rpc('crm_access_snapshot',u.token)).generalAdmin,false);});
 await test('Permission revision conflict, revocation and last general administrator protection',async()=>{const admin=users.admin;await grant(users['second-admin'],fullGrants,true,'admin');await grant(users.revoked,{contacts:{level:'read'}});const snapshot=ok(await rpc('crm_admin_users',admin.token));const target=snapshot.users.find(u=>u.id===users.revoked.id);const args={p_user:target.id,p_revision:target.revision,p_active:false,p_general_admin:false,p_grants:target.modules,p_izord_role:null,p_assignments:[]};ok(await rpc('crm_admin_save',admin.token,args));denied(await rpc('crm_read_module',users.revoked.token,{p_module:'contacts'}));assert.equal((await rpc('crm_admin_save',admin.token,args)).data.code,'40001');const other=snapshot.users.find(u=>u.id===users['second-admin'].id);ok(await rpc('crm_admin_save',admin.token,{p_user:other.id,p_revision:other.revision,p_active:false,p_general_admin:false,p_grants:other.modules,p_izord_role:'admin',p_assignments:[]}));const own=ok(await rpc('crm_admin_users',admin.token)).users.find(u=>u.id===admin.id);const deniedLast=await rpc('crm_admin_save',admin.token,{p_user:own.id,p_revision:own.revision,p_active:false,p_general_admin:false,p_grants:own.modules,p_izord_role:'admin',p_assignments:[]});denied(deniedLast);assert.match(deniedLast.data.message,/last_general_admin/);});
 await test('IZORD matrix supplements role and assignment; no OAR payload',async()=>{const u=users.izord;await grant(u,{izord:{level:'contribute',sensitive:{export:true}}},false,'contributor');const project=ok(await rpc('izord_create_project',u.token,{p_title:'Projet unifié fictif'}));await grant(u,{izord:{level:'read',sensitive:{export:true}}},false,'contributor');denied(await rpc('izord_create_project',u.token,{p_title:'Interdit lecture'}));assert.equal(ok(await request('/rest/v1/izord_projects?id=eq.'+project,u.token)).length,1);await grant(u,{izord:{level:'contribute'}},false,'reader');denied(await rpc('izord_create_project',u.token,{p_title:'Interdit rôle'}));await grant(u,{izord:{level:'contribute',sensitive:{export:true}}},false,'contributor');assert.equal(ok(await request('/rest/v1/crm_workspace_state?select=payload',u.token)).length,0);});
 await test('Storage unclassified file denied; classified owner+document+export required; bank scope enforced',async()=>{const name='unified-'+randomUUID()+'.txt';const upload=await fetch(status.API_URL+'/storage/v1/object/crm-documents/'+name,{method:'POST',headers:{apikey:status.ANON_KEY,Authorization:'Bearer '+users.admin.token,'Content-Type':'text/plain'},body:'FICTIONAL DOCUMENT'});assert.equal(upload.status,200);const download=token=>fetch(status.API_URL+'/storage/v1/object/authenticated/crm-documents/'+name,{headers:{apikey:status.ANON_KEY,Authorization:'Bearer '+token}});assert.ok((await download(users.tasks.token)).status>=400);ok(await rpc('crm_classify_document',users.admin.token,{p_provider:'storage',p_resource:name,p_collection:'tasks',p_record:'unified-tasks',p_title:'Document fictif',p_bank:false}));await grant(users.matrix,{documents:{level:'read',sensitive:{export:true}}});assert.ok((await download(users.matrix.token)).status>=400);await grant(users.matrix,{documents:{level:'read',sensitive:{export:true}},tasks:{level:'read',sensitive:{export:true}}});const r=await download(users.matrix.token);assert.equal(r.status,200);assert.equal(await r.text(),'FICTIONAL DOCUMENT');await grant(users.matrix,{documents:{level:'read',sensitive:{export:true}},tasks:{level:'read'}});assert.ok((await download(users.matrix.token)).status>=400);ok(await rpc('crm_classify_document',users.admin.token,{p_provider:'storage',p_resource:name,p_collection:'contacts',p_record:'unified-contacts',p_title:'RIB fictif',p_bank:true}));await grant(users.matrix,{documents:{level:'read',sensitive:{export:true}},contacts:{level:'read',sensitive:{export:true}}});assert.ok((await download(users.matrix.token)).status>=400);});
 await test('Invitation verified recipient, no pre-accept grants, replay and incorrect recipient denied',async()=>{const recipient=await user('invite-'+Date.now());const invitation=ok(await rpc('crm_invite_prepare',users.admin.token,{p_email:recipient.email,p_grants:{tasks:{level:'read'}},p_izord_role:null}));assert.equal(Object.keys(ok(await rpc('crm_access_snapshot',recipient.token)).modules).length,0);denied(await rpc('crm_invite_accept',users.none.token,{p_token:invitation.token}));ok(await rpc('crm_invite_accept',recipient.token,{p_token:invitation.token}));assert.equal(ok(await rpc('crm_access_snapshot',recipient.token)).modules.tasks.level,'read');denied(await rpc('crm_invite_accept',recipient.token,{p_token:invitation.token}));});
}finally{await sql.end();}
