/** Targeted disposable local Auth/RPC/Storage suite. No external transport, paid
 * request or production database. Retained fictional files demonstrate recovery. */
import assert from 'node:assert/strict';
import {readFileSync,writeFileSync} from 'node:fs';
import {randomBytes,randomUUID,createHash} from 'node:crypto';
import pg from 'pg';
import {assertLocalTarget} from '../izord/local-target.mjs';
const status=JSON.parse(readFileSync(process.env.LOCAL_STATUS_FILE??'/private/tmp/oar-targeted-docs-local-status.json','utf8'));
assertLocalTarget({api:status.API_URL,database:status.DB_URL,app:'http://127.0.0.1:3159',mail:'http://127.0.0.1:55434',acknowledgement:process.env.IZORD_TEST_ACK});
const sql=new pg.Client({connectionString:status.DB_URL});
const api=new URL(status.API_URL).origin,app='http://127.0.0.1:3190',run=randomUUID();
const results=[],users={};
async function request(path,user,body,method){const r=await fetch(api+path,{method:method??(body===undefined?'GET':'POST'),headers:{apikey:status.ANON_KEY,...(user?.token?{Authorization:'Bearer '+user.token}:{}),...(body===undefined?{}:{'Content-Type':'application/json'})},body:body===undefined?undefined:JSON.stringify(body)});const text=await r.text();let data;try{data=JSON.parse(text);}catch{data=text;}return {status:r.status,data};}
const rpc=(name,user,args={})=>request('/rest/v1/rpc/'+name,user,args);
const ok=r=>{assert.ok([200,204].includes(r.status),JSON.stringify(r));return r.data;};
const denied=r=>assert.ok(r.status>=400,JSON.stringify(r));
async function test(name,fn){await fn();results.push({name,passed:true});writeFileSync('/private/tmp/oar-contact-evolution-server-progress.json',JSON.stringify({results},null,2),{mode:0o600});console.log('PASS '+name);}
const payload=async()=> (await sql.query("select payload from public.crm_workspace_state where workspace_id='oneaddress-riviera'")).rows[0].payload;
const row=(p,collection,id)=>p[collection].find(r=>r.id===id);
const list=user=>rpc('crm_contact_documents',user,{p_contact:'contact-evolution-demo'}).then(ok);
const fullModules=['dashboard','contacts','leads','tasks','quotes','bookings','vendorQuotes','vendorInvoices','houseTracking','documents','planning','properties','vehicles','boats','izord','monthlyCharges','publisher'];
const ownerGrants=Object.fromEntries(fullModules.map(module=>[module,{level:'contribute',sensitive:module==='monthlyCharges'?{export:true}:module==='publisher'?{export:true,generate:true,mark_published:true}:{delete:true,export:true,...(module==='contacts'?{bank_read:true,bank_write:true}:{}),...(module==='vendorInvoices'?{payment:true}:{})}}]));
const depositorGrants={contacts:{level:'contribute',sensitive:{export:true,delete:true}},documents:{level:'contribute',sensitive:{export:true,delete:true}},houseTracking:{level:'contribute',sensitive:{export:true,delete:true}},monthlyCharges:{level:'read',sensitive:{export:true}}};
const otherGrants={contacts:{level:'contribute',sensitive:{export:true,delete:true}},documents:{level:'contribute',sensitive:{export:true,delete:true}},dashboard:{level:'read'}};
async function grant(user,grants,owner=false){await sql.query('insert into public.crm_access_profiles(user_id,general_admin) values($1,$2) on conflict(user_id) do update set active=true,general_admin=$2',[user.id,owner]);await sql.query('delete from public.crm_module_grants where user_id=$1',[user.id]);for(const [module,g]of Object.entries(grants))await sql.query('insert into public.crm_module_grants(user_id,module,level,sensitive) values($1,$2,$3,$4)',[user.id,module,g.level,g.sensitive??{}]);await sql.query("insert into public.app_memberships(user_id,workspace_id,role) values($1,'oar','member') on conflict(user_id,workspace_id) do update set status='active'",[user.id]);if(owner)await sql.query("insert into public.app_memberships(user_id,workspace_id,role) values($1,'izord','admin') on conflict(user_id,workspace_id) do update set status='active'",[user.id]);}
async function createUser(name,grants,owner=false){const email=`contact-evolution-${name}-${run}@example.invalid`,password=randomBytes(24).toString('hex');const created=ok(await request('/auth/v1/admin/users',{token:status.SERVICE_ROLE_KEY},{email,password,email_confirm:true}));const login=ok(await request('/auth/v1/token?grant_type=password',null,{email,password}));const user={id:created.id,email,password,token:login.access_token};await grant(user,grants,owner);return user;}
const content=Buffer.from('%PDF-1.4\nFICTIONAL CONTACT IDENTITY. NO REAL PERSON.\n');
async function reserve(user,args={}){return ok(await rpc('crm_contact_document_begin',user,{p_operation:randomUUID(),p_contact:'contact-evolution-demo',p_title:'Pièce fictive',p_type:'Carte d’identité',p_filename:'identite-fictive.pdf',p_mime:'application/pdf',p_size:content.length,...args}));}
async function upload(user,d,bytes=content){const r=await fetch(api+'/storage/v1/object/crm-documents/'+d.resource_id,{method:'POST',headers:{apikey:status.ANON_KEY,Authorization:'Bearer '+user.token,'Content-Type':'application/pdf','x-upsert':'false'},body:bytes});assert.equal(r.status,200,await r.text());return ok(await rpc('crm_contact_document_complete',user,{p_operation:d.operation_id}));}
const contact={id:'contact-evolution-supplier',name:'Alex Équipe Fictive',kind:'Prestataire',supplierCategory:'Entretien fictif',supplierStatus:'Actif',relationshipStatus:'Prestataire',notes:'HISTORIQUE FICTIF À CONSERVER',supplierBankAccounts:[{id:'bank-contact-evolution',accountHolder:'Alex Équipe Fictive',iban:'FICTIONAL-LOCAL-NOT-AN-IBAN',bic:'FICTIONAL',status:'Vérifié',isPrimary:true,driveFileId:'contact-evolution-fictional-bank'}],createdAt:'2026-01-01'};
const demo={id:'contact-evolution-demo',name:'Camille Documents Fictifs',kind:'Client',email:'demo-contact@example.invalid',createdAt:'2026-01-01'};
const sources={houseTrackingHouses:[{id:'house-contact-evolution',name:'Maison fictive Équipe',address:'Fictive'}],houseTrackingWorkers:[{id:'worker-contact-evolution',contactId:contact.id,contactName:contact.name,role:'Entretien fictif',hourlyRate:27.5,status:'Actif',documentStoragePath:'',documentFileName:'',createdAt:'2026-01-01'}],houseTimeEntries:[{id:'hours-contact-evolution',houseId:'house-contact-evolution',workerId:'worker-contact-evolution',workerName:contact.name,houseName:'Maison fictive Équipe',date:'2026-09-09',startTime:'08:07',endTime:'12:42',breakMinutes:15,hourlyRate:19.25}],housePayments:[{id:'payment-contact-evolution',houseId:'house-contact-evolution',workerId:'worker-contact-evolution',workerName:contact.name,date:'2026-09-09',amount:20,method:'Virement'}],vendorInvoices:[{id:'invoice-contact-evolution',title:'Facture historique fictive',contactId:contact.id,contactName:contact.name,invoiceReference:'FICTIONAL-HISTORY-001',invoiceDate:'2026-09-01',amount:135,paidAmount:35,status:'Partiellement payé',paymentBankAccountId:'bank-contact-evolution',createdAt:'2026-01-01'}],tasks:[{id:'task-contact-evolution',title:'Tâche historique fictive',contactId:contact.id,status:'À faire'}]};
await sql.connect();
try{
 assert.equal((await sql.query("select count(*)::int n from auth.users where email not like '%@example.invalid'")).rows[0].n,0);
 const beforeShares=(await sql.query("select * from public.crm_document_shares where resource_id not like 'contact-private/%' order by provider,resource_id,user_id")).rows;
 const original=await payload(),originalHash=createHash('sha256').update(JSON.stringify(original)).digest('hex');
 users.owner=await createUser('owner',ownerGrants,true);users.depositor=await createUser('depositor',depositorGrants);users.other=await createUser('other',otherGrants);
 const source=await payload();source.contacts??=[];for(const c of [contact,demo])if(!source.contacts.some(r=>r.id===c.id))source.contacts.push(c);for(const[c,rows]of Object.entries(sources)){source[c]??=[];for(const r of rows)if(!source[c].some(x=>x.id===r.id))source[c].push(r);}
 await sql.query("update public.crm_workspace_state set payload=$1 where workspace_id='oneaddress-riviera'",[source]);
 let monthly=ok(await rpc('crm_read_monthly_charges',users.owner));
 ok(await rpc('crm_patch_monthly_charges',users.owner,{p_revision:monthly.revision,p_request_id:randomUUID(),p_patch:{personRules:[{source:'invoice',personId:contact.id,included:true},{source:'hours',personId:'worker-contact-evolution',included:true}]}}));
 const fixture={run,api,app,users,contacts:{history:contact,demo},documents:[],statusFile:process.env.LOCAL_STATUS_FILE??'/private/tmp/oar-targeted-docs-local-status.json'};
 writeFileSync('/private/tmp/oar-contact-evolution-fixture.private.json',JSON.stringify(fixture,null,2),{mode:0o600});
 await test('member create/edit/reload owner and contributor, invalid enum and unknown patches denied',async()=>{
  for(const user of [users.owner,users.depositor]){const id='member-rpc-'+(user===users.owner?'owner':'contributor');let state=ok(await rpc('crm_read_module',user,{p_module:'contacts'}));ok(await rpc('crm_mutate_record',user,{p_module:'contacts',p_collection:'contacts',p_id:id,p_patch:{name:'Membre RPC fictif '+id,kind:'Membre de l’organisation',organizationFunction:'Coordination'},p_revision:state.revision}));state=ok(await rpc('crm_read_module',user,{p_module:'contacts'}));assert.equal(row(state.collections,'contacts',id).organizationFunction,'Coordination');ok(await rpc('crm_mutate_record',user,{p_module:'contacts',p_collection:'contacts',p_id:id,p_patch:{organizationFunction:'Accueil'},p_revision:state.revision}));state=ok(await rpc('crm_read_module',user,{p_module:'contacts'}));assert.equal(row(state.collections,'contacts',id).kind,'Membre de l’organisation');assert.equal(row(state.collections,'contacts',id).organizationFunction,'Accueil');assert.equal(ok(await rpc('crm_reference_options',user,{p_module:'contacts'})).contacts.find(r=>r.id===id).organizationFunction,'Accueil');denied(await rpc('crm_mutate_record',user,{p_module:'contacts',p_collection:'contacts',p_id:id,p_patch:{kind:'AuthAdmin'},p_revision:state.revision}));}
 });
 await test('supplier to member preserves exact identity, residual supplier/bank fields, histories, monthly sources and rules',async()=>{
  const before=await payload(),charges=ok(await rpc('crm_read_monthly_charges',users.owner));const memberships=(await sql.query('select * from public.app_memberships order by user_id,workspace_id')).rows;
  const state=ok(await rpc('crm_read_module',users.owner,{p_module:'contacts'}));ok(await rpc('crm_mutate_record',users.owner,{p_module:'contacts',p_collection:'contacts',p_id:contact.id,p_patch:{kind:'Membre de l’organisation',organizationFunction:'Responsable fictif'},p_revision:state.revision}));
  const after=await payload(),actual=row(after,'contacts',contact.id);for(const[k,value]of Object.entries(row(before,'contacts',contact.id)))if(!['kind','updatedAt','updatedBy'].includes(k))assert.deepEqual(actual[k],value,k);
  for(const collection of Object.keys(sources))assert.deepEqual(after[collection],before[collection],collection);assert.deepEqual(ok(await rpc('crm_read_monthly_charges',users.owner)),charges);assert.deepEqual((await sql.query('select * from public.app_memberships order by user_id,workspace_id')).rows,memberships);
  const current=ok(await rpc('crm_read_module',users.owner,{p_module:'contacts'}));ok(await rpc('crm_mutate_record',users.owner,{p_module:'contacts',p_collection:'contacts',p_id:contact.id,p_patch:{kind:'Prestataire'},p_revision:current.revision}));
 });
 let first,second;
 await test('multiple and later contact uploads, duplicate filename unique bytes, author/date server, reserve and confirmation idempotent',async()=>{
  const before=await payload(),visible=await list(users.depositor);first=await reserve(users.depositor,{p_revision:visible.revision,p_expiry:'2030-10-06'});second=await reserve(users.depositor,{p_revision:visible.revision,p_title:'Verso fictif'});assert.notEqual(first.resource_id,second.resource_id);assert.equal((await list(users.depositor)).documents.length,0);assert.equal(first.created_by,users.depositor.id);assert.ok(new Date(first.created_at).valueOf()>Date.now()-60000);first=await upload(users.depositor,first);second=await upload(users.depositor,second);const third=await upload(users.depositor,await reserve(users.depositor,{p_title:'Permis ultérieur',p_type:'Permis de conduire'}));fixture.documents.push(first,second,third);assert.equal((await list(users.depositor)).documents.length,3);assert.deepEqual(await payload(),before,'Document addition does not touch any contact/payload');assert.deepEqual(ok(await rpc('crm_contact_document_complete',users.depositor,{p_operation:first.operation_id})),first);const retry=await reserve(users.depositor,{p_operation:first.operation_id,p_expiry:'2030-10-06'});assert.equal(retry.resource_id,first.resource_id);assert.equal(retry.lifecycle,'active');denied(await rpc('crm_contact_document_begin',users.depositor,{p_operation:first.operation_id,p_contact:demo.id,p_title:'Other',p_type:'Autre',p_filename:'other.pdf',p_mime:'application/pdf',p_size:content.length}));
 });
 await test('failed upload, conflict and cancellation preserve confirmed successes and never duplicate retries',async()=>{
  const missing=await reserve(users.depositor);denied(await rpc('crm_contact_document_complete',users.depositor,{p_operation:missing.operation_id}));const retried=await reserve(users.depositor,{p_operation:missing.operation_id});assert.equal(retried.resource_id,missing.resource_id);ok(await rpc('crm_contact_document_cancel',users.depositor,{p_operation:missing.operation_id}));denied(await rpc('crm_contact_document_complete',users.depositor,{p_operation:missing.operation_id}));denied(await rpc('crm_contact_document_begin',users.depositor,{p_operation:randomUUID(),p_contact:demo.id,p_title:'Conflit',p_type:'Autre',p_filename:'x.pdf',p_mime:'application/pdf',p_size:content.length,p_revision:'stale'}));assert.equal((await list(users.depositor)).documents.length,3);
  for(const args of [{p_size:25000001},{p_size:0},{p_mime:'image/svg+xml'},{p_type:'RIB'},{p_expiry:'2026-02-31'}])denied(await rpc('crm_contact_document_begin',users.depositor,{p_operation:randomUUID(),p_contact:demo.id,p_title:'Invalid',p_type:'Autre',p_filename:'x.pdf',p_mime:'application/pdf',p_size:content.length,...args}));denied(await rpc('crm_contact_document_begin',users.depositor,{p_operation:randomUUID(),p_contact:'unconfirmed-contact',p_title:'Invalid',p_type:'Autre',p_filename:'x.pdf',p_mime:'application/pdf',p_size:content.length}));
 });
 await test('private metadata/list/count/export/Storage/direct-RPC and legacy bypasses deny unshared collaborator, including contributor',async()=>{
  assert.equal((await list(users.other)).documents.length,0);const emptyRevision=(await list(users.other)).revision;const rows=ok(await rpc('crm_read_module',users.other,{p_module:'documents'})).collections.documents;assert.ok(!JSON.stringify(rows).includes('contact-private'));assert.equal(ok(await rpc('crm_read_module',users.other,{p_module:'dashboard'})).collections.documents,0);assert.ok(!JSON.stringify(ok(await rpc('crm_export_module',users.other,{p_module:'documents'}))).includes(first.resource_id));denied(await rpc('crm_contact_document_file',users.other,{p_resource:first.resource_id}));denied(await rpc('crm_contact_document_withdraw',users.other,{p_resource:first.resource_id,p_revision:first.revision}));denied(await rpc('crm_contact_document_replace',users.other,{p_previous:first.resource_id,p_next:second.resource_id,p_revision:first.revision}));denied(await rpc('crm_share_contact_document',users.depositor,{p_resource:first.resource_id,p_user:users.other.id}));
  for(const user of [users.owner,users.depositor,users.other]){const headers={apikey:status.ANON_KEY,Authorization:'Bearer '+user.token,'Content-Type':'application/json'};for(const path of ['/storage/v1/object/authenticated/crm-documents/'+first.resource_id,'/storage/v1/object/sign/crm-documents/'+first.resource_id]){const r=await fetch(api+path,{method:path.includes('/sign/')?'POST':'GET',headers,...(path.includes('/sign/')?{body:JSON.stringify({expiresIn:60})}:{})});assert.ok(r.status>=400,await r.text());}const overwrite=await fetch(api+'/storage/v1/object/crm-documents/'+first.resource_id,{method:'PUT',headers:{...headers,'Content-Type':'application/pdf'},body:content});assert.ok(overwrite.status>=400,await overwrite.text());await fetch(api+'/storage/v1/object/crm-documents',{method:'DELETE',headers,body:JSON.stringify({prefixes:[first.resource_id]})});assert.equal((await sql.query("select count(*)::int n from storage.objects where bucket_id='crm-documents' and name=$1",[first.resource_id])).rows[0].n,1);}
  for(const name of ['crm_classify_document','crm_update_document','crm_forget_document','crm_replace_document']){const args=name==='crm_classify_document'?{p_provider:'storage',p_resource:first.resource_id,p_collection:'tasks',p_record:'task-contact-evolution',p_title:'Declassified',p_bank:false}:name==='crm_update_document'?{p_resource:first.resource_id,p_title:'Tampered',p_folder:'Tampered'}:name==='crm_forget_document'?{p_resource:first.resource_id}:{p_previous:first.resource_id,p_next:second.resource_id};denied(await rpc(name,users.owner,args));}
  denied(await rpc('crm_new_document',users.owner,{p_collection:'contacts',p_record:demo.id,p_title:'Legacy personal bypass',p_bank:false}));assert.equal(ok(await rpc('crm_authorize_drive',users.owner,{p_resource:first.resource_id})),false);assert.equal((await list(users.other)).revision,emptyRevision);
 });
 await test('explicit sharing requires both modules; read/write/delete/export remain distinct; same token revocation and session loss immediately deny',async()=>{
  ok(await rpc('crm_share_contact_document',users.owner,{p_resource:first.resource_id,p_user:users.other.id}));assert.equal((await list(users.other)).documents.length,1);assert.equal((await list(users.other)).documents[0].readonly,true);ok(await rpc('crm_contact_document_file',users.other,{p_resource:first.resource_id}));denied(await rpc('crm_contact_document_withdraw',users.other,{p_resource:first.resource_id,p_revision:first.revision}));
  await grant(users.other,{...otherGrants,contacts:{level:'read'},documents:{level:'read',sensitive:{export:true}}});ok(await rpc('crm_contact_document_file',users.other,{p_resource:first.resource_id}));denied(await rpc('crm_contact_document_file',users.other,{p_resource:first.resource_id,p_download:true}));assert.ok(!JSON.stringify(ok(await rpc('crm_export_module',users.other,{p_module:'documents'}))).includes(first.resource_id));await grant(users.other,{...otherGrants,documents:{level:'read'}});denied(await rpc('crm_export_module',users.other,{p_module:'documents'}));await grant(users.other,otherGrants);
  ok(await rpc('crm_revoke_document_share',users.owner,{p_provider:'storage',p_resource:first.resource_id,p_user:users.other.id}));assert.equal((await list(users.other)).documents.length,0);denied(await rpc('crm_contact_document_file',users.other,{p_resource:first.resource_id}));
  await grant(users.depositor,{...depositorGrants,contacts:{level:'read',sensitive:{export:true}}});denied(await rpc('crm_contact_document_withdraw',users.depositor,{p_resource:second.resource_id,p_revision:second.revision}));denied(await rpc('crm_contact_document_replace',users.depositor,{p_previous:first.resource_id,p_next:second.resource_id,p_revision:first.revision}));await grant(users.depositor,depositorGrants);
  for(const change of ["update public.crm_access_profiles set active=false where user_id=$1","update public.app_memberships set status='revoked' where user_id=$1 and workspace_id='oar'","update auth.users set banned_until=now()+interval '1 hour' where id=$1"]){await sql.query(change,[users.depositor.id]);denied(await list(users.depositor).then(data=>({status:200,data})).catch(e=>({status:403,data:e.message})));denied(await rpc('crm_contact_document_file',users.depositor,{p_resource:first.resource_id}));await sql.query('update public.crm_access_profiles set active=true where user_id=$1',[users.depositor.id]);await sql.query("update public.app_memberships set status='active' where user_id=$1 and workspace_id='oar'",[users.depositor.id]);await sql.query('update auth.users set banned_until=null where id=$1',[users.depositor.id]);}
 });
 await test('explicit replacement preserves original and grants; individual withdrawal retains bytes, rejects stale revision and stops every read',async()=>{
  const replacement=await upload(users.depositor,await reserve(users.depositor,{p_title:'Nouvelle version explicite',p_type:'Passeport'}));denied(await rpc('crm_contact_document_replace',users.depositor,{p_previous:first.resource_id,p_next:replacement.resource_id,p_revision:99}));ok(await rpc('crm_contact_document_replace',users.depositor,{p_previous:first.resource_id,p_next:replacement.resource_id,p_revision:first.revision}));ok(await rpc('crm_contact_document_replace',users.depositor,{p_previous:first.resource_id,p_next:replacement.resource_id,p_revision:first.revision}));assert.equal((await list(users.depositor)).documents.find(d=>d.resource_id===first.resource_id).superseded_by,replacement.resource_id);assert.equal((await sql.query("select count(*)::int n from storage.objects where bucket_id='crm-documents' and name=$1",[first.resource_id])).rows[0].n,1);denied(await rpc('crm_contact_document_withdraw',users.depositor,{p_resource:second.resource_id,p_revision:999}));ok(await rpc('crm_contact_document_withdraw',users.depositor,{p_resource:second.resource_id,p_revision:second.revision}));ok(await rpc('crm_contact_document_withdraw',users.depositor,{p_resource:second.resource_id,p_revision:second.revision}));assert.equal((await sql.query("select count(*)::int n from storage.objects where bucket_id='crm-documents' and name=$1",[second.resource_id])).rows[0].n,1);denied(await rpc('crm_contact_document_file',users.owner,{p_resource:second.resource_id}));fixture.documents=(await list(users.owner)).documents;
 });
 await test('contact deletion and stale full save cannot orphan retained files; eight original shares and every original business row preserved',async()=>{
  const current=await payload();const snapshot=ok(await rpc('crm_read_module',users.owner,{p_module:'contacts'}));denied(await rpc('crm_mutate_record',users.owner,{p_module:'contacts',p_collection:'contacts',p_id:demo.id,p_patch:{},p_revision:snapshot.revision,p_delete:true}));const invalid=structuredClone(current);invalid.contacts=invalid.contacts.filter(c=>c.id!==demo.id);try{await sql.query("update public.crm_workspace_state set payload=$1 where workspace_id='oneaddress-riviera'",[invalid]);assert.fail('Orphan contact deletion must fail');}catch(e){assert.match(e.message,/contact_has_retained_documents/);}assert.deepEqual(await payload(),current);
  assert.deepEqual((await sql.query('select * from public.crm_document_shares where resource_id not like \'contact-private/%\' order by provider,resource_id,user_id')).rows,beforeShares);const after=await payload();for(const[c,value]of Object.entries(original)){if(Array.isArray(value)){for(const r of value)if(!['contact-evolution-supplier','contact-evolution-demo','member-rpc-owner','member-rpc-contributor'].includes(r.id))assert.ok(after[c].some(x=>JSON.stringify(x)===JSON.stringify(r)),c+' original '+r.id);}else assert.deepEqual(after[c],value,c);}assert.equal(JSON.stringify(after).includes('contact-private/'),false,'No file payload/base64 embedded in CRM');
 });
 fixture.contacts.history=row(await payload(),'contacts',contact.id);fixture.contacts.demo=row(await payload(),'contacts',demo.id);
 writeFileSync('/private/tmp/oar-contact-evolution-fixture.private.json',JSON.stringify(fixture,null,2),{mode:0o600});
 writeFileSync('/private/tmp/oar-contact-evolution-server-results.json',JSON.stringify({passed:true,results,actualLocalAuth:true,actualLocalStorage:true,externalGoogleCalls:0,productionVerified:false,originalPayloadHash:originalHash,retainedFictionalFiles:true},null,2),{mode:0o600});
 console.log(JSON.stringify({passed:results.length,fixture:'/private/tmp/oar-contact-evolution-fixture.private.json'}));
}finally{await sql.end();}
