"use client";
import { useEffect, useState } from "react";
import { useScopedOperations, isCancelled } from "@/lib/access/operations";
import { emptyGrants, moduleItems, sensitiveLabels, type ModuleGrant, type ModuleId, type Sensitive } from "@/lib/access/modules";
type User = { id:string; email:string; confirmed:boolean; active:boolean; generalAdmin:boolean; revision:number; modules:Record<ModuleId,ModuleGrant>; izordRole:string|null; assignments:string[] };
type AdminData = {invitations:{id:string;email:string;expires_at:string}[];users:User[];projects:{id:string;title:string}[];history:{id:number;action:string;actor_id:string;subject_id:string;created_at:string}[]};
export default function AccessAdministration({onDirty,onSaved}:{onDirty:(dirty:boolean)=>void;onSaved:()=>void}) {
 const begin=useScopedOperations('admin');
 const [data,setData]=useState<AdminData|null>(null),[edit,setEdit]=useState<User|null>(null),[message,setMessage]=useState(''),[dirty,setDirty]=useState(false),[busy,setBusy]=useState(false),[inviteEmail,setInviteEmail]=useState('');
 async function load(){try{const op=await begin();const r=await op.run(()=>op.client.rpc('crm_admin_users'));if(r.error)throw r.error;setData(r.data);}catch(e){if(!isCancelled(e))setMessage('Lecture des accès indisponible.');}}
 useEffect(()=>{void begin().then(op=>op.run(()=>op.client.rpc('crm_admin_users'))).then(r=>{if(r.error)setMessage('Lecture des accès indisponible.');else setData(r.data);}).catch(e=>{if(!isCancelled(e))setMessage('Lecture des accès indisponible.');});},[begin]);
 useEffect(()=>{onDirty(dirty);return()=>onDirty(false);},[dirty,onDirty]);
 const update=(next:User)=>{setEdit(next);setDirty(true);};
 async function save(){if(!edit)return;setBusy(true);try{const op=await begin();const r=await op.run(()=>op.client.rpc('crm_admin_save',{p_user:edit.id,p_revision:edit.revision,p_active:edit.active,p_general_admin:edit.generalAdmin,p_grants:edit.modules,p_izord_role:edit.izordRole,p_assignments:edit.assignments}));if(r.error)throw r.error;setDirty(false);setEdit({...edit,revision:r.data});setMessage('Droits enregistrés et confirmés par le serveur.');await op.check();onSaved();await load();}catch(e){if(!isCancelled(e))setMessage('Enregistrement refusé ou conflit de révision. Rechargez avant de confirmer.');}finally{setBusy(false);}}
 function select(user:User){if(dirty&&!window.confirm('Abandonner les modifications non enregistrées ?'))return;setEdit({...user,modules:{...emptyGrants(),...user.modules}});setDirty(false);setMessage('');}
 return <div className="module-workspace"><p className="eyebrow">Administration</p><h1>Utilisateurs et accès</h1><p>Les rôles IZORD et les dossiers affectés s’ajoutent aux droits du module. L’administration générale est indépendante.</p>{message&&<p role="status">{message}</p>}<div className="unified-admin"><section className="panel"><h2>Utilisateurs</h2>{data?.users.map(u=><button className="unified-user" key={u.id} onClick={()=>select(u)}>{u.email}<small>{!u.confirmed?'Invitation à accepter':u.active?'Actif':'Sans accès actif'}</small></button>)}<button onClick={()=>{if(!dirty||window.confirm('Abandonner la saisie ?')){setEdit({id:'invitation',email:'',confirmed:false,active:true,generalAdmin:false,revision:0,modules:emptyGrants(),izordRole:null,assignments:[]});setDirty(false);}}}>Inviter un utilisateur</button></section>
 {edit&&<section className="panel"><h2>{edit.id==='invitation'?'Nouvelle invitation':edit.email}</h2>{edit.id==='invitation'?<label>Email du destinataire<input type="email" value={inviteEmail} onChange={e=>{setInviteEmail(e.target.value);setDirty(true);}}/></label>:<><label><input type="checkbox" checked={edit.active} onChange={e=>update({...edit,active:e.target.checked})}/>Accès actif</label><label><input type="checkbox" checked={edit.generalAdmin} onChange={e=>update({...edit,generalAdmin:e.target.checked})}/>Administration générale — gérer les utilisateurs et les accès</label></>}
 <div className="unified-table"><table><thead><tr><th>Module</th><th>Droit</th><th>Permissions sensibles</th></tr></thead><tbody>{moduleItems.map(m=>{const g=edit.modules[m.tab];return <tr key={m.tab}><td>{m.label}</td><td><select aria-label={'Droit '+m.label} value={g.level} onChange={e=>update({...edit,modules:{...edit.modules,[m.tab]:{level:e.target.value,sensitive:{}}}})}><option value="none">Aucun accès</option><option value="read">Lecture</option><option value="contribute">Contribution</option></select></td><td>{Object.entries(sensitiveLabels).filter(([k])=>!k.startsWith('bank_')||m.tab==='contacts').filter(([k])=>k!=='payment'||m.tab==='vendorInvoices').map(([k,label])=>{const key=k as Sensitive;const disabled=g.level==='none'||(['delete','bank_write','payment'].includes(k)&&g.level!=='contribute')||(k==='bank_write'&&!g.sensitive.bank_read)||(k==='payment'&&!edit.modules.contacts.sensitive.bank_read);return <label className="unified-check" key={k}><input type="checkbox" checked={Boolean(g.sensitive[key])} disabled={disabled} onChange={e=>update({...edit,modules:{...edit.modules,[m.tab]:{...g,sensitive:{...g.sensitive,[key]:e.target.checked}}}})}/>{label}</label>;})}</td></tr>;})}</tbody></table></div>
 <h3>Paramétrage IZORD complémentaire</h3><label>Rôle IZORD<select value={edit.izordRole??''} onChange={e=>update({...edit,izordRole:e.target.value||null})}><option value="">Aucun rôle</option><option value="reader">Lecteur</option><option value="contributor">Contributeur</option><option value="partner">Associé</option><option value="admin">Administrateur IZORD</option></select></label><p>Contribution ne remplace jamais le rôle IZORD. Un lecteur reste lecteur. L’approbation est réservée aux rôles Associé et Administrateur IZORD, selon les droits du module.</p>{data?.projects.map(p=><label className="unified-check" key={p.id}><input type="checkbox" checked={edit.assignments.includes(p.id)} onChange={e=>update({...edit,assignments:e.target.checked?[...edit.assignments,p.id]:edit.assignments.filter(id=>id!==p.id)})}/>{p.title}</label>)}
 {edit.id==='invitation'?<button disabled={busy||!inviteEmail} onClick={async()=>{setBusy(true);try{const op=await begin();const r=await op.run(()=>fetch('/api/access/invite',{method:'POST',headers:{'Content-Type':'application/json',Authorization:'Bearer '+op.token},signal:op.signal,body:JSON.stringify({email:inviteEmail,grants:edit.modules,izordRole:edit.izordRole,assignments:edit.assignments})}));const result=await op.run(()=>r.json());setMessage(r.ok?'Invitation remise au transport. Aucun droit actif avant acceptation.':result.error);if(r.ok){setDirty(false);await op.check();await load();}}catch(e){if(!isCancelled(e))setMessage('Envoi non confirmé. Consultez les invitations en attente.');}finally{setBusy(false);}}}>Envoyer l’invitation</button>:<button disabled={busy||!dirty} onClick={save}>{busy?'Enregistrement…':'Enregistrer'}</button>}<button onClick={()=>{setEdit(null);setDirty(false);void load();}}>Annuler et recharger</button>
 </section>}</div><section className="panel"><h2>Invitations en attente</h2>{data?.invitations?.map(i=><p key={i.id}>{i.email} · expire le {new Date(i.expires_at).toLocaleString('fr-FR')} <button onClick={async()=>{if(!window.confirm('Révoquer cette invitation ?'))return;try{const op=await begin();const r=await op.run(()=>op.client.rpc('crm_invite_revoke',{p_id:i.id}));if(r.error)throw r.error;setMessage('Révocation confirmée par le serveur.');await op.check();await load();}catch(e){if(!isCancelled(e))setMessage('Révocation non confirmée. Rechargez la liste.');}}}>Révoquer l’invitation</button></p>)}</section><section className="panel"><h2>Historique des changements</h2>{data?.history.map(e=><p key={e.id}>{new Date(e.created_at).toLocaleString('fr-FR')} · {e.action} · {data.users.find(u=>u.id===e.actor_id)?.email??'Administrateur'} → {data.users.find(u=>u.id===e.subject_id)?.email??'Invitation / document'}</p>)}</section></div>;
}
