"use client";
import { useCallback, useEffect, useRef, useState } from "react";
import { useI18n } from "@/lib/i18n/I18nProvider";
import AdminHistory from "@/lib/access/AdminHistory";
import { useScopedOperations, isCancelled } from "@/lib/access/operations";
import type { AccessSnapshot } from "@/lib/access/modules";
import GoogleDriveDiagnostic from "./GoogleDriveDiagnostic";
import { emptyGrants, moduleItems, moduleSensitivePermissions, sensitiveNeedsContribution, type ModuleGrant, type ModuleId } from "@/lib/access/modules";

const invitationErrorKeys: Record<string, string> = {
  "Envoi non activé ou configuration non approuvée.": "admin.deliveryDisabled",
  "Authentification requise.": "admin.authenticationRequired",
  "Session invalide.": "admin.invalidSession",
  "Administration générale requise.": "admin.adminRequired",
  "Destinataire ou invitation invalide.": "admin.invalidRecipient",
  "Invitation refusée : vérifiez les droits et le destinataire.": "admin.invitationDeclined",
  "Envoi non confirmé. Vérifiez et révoquez l’invitation dans les invitations en attente.": "admin.deliveryCheckRevoke",
  "Envoi non confirmé ; cette invitation est révoquée. Vous pouvez reprendre.": "admin.deliveryRevoked"
};
function invitationErrorKey(error: unknown) { return typeof error === "string" ? invitationErrorKeys[error] ?? "admin.sendUnconfirmed" : "admin.sendUnconfirmed"; }
type User = { id:string; email:string; confirmed:boolean; active:boolean; generalAdmin:boolean; revision:number; modules:Record<ModuleId,ModuleGrant>; izordRole:string|null; assignments:string[] };
type AdminData = {invitations:{id:string;email:string;expires_at:string}[];users:User[];projects:{id:string;title:string}[]};
export default function AccessAdministration({onDirty,onSaved,userId,access,onReconnect}:{onDirty:(dirty:boolean)=>void;onSaved:()=>void;userId:string;access:AccessSnapshot;onReconnect:()=>Promise<void>}) {
 const { t, formatDate } = useI18n();
 const begin=useScopedOperations('admin');
 const loadRequest=useRef({sequence:0});
 const [historyReload,setHistoryReload]=useState(0);
 const [data,setData]=useState<AdminData|null>(null),[edit,setEdit]=useState<User|null>(null),[message,setMessage]=useState(''),[dirty,setDirty]=useState(false),[busy,setBusy]=useState(false),[inviteEmail,setInviteEmail]=useState('');
 const load=useCallback(async()=>{const lease=loadRequest.current,sequence=++lease.sequence;try{const op=await begin();const r=await op.run(()=>op.client.rpc('crm_admin_users'));if(sequence!==lease.sequence)return;if(r.error)throw r.error;setData(r.data);}catch(e){if(sequence===lease.sequence&&!isCancelled(e))setMessage('admin.readFailed');}},[begin]);
 async function reload(){setHistoryReload(value=>value+1);await load();}
 useEffect(()=>{const lease=loadRequest.current,sequence=lease.sequence;void Promise.resolve().then(()=>{if(sequence===lease.sequence)void load();});return()=>{lease.sequence++;};},[load]);
 useEffect(()=>{onDirty(dirty);return()=>onDirty(false);},[dirty,onDirty]);
 const update=(next:User)=>{setEdit(next);setDirty(true);};
 async function save(){if(!edit)return;setBusy(true);try{const op=await begin();const r=await op.run(()=>op.client.rpc('crm_admin_save',{p_user:edit.id,p_revision:edit.revision,p_active:edit.active,p_general_admin:edit.generalAdmin,p_grants:edit.modules,p_izord_role:edit.izordRole,p_assignments:edit.assignments}));if(r.error)throw r.error;setDirty(false);setEdit({...edit,revision:r.data});setMessage('admin.saved');await op.check();onSaved();await reload();}catch(e){if(!isCancelled(e))setMessage('admin.saveFailed');}finally{setBusy(false);}}
 function select(user:User){if(dirty&&!window.confirm(t("admin.discardChanges")))return;setEdit({...user,modules:{...emptyGrants(),...user.modules}});setDirty(false);setMessage('');}
 return <div className="module-workspace"><p className="eyebrow">{t("navigation.module.admin")}</p><h1>{t("admin.title")}</h1><p>{t("admin.hint")}</p><GoogleDriveDiagnostic userId={userId} access={access} onReconnect={onReconnect}/>{message&&<p role="status">{t(message)}</p>}<div className="unified-admin"><section className="panel"><h2>{t("admin.users")}</h2>{data?.users.map(u=><button className="unified-user" key={u.id} onClick={()=>select(u)}>{u.email}<small>{!u.confirmed?t("admin.pendingAcceptance"):u.active?t("admin.active"):t("admin.inactive")}</small></button>)}<button onClick={()=>{if(!dirty||window.confirm(t("admin.discardInput"))){setEdit({id:'invitation',email:'',confirmed:false,active:true,generalAdmin:false,revision:0,modules:emptyGrants(),izordRole:null,assignments:[]});setDirty(false);}}}>{t("admin.inviteUser")}</button></section>
 {edit&&<section className="panel"><h2>{edit.id==='invitation'?t("admin.newInvitation"):edit.email}</h2>{edit.id==='invitation'?<label>{t("admin.recipientEmail")}<input type="email" value={inviteEmail} onChange={e=>{setInviteEmail(e.target.value);setDirty(true);}}/></label>:<><label><input type="checkbox" checked={edit.active} onChange={e=>update({...edit,active:e.target.checked})}/>{t("admin.activeAccess")}</label><label><input type="checkbox" checked={edit.generalAdmin} onChange={e=>update({...edit,generalAdmin:e.target.checked})}/>{t("admin.generalAdmin")}</label></>}
 <div className="unified-table"><table><thead><tr><th>{t("admin.module")}</th><th>{t("admin.level")}</th><th>{t("admin.sensitive")}</th></tr></thead><tbody>{moduleItems.map(m=>{const g=edit.modules[m.tab];return <tr key={m.tab}><td>{t(`navigation.module.${m.tab}`)}</td><td><select aria-label={t("admin.levelFor", { module: t(`navigation.module.${m.tab}`) })} value={g.level} onChange={e=>update({...edit,modules:{...edit.modules,[m.tab]:{level:e.target.value,sensitive:{}}}})}><option value="none">{t("admin.none")}</option><option value="read">{t("admin.read")}</option><option value="contribute">{t("admin.contribute")}</option></select></td><td>{moduleSensitivePermissions(m.tab).map(key=>{const k=key;const disabled=g.level==='none'||(sensitiveNeedsContribution(key)&&g.level!=='contribute')||(k==='bank_write'&&!g.sensitive.bank_read)||(k==='payment'&&!edit.modules.contacts.sensitive.bank_read);return <label className="unified-check" key={k}><input type="checkbox" checked={Boolean(g.sensitive[key])} disabled={disabled} onChange={e=>update({...edit,modules:{...edit.modules,[m.tab]:{...g,sensitive:{...g.sensitive,[key]:e.target.checked}}}})}/>{t(`admin.permission.${key}`)}</label>;})}</td></tr>;})}</tbody></table></div>
 <h3>{t("admin.izordSettings")}</h3><label>{t("admin.izordRole")}<select value={edit.izordRole??''} onChange={e=>update({...edit,izordRole:e.target.value||null})}><option value="">{t("admin.noRole")}</option><option value="reader">{t("admin.reader")}</option><option value="contributor">{t("admin.contributor")}</option><option value="partner">{t("admin.partner")}</option><option value="admin">{t("admin.izordAdmin")}</option></select></label><p>{t("admin.izordHint")}</p>{data?.projects.map(p=><label className="unified-check" key={p.id}><input type="checkbox" checked={edit.assignments.includes(p.id)} onChange={e=>update({...edit,assignments:e.target.checked?[...edit.assignments,p.id]:edit.assignments.filter(id=>id!==p.id)})}/>{p.title}</label>)}
 {edit.id==='invitation'?<button disabled={busy||!inviteEmail} onClick={async()=>{setBusy(true);try{const op=await begin();const r=await op.run(()=>fetch('/api/access/invite',{method:'POST',headers:{'Content-Type':'application/json',Authorization:'Bearer '+op.token},signal:op.signal,body:JSON.stringify({email:inviteEmail,grants:edit.modules,izordRole:edit.izordRole,assignments:edit.assignments})}));const result=await op.run(()=>r.json());setMessage(r.ok?'admin.invitationSent':invitationErrorKey(result?.error));if(r.ok){setDirty(false);await op.check();await reload();}}catch(e){if(!isCancelled(e))setMessage('admin.sendUnconfirmed');}finally{setBusy(false);}}}>{t("admin.sendInvitation")}</button>:<button disabled={busy||!dirty} onClick={save}>{busy?t("admin.saving"):t("admin.save")}</button>}<button onClick={()=>{setEdit(null);setDirty(false);void reload();}}>{t("admin.cancelReload")}</button>
 </section>}</div><section className="panel"><h2>{t("admin.pendingInvitations")}</h2>{data?.invitations?.map(i=><p key={i.id}>{i.email} · {t("admin.expires", { date: formatDate(i.expires_at, { year: "numeric", month: "2-digit", day: "2-digit", hour: "2-digit", minute: "2-digit" }) })} <button onClick={async()=>{if(!window.confirm(t("admin.confirmRevoke")))return;try{const op=await begin();const r=await op.run(()=>op.client.rpc('crm_invite_revoke',{p_id:i.id}));if(r.error)throw r.error;setMessage('admin.revoked');await op.check();await reload();}catch(e){if(!isCancelled(e))setMessage('admin.revokeFailed');}}}>{t("admin.revokeInvitation")}</button></p>)}</section><AdminHistory key={userId+":"+JSON.stringify(access)+":"+historyReload} users={data?.users??[]}/></div>;
}
