"use client";
import {useEffect,useRef,useState,useMemo} from 'react';
import {useScopedOperations,isCancelled,type ScopedOperation} from '@/lib/access/operations';
import {readable,moduleItems,type AccessSnapshot,type ModuleId} from '@/lib/access/modules';
import catalog from '@/lib/access/collections.json';
import {BusinessContext,type BusinessPermissions} from './BusinessPermissions';
import {ContactsView,TasksView,HouseTrackingView,PlanningView,QuotesView,BookingsView,VendorInvoicesView,LeadsView,PropertiesView,VehiclesView,BoatsView,Dashboard,createQuickEntryRecords,promptQuickEntryText,createDraftQuoteFromLead,parseAssetKey,isValidPlanningDate} from './CRMApp';
import VendorQuotesView from './VendorQuotesView';
import ScopedInvoicePayments from './ScopedInvoicePayments';
import ScopedBanking from './ScopedBanking';
import ScopedDocuments from './ScopedDocuments';
import type {FormSaveResult} from '@/lib/access/useConfirmedForm';
import {parseEuroAmount} from '@/lib/currency';
import type {Contact} from '@/lib/types';
// These are per-module view models, never a CRMData payload or a global write.
type Row=Record<string,any>;
type Projection={revision:string;collections:Record<string,Row[]|number>};
const dependencies:Partial<Record<ModuleId,ModuleId[]>>={properties:['leads'],vehicles:['leads'],boats:['leads'],contacts:['leads','tasks'],tasks:['leads'],leads:['contacts','properties','vehicles','boats','tasks','quotes'],quotes:['contacts','leads'],bookings:['contacts'],vendorQuotes:['contacts','vendorInvoices'],vendorInvoices:['contacts','vendorQuotes'],houseTracking:['contacts'],planning:['contacts','properties','vehicles','boats','leads']};
export default function ModuleWorkspace({module,access,onDirty,draft,onNavigate}:{module:ModuleId;access:AccessSnapshot;onDirty:(dirty:boolean)=>void;draft?:Record<string,string>;onNavigate:(m:ModuleId,draft?:Record<string,string>)=>void}){
 const begin=useScopedOperations(module),[data,setData]=useState<Projection|null>(null),[refs,setRefs]=useState<Record<string,Row[]>>({}),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);
 const saving=useRef(false);
 const permissionFingerprint=JSON.stringify(access);
 const stableAccess=useMemo(()=>JSON.parse(permissionFingerprint) as AccessSnapshot,[permissionFingerprint]);
 const current=useRef<Projection|null>(null);const staged=useRef(new Map<string,{file:File;collection:string;id:string;operation:ScopedOperation}>());
 const grant=access.modules[module],canWrite=(m:ModuleId)=>access.modules[m]?.level==='contribute';
 function accept(next:Projection){current.current=next;setData(next);}
 useEffect(()=>{const pending=staged.current;let live=true;void (async()=>{try{const op=await begin();const r=await op.run(()=>op.client.rpc('crm_read_module',{p_module:module}));if(r.error)throw r.error;const linked:Record<string,Row[]>={};for(const m of (module==='dashboard'?moduleItems.map(m=>m.tab).filter(m=>!['dashboard','izord','documents'].includes(m)):dependencies[module]??[])){if(!readable(stableAccess,m))continue;const r=await op.run(()=>op.client.rpc('crm_reference_options',{p_module:m}));if(r.error)throw r.error;Object.assign(linked,r.data);}if(live){accept(r.data);setRefs(linked);}}catch(e){if(live&&!isCancelled(e))setMessage('Lecture indisponible. Rechargez le module.');}})();return()=>{live=false;pending.clear();onDirty(false);};},[module,stableAccess,begin,onDirty]);
 const fail=(e:unknown)=>{if(!isCancelled(e))setMessage(e instanceof Error?e.message:(e as {message?:string})?.message??'Opération non confirmée.');};
 const rows=(c:string):Row[]=>Array.isArray(data?.collections[c])?data!.collections[c] as Row[]:refs[c]??[];
 const schema=(c:string)=>catalog.find(x=>x.collection===c);
 function patchFor(c:string,row:Row,previous:Row|undefined){const fields=schema(c)?.fields??{};return Object.fromEntries(Object.entries(row).filter(([k,v])=>{const f=(fields as Record<string,{requires?:ModuleId}>)[k];return f&&(module!=='bookings'||['bookingStatus','supplierCost','depositReceived','balanceReceived','paymentStatus','expectedDeposit','paymentDueDate','clientConfirmed','depositConfirmed','supplierConfirmed','balanceConfirmed','detailsSent','serviceCompleted','assignedContactId'].includes(k))&&v!==undefined&&(!f.requires||readable(access,f.requires))&&JSON.stringify(v)!==JSON.stringify(previous?.[k])&&!String(v).startsWith('pending-upload:');}));}
 async function change(c:string,id:string,patch:Row,remove=false,op?:ScopedOperation){const operation=op??await begin();const r=await operation.run(()=>operation.client.rpc('crm_mutate_record',{p_module:module,p_collection:c,p_id:id,p_patch:patch,p_revision:current.current?.revision,p_delete:remove}));if(r.error)throw new Error(r.error.message.includes('revision_conflict')?'Conflit : les données ont changé. Rechargez avant de reprendre.':r.error.message);accept(r.data);}
 async function save(c:string,row:Row):Promise<FormSaveResult>{if(saving.current)return {ok:false,message:'Un enregistrement est déjà en cours.'};saving.current=true;setBusy(true);setMessage('');onDirty(true);try{const op=await begin();const before=rows(module==='bookings'?'bookings':c).find(x=>x.id===row.id);const initialPatch=patchFor(c,row,before);const hasUpload=[...staged.current.values()].some(x=>x.collection===c&&x.id===row.id);const deferred:Row={};if(hasUpload&&c==='vendorInvoices'){for(const k of ['paidAmount','paymentMethod']){if(k in initialPatch){deferred[k]=initialPatch[k];delete initialPatch[k];}}}await change(c,row.id,initialPatch,false,op);for(const [marker,item]of staged.current){if(item.collection!==c||item.id!==row.id)continue;await item.operation.check();const reserved=await op.run(()=>op.client.rpc('crm_new_document',{p_collection:c,p_record:row.id,p_title:item.file.name}));if(reserved.error)throw reserved.error;const uploaded=await op.run(()=>op.client.storage.from('crm-documents').upload(reserved.data,item.file,{upsert:false}));if(uploaded.error)throw uploaded.error;const pathField=Object.keys(row).find(k=>row[k]===marker);if(pathField)await change(c,row.id,{[pathField]:reserved.data},false,op);staged.current.delete(marker);}if(Object.keys(deferred).length)await change(c,row.id,deferred,false,op);await op.check();onDirty(false);setMessage('Enregistrement confirmé par le serveur.');return {ok:true,recordId:row.id};}catch(e){const raw=e instanceof Error?e.message:'';const message=isCancelled(e)?'Enregistrement interrompu : la session ou vos droits ont changé.':raw.includes('Conflit')?raw:/fetch|network|Failed|Network/i.test(raw)?'Connexion interrompue. Enregistrement non confirmé ; votre saisie est conservée.':'Enregistrement refusé. Vérifiez les champs et vos droits ; votre saisie est conservée.';if(!isCancelled(e))setMessage(message);return {ok:false,message,cancelled:isCancelled(e)};}finally{saving.current=false;setBusy(false);}}
 async function updateHouseWorker(id:string,patch:import('@/lib/houseTracking').HouseWorkerEdit):Promise<FormSaveResult>{
  if(!canWrite('houseTracking')||saving.current)return {ok:false,message:'Modification non autorisée ou enregistrement en cours.'};
  saving.current=true;setBusy(true);onDirty(true);
  try{const op=await begin();const r=await op.run(()=>op.client.rpc('crm_update_house_worker',{p_id:id,p_patch:{hourlyRate:patch.hourlyRate},p_revision:current.current?.revision}));if(r.error)throw new Error(r.error.message);accept(r.data);onDirty(false);return {ok:true,recordId:id};}
  catch(e){return {ok:false,cancelled:isCancelled(e),message:isCancelled(e)?'Enregistrement interrompu : le compte ou les droits ont changé.':e instanceof Error&&e.message.includes('revision_conflict')?'Conflit : les données ont changé. Votre saisie est conservée ; rechargez avant de reprendre.':'Enregistrement non confirmé. Votre saisie est conservée ; vérifiez la connexion et vos droits.'};}
  finally{saving.current=false;setBusy(false);}
 }
 function saveRows(c:string,next:Row[]){const before=rows(c);const changed=next.filter(r=>JSON.stringify(r)!==JSON.stringify(before.find(b=>b.id===r.id)));const deleted=before.filter(r=>!next.some(n=>n.id===r.id));if(changed.length===1&&!deleted.length)return save(c,changed[0]);else if(deleted.length===1&&!changed.length)void remove(c,deleted[0].id);else if(changed.length||deleted.length){const message='Modifiez un seul élément à la fois.';setMessage(message);return {ok:false as const,message};}}
 async function remove(c:string,id:string){if(!grant?.sensitive.delete)return setMessage('Suppression non autorisée.');setBusy(true);try{await change(c,id,{},true);onDirty(false);setMessage('Suppression confirmée.');}catch(e){fail(e);}finally{setBusy(false);}}
 function form(c:string,e:React.FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget),row:Row={id:e.currentTarget.dataset.savedRecordId||crypto.randomUUID()};for(const [k,field]of Object.entries(schema(c)?.fields??{})){if(f.has(k))row[k]=field.type==='number'?parseEuroAmount(f.get(k)):field.type==='boolean'?['true','on'].includes(String(f.get(k))):String(f.get(k)??'').trim();}if(f.has('assetKey'))Object.assign(row,parseAssetKey(f.get('assetKey')));if(c==='contacts'){if(row.kind==='Prestataire'){row.relationshipStatus='Prestataire';row.supplierCategory=row.supplierCategory==='Autre'?String(f.get('supplierCategoryCustom')??'Autre'):row.supplierCategory;}else row.supplierCategory='';}if(c==='planningEntries'){row.endDate||=row.startDate;if(!isValidPlanningDate(row.startDate)||!isValidPlanningDate(row.endDate)||row.endDate<row.startDate)return setMessage('Dates du planning invalides.');}return save(c,row);}
 async function workflow(name:string,args:Row){setBusy(true);try{const op=await begin();const r=await op.run(()=>op.client.rpc(name,{...args,p_revision:current.current?.revision}));if(r.error)throw r.error;accept(r.data);onDirty(false);setMessage('Opération confirmée par le serveur.');}catch(e){fail(e);}finally{setBusy(false);}}
 async function relatedChange(m:ModuleId,c:string,id:string,patch:Row){try{const op=await begin();const v=await op.run(()=>op.client.rpc('crm_read_module',{p_module:m}));if(v.error)throw v.error;const r=await op.run(()=>op.client.rpc('crm_mutate_record',{p_module:m,p_collection:c,p_id:id,p_patch:patch,p_revision:v.data.revision}));if(r.error)throw r.error;setRefs(prev=>({...prev,[c]:r.data.collections[c]}));setMessage('Modification liée confirmée.');}catch(e){fail(e);}}
 const hiddenFields=['notes','importantNotes','supplierPriceNotes','supplierCommissionNotes','paymentNotes','operationNotes','preferences',...(!readable(access,'contacts')?['contactName','contactId','clientName','owner','assignedContactId','contactSearch']:[]),...(!readable(access,'leads')?['linkedTo','leadId']:[]),...(!readable(access,'documents')||!canWrite('documents')?['invoiceFile','quoteFile','documentFile']:[]),...(!grant?.sensitive.payment&&module==='vendorInvoices'?['paidAmount','paymentMethod']:[])].filter(k=>!(module==='tasks'&&k==='owner'));
 const business:BusinessPermissions={write:canWrite(module)&&!busy&&(module!=='bookings'||canWrite('quotes')),remove:Boolean(grant?.sensitive.delete)&&!busy&&module!=='bookings',export:Boolean(grant?.sensitive.export),read:m=>readable(access,m),canWrite,hiddenFields,
  markDirty:()=>onDirty(true),
  check:async()=>{await begin();},
  download:async(path,name)=>{try{const op=await begin();const r=await op.run(()=>op.client.storage.from('crm-documents').download(path));if(r.error)throw r.error;await op.download(r.data,name);}catch(e){fail(e);}},
  upload:async(c,id,file)=>{const op=await begin();if(!canWrite('documents'))throw new Error('Contribution Documents requise.');const marker='pending-upload:'+crypto.randomUUID();staged.current.set(marker,{collection:c,id,file,operation:op});return marker;}
 };
 async function exportModule(){try{const op=await begin();const r=await op.run(()=>op.client.rpc('crm_export_module',{p_module:module}));if(r.error)throw r.error;await op.download(new Blob([JSON.stringify(r.data.collections,null,2)],{type:'application/json'}),module+'.json');}catch(e){fail(e);}}
 async function fromMessage(){if(!canWrite('contacts')||!canWrite('leads'))return need('leads');try{const op=await begin();const text=promptQuickEntryText();if(!text)return;await op.check();const contacts=await op.run(()=>op.client.rpc('crm_read_module',{p_module:'contacts'}));if(contacts.error)throw contacts.error;const leads=await op.run(()=>op.client.rpc('crm_read_module',{p_module:'leads'}));if(leads.error)throw leads.error;const draft=createQuickEntryRecords(text,contacts.data.collections.contacts,leads.data.collections.leads);if(!draft)return;const result=await op.run(()=>op.client.rpc('crm_create_from_message',{p_contact:{...patchFor('contacts',draft.newContact,undefined),id:draft.newContact.id},p_lead:{...patchFor('leads',draft.newLead,undefined),id:draft.newLead.id},p_contacts_revision:contacts.data.revision,p_leads_revision:leads.data.revision}));if(result.error)throw result.error;setMessage('Contact et lead créés et confirmés par le serveur.');await op.check();onNavigate('leads');}catch(e){fail(e);}}
 const open=(m:ModuleId,value?:Record<string,string>)=>{if(readable(access,m))onNavigate(m,value);else need(m);};
 const need=(m:ModuleId)=>setMessage('Le parcours nécessite le module '+moduleItems.find(x=>x.tab===m)?.label+' avec les droits correspondants. Ouvrez-le dans la barre latérale.');
 const contacts=rows('contacts') as Contact[];
 return <BusinessContext.Provider value={business}><div className="module-workspace business-workspace" onChangeCapture={e=>{if((e.target as HTMLElement).closest('form'))onDirty(true);}}><header className="topbar"><div><p className="eyebrow">CRM interne · {canWrite(module)?'Contribution':'Lecture'}</p><h1>{moduleItems.find(m=>m.tab===module)?.label}</h1></div>{grant?.sensitive.export&&<button onClick={()=>void exportModule()}>Exporter ce module</button>}</header>{message&&<p role="status">{message}</p>}{busy&&<p role="status">Enregistrement en cours…</p>}{(dependencies[module]??[]).filter(m=>!readable(access,m)).length>0&&<p className="muted-line">Références indisponibles sans droit de lecture : {(dependencies[module]??[]).filter(m=>!readable(access,m)).map(m=>moduleItems.find(x=>x.tab===m)?.label).join(', ')}. Les données déjà liées sont conservées.</p>}
 {!data?<p>Chargement du module…</p>:<>
 {module==='tasks'&&<TasksView prefilledTitle={draft?.title} preselectedLeadId={draft?.leadId} tasks={rows('tasks') as any} leads={rows('leads') as any} onAdd={e=>form('tasks',e)} onUpdate={r=>void save('tasks',r)} onDelete={id=>void remove('tasks',id)} onStatusChange={(id,status)=>void save('tasks',{...rows('tasks').find(r=>r.id===id),id,status})}/>}
 {module==='contacts'&&<><ContactsView actor="Compte connecté" contacts={contacts} leads={rows('leads') as any} tasks={rows('tasks') as any} onAdd={e=>form('contacts',e)} onUpdate={r=>save('contacts',r)} onDelete={id=>void remove('contacts',id)} onCreateLead={name=>open('leads',{contactName:name})} onCreateTask={name=>open('tasks',{title:'Relancer '+name})}/>{grant?.sensitive.bank_read&&contacts.map(contact=><section className="card" key={contact.id}><h3>{contact.name}</h3><ScopedBanking contact={contact} revision={data.revision} canWrite={Boolean(grant.sensitive.bank_write&&canWrite(module))} onResult={v=>accept(v as Projection)}/></section>)}</>}
 {module==='houseTracking'&&<HouseTrackingView contacts={contacts} houses={rows('houseTrackingHouses') as any} workers={rows('houseTrackingWorkers') as any} timeEntries={rows('houseTimeEntries') as any} payments={rows('housePayments') as any} onAddHouse={r=>void save('houseTrackingHouses',r)} onDeleteHouse={id=>void remove('houseTrackingHouses',id)} onAddWorker={r=>void save('houseTrackingWorkers',r)} onUpdateWorker={updateHouseWorker} onArchiveWorker={id=>void save('houseTrackingWorkers',{id,status:'Inactif'})} onReactivateWorker={id=>void save('houseTrackingWorkers',{id,status:'Actif'})} onPermanentlyDeleteWorker={id=>void remove('houseTrackingWorkers',id)} onAddTimeEntry={r=>save('houseTimeEntries',r)} onDeleteTimeEntry={id=>void remove('houseTimeEntries',id)} onAddPayment={r=>void save('housePayments',r)} onDeletePayment={id=>void remove('housePayments',id)}/>}
 {module==='planning'&&<PlanningView contacts={contacts} leads={rows('leads') as any} properties={rows('properties') as any} vehicles={rows('vehicles') as any} boats={rows('boats') as any} planningEntries={rows('planningEntries') as any} onAddPlanningEntry={e=>form('planningEntries',e)} onUpdatePlanningEntry={(id,e)=>{e.preventDefault();const f=new FormData(e.currentTarget);const p:Row={id,...Object.fromEntries(f)};Object.assign(p,parseAssetKey(f.get('assetKey')));p.blocksAvailability=String(f.get('blocksAvailability'))==='true';void save('planningEntries',p);return true;}} onDeletePlanningEntry={id=>void remove('planningEntries',id)} onPatchPlanningEntry={(id,p)=>void save('planningEntries',{id,...p})} onPatchLeadReservationDates={(id,startDate,endDate)=>{if(!canWrite('leads'))return need('leads');void relatedChange('leads','leads',id,{rentalStartDate:startDate,rentalEndDate:endDate});}}/>}
 {module==='quotes'&&<QuotesView contacts={contacts} quotes={rows('quotes') as any} activeActor="Compte connecté" onChange={next=>saveRows('quotes',next)}/>}
 {module==='bookings'&&<BookingsView contacts={contacts} quotes={rows('bookings') as any} activeActor="Compte connecté" onChange={next=>{const before=rows('bookings');const changed=next.find(r=>JSON.stringify(r)!==JSON.stringify(before.find(b=>b.id===r.id)));if(changed)void save('quotes',changed);}}/>}
 {module==='leads'&&<LeadsView preselectedContactName={draft?.contactName} leads={rows('leads') as any} contacts={contacts} tasks={rows('tasks') as any} quotes={rows('quotes') as any} properties={rows('properties') as any} vehicles={rows('vehicles') as any} boats={rows('boats') as any} onAdd={e=>form('leads',e)} onUpdate={r=>void save('leads',r)} onStatusChange={(id,status)=>void save('leads',{id,status})} onDelete={id=>void remove('leads',id)} onCreateQuote={r=>{if(!canWrite('quotes'))return need('quotes');void (async()=>{try{const op=await begin();const d=createDraftQuoteFromLead(r);const q=await op.run(()=>op.client.rpc('crm_read_module',{p_module:'quotes'}));if(q.error)throw q.error;const result=await op.run(()=>op.client.rpc('crm_mutate_record',{p_module:'quotes',p_collection:'quotes',p_id:d.id,p_patch:patchFor('quotes',d,undefined),p_revision:q.data.revision}));if(result.error)throw result.error;setMessage('Devis créé : ouvrez Devis pour le compléter.');}catch(e){fail(e);}})();}} onCreateTask={lead=>open('tasks',{title:lead.nextAction||'Relancer '+lead.contactName,leadId:lead.id})}/>}
 {module==='properties'&&<PropertiesView properties={rows('properties') as any} leads={rows('leads') as any} onAdd={e=>form('properties',e)} onUpdate={r=>void save('properties',r)} onDelete={id=>void remove('properties',id)}/>}
 {module==='vehicles'&&<VehiclesView vehicles={rows('vehicles') as any} leads={rows('leads') as any} onAdd={e=>form('vehicles',e)} onUpdate={r=>void save('vehicles',r)} onDelete={id=>void remove('vehicles',id)}/>}
 {module==='boats'&&<BoatsView boats={rows('boats') as any} leads={rows('leads') as any} onAdd={e=>form('boats',e)} onUpdate={r=>void save('boats',r)} onDelete={id=>void remove('boats',id)}/>}
 {module==='vendorQuotes'&&<VendorQuotesView contacts={contacts} quotes={rows('vendorQuotes') as any} invoices={rows('vendorInvoices') as any} onAdd={r=>void save('vendorQuotes',r)} onUpdate={r=>void save('vendorQuotes',r)} onDelete={(id,choice)=>{void (async()=>{try{const op=await begin();let rev=null;if(choice==='delete-both'){const r=await op.run(()=>op.client.rpc('crm_read_module',{p_module:'vendorInvoices'}));if(r.error)throw r.error;rev=r.data.revision;}await workflow('crm_delete_vendor_quote',{p_quote:id,p_choice:choice??null,p_invoice_revision:rev});}catch(e){fail(e);}})();}} onValidate={id=>void workflow('crm_validate_vendor_quote',{p_quote:id})} onReject={id=>void workflow('crm_reject_vendor_quote',{p_quote:id})} onOpenInvoice={()=>open('vendorInvoices')}/>}
 {module==='vendorInvoices'&&<><VendorInvoicesView actor="Compte connecté" contacts={contacts} documents={[]} invoices={rows('vendorInvoices') as any} quotes={rows('vendorQuotes') as any} onAdd={r=>void save('vendorInvoices',r)} onUpdate={r=>void save('vendorInvoices',r)} onDelete={id=>void remove('vendorInvoices',id)} onDeleteOrphan={id=>void workflow('crm_delete_orphan_invoice',{p_invoice:id})} onOpenQuote={()=>open('vendorQuotes')} onUpdateContact={()=>need('contacts')}/>{grant?.sensitive.payment&&<ScopedInvoicePayments invoices={rows('vendorInvoices') as any} revision={data.revision} onResult={v=>accept(v as Projection)}/>}</>}
 {module==='dashboard'&&<Dashboard stats={{pipeline:rows('leads').reduce((n,r)=>n+Number(r.value||0),0),won:rows('leads').filter(r=>r.status==='Gagné').length,openTasks:rows('tasks').filter(r=>r.status!=='Terminé').length,availableProperties:rows('properties').filter(r=>r.status==='Disponible').length}} data={{...Object.fromEntries(catalog.map(c=>[c.collection,rows(c.collection)])),bookings:rows('bookings')} as any} onLeadStatusChange={(id,status)=>void relatedChange('leads','leads',id,{status})} onTaskStatusChange={(id,status)=>void relatedChange('tasks','tasks',id,{status})} onStartMessage={()=>void fromMessage()} onStartContactLead={()=>open('contacts')} onStartInventory={()=>open('properties')} onShowLeads={()=>open('leads')} onCloudBackup={()=>setMessage('Sauvegarde globale réservée à l’accès complet.')} onDashboardAction={m=>open(m as ModuleId)}/>}

 {module==='documents'&&<ScopedDocuments access={access} onSaved={()=>{void (async()=>{try{const op=await begin();const r=await op.run(()=>op.client.rpc('crm_read_module',{p_module:'documents'}));if(r.error)throw r.error;accept(r.data);onDirty(false);}catch(e){fail(e);}})();}} documents={rows('documents')}/>}
 </> }</div></BusinessContext.Provider>;
}
