"use client";
import { moduleMessage } from "@/lib/i18n/moduleMessage";
import { useI18n } from "@/lib/i18n/I18nProvider";
import {useState} from 'react';
import type {Contact,VendorBankAccount} from '@/lib/types';
import {validateIban,validateBic,formatIban} from '@/lib/vendorBanking';
import {useScopedOperations,isCancelled} from '@/lib/access/operations';
export default function ScopedBanking({contact,revision,canWrite,onResult}:{contact:Contact;revision:string;canWrite:boolean;onResult:(data:unknown)=>void}){
  const {t, label: uiLabel} = useI18n();

 const begin=useScopedOperations('contacts');
 const [error,setError]=useState(''),[busy,setBusy]=useState(false),[adding,setAdding]=useState(false);
 async function action(kind:string,account:Partial<VendorBankAccount>){setBusy(true);try{const op=await begin();const r=await op.run(()=>op.client.rpc('crm_bank_action',{p_contact:contact.id,p_action:kind,p_account:account,p_revision:revision}));if(r.error)throw r.error;await op.check();setError('');setAdding(false);onResult(r.data);}catch(e){if(!isCancelled(e))setError('Opération bancaire non confirmée.');}finally{setBusy(false);}}
 return <details><summary>{t("modules.scopedBanking.authorisedBankDetails")}</summary>{error&&<p role="alert">{moduleMessage(error, t)}</p>}{(contact.supplierBankAccounts??[]).map(a=><section key={a.id}><p>{a.accountHolder} · {uiLabel(a.status, "modules")}{a.isPrimary?t("modules.vendorBanking.primary"):''}</p><p><code>{formatIban(a.iban)}</code> · {a.bic}</p><button onClick={async()=>{try{const op=await begin();await op.check();await op.run(()=>navigator.clipboard.writeText(a.iban));setError('IBAN copié.');}catch(e){if(!isCancelled(e))setError('Copie indisponible : sélectionnez le texte affiché.');}}}>{t("modules.scopedBanking.copyIBAN")}</button>{canWrite&&<><button disabled={busy||a.status==='Archivé'} onClick={()=>{if(window.confirm(t("modules.scopedBanking.confirmThatYouHaveVerifiedTheBankDetailsThroughATrustedChannel")))void action('verify',{id:a.id});}}>{t("modules.scopedBanking.verify")}</button><button disabled={busy||a.status!=='Vérifié'} onClick={()=>void action('primary',{id:a.id})}>{t("modules.scopedBanking.primary")}</button><button disabled={busy||a.status==='Archivé'} onClick={()=>void action('archive',{id:a.id})}>{t("modules.vendorBanking.archive")}</button></>}</section>)}{canWrite&&<button onClick={()=>setAdding(!adding)}>{t("modules.scopedBanking.addAnAccount")}</button>}{adding&&<form className="unified-form" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);const a={accountHolder:String(f.get('holder')),iban:String(f.get('iban')),bic:String(f.get('bic')),bankName:String(f.get('bank'))};if(!validateIban(a.iban)||!validateBic(a.bic)){setError('IBAN ou BIC invalide.');return;}void action('add',a);}}><label>{t("modules.vendorBanking.accountHolder")}<input name="holder" required/></label><label>{t("modules.vendorBanking.iban")}<input name="iban" required/></label><label>{t("modules.vendorBanking.bic_7434fa")}<input name="bic" required/></label><label>{t("modules.vendorBanking.bank")}<input name="bank"/></label><p>{t("modules.scopedBanking.everyNewAccountRemainsAwaitingVerificationTheVerifiedPrimaryAccountIsRetained")}</p><button disabled={busy}>{t("modules.scopedBanking.saveAccount")}</button></form>}</details>;
}
