"use client";
import {useRef,useState} from 'react';
import {useScopedOperations,isCancelled} from '@/lib/access/operations';
import catalog from '@/lib/access/collections.json';
import type {AccessSnapshot} from '@/lib/access/modules';
type Doc={provider?:string;resource_id?:string;title?:string;module?:string;folder?:string;bank?:boolean;replaceable?:boolean;deletable?:boolean;collection?:string;record_id?:string;superseded_by?:string};
export default function ScopedDocuments({access,onSaved,documents=[]}:{access:AccessSnapshot;onSaved:()=>void;documents?:Doc[]}){
 const begin=useScopedOperations('documents'),[collection,setCollection]=useState(''),[rows,setRows]=useState<{id:string;name?:string;title?:string;contactName?:string}[]>([]),[record,setRecord]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[folder,setFolder]=useState(''),[query,setQuery]=useState('');
 const selection=useRef(0),eligible=catalog.filter(c=>access.modules[c.module as keyof typeof access.modules]?.level==='contribute');
 const fail=(e:unknown)=>{if(!isCancelled(e))setError(e instanceof Error?e.message:'Opération non confirmée.');};
 async function download(doc:Doc){try{const op=await begin();let blob:Blob;if(doc.provider==='storage'){const r=await op.run(()=>op.client.storage.from('crm-documents').download(doc.resource_id!));if(r.error)throw r.error;blob=r.data;}else{const r=await op.run(()=>fetch('/api/drive/file?download=1&fileId='+encodeURIComponent(doc.resource_id!),{headers:{Authorization:'Bearer '+op.token},signal:op.signal}));if(!r.ok)throw new Error('Document inaccessible.');blob=await op.run(()=>r.blob());}await op.download(blob,doc.title??'document');}catch(e){fail(e);}}
 async function remove(doc:Doc){if(!window.confirm('Supprimer ce document ?'))return;try{const op=await begin();const r=await op.run(()=>op.client.storage.from('crm-documents').remove([doc.resource_id!]));if(r.error)throw r.error;const forgotten=await op.run(()=>op.client.rpc('crm_forget_document',{p_resource:doc.resource_id}));if(forgotten.error)throw forgotten.error;await op.check();onSaved();}catch(e){fail(e);}}
 const ownerGrant=(doc:Doc)=>access.modules[doc.module as keyof typeof access.modules];
 const writable=(doc:Doc)=>access.modules.documents?.level==='contribute'&&ownerGrant(doc)?.level==='contribute'&&(!doc.bank||access.modules.contacts?.sensitive.bank_write);
 async function replace(doc:Doc,file:File){if(!file.size||file.size>25000000)return setError('Fichier de 25 Mo maximum requis.');if(!window.confirm('Créer une nouvelle version de ce document ? L’ancienne version sera conservée.'))return;setBusy(true);try{const op=await begin();const reserved=await op.run(()=>op.client.rpc('crm_new_document',{p_collection:doc.collection,p_record:doc.record_id,p_title:file.name}));if(reserved.error)throw reserved.error;const uploaded=await op.run(()=>op.client.storage.from('crm-documents').upload(reserved.data,file,{upsert:false}));if(uploaded.error)throw uploaded.error;const committed=await op.run(()=>op.client.rpc('crm_replace_document',{p_previous:doc.resource_id,p_next:reserved.data}));if(committed.error)throw committed.error;await op.check();setError('Nouvelle version confirmée. L’original est conservé.');onSaved();}catch(e){fail(e);}finally{setBusy(false);}}
 return <section className="card"><h2>Documents autorisés</h2><p>Les dossiers et fichiers affichés sont limités aux modules propriétaires accessibles. Le téléchargement exige Export sur Documents et sur le module propriétaire.</p><label>Rechercher<input value={query} onChange={e=>setQuery(e.target.value)}/></label><label>Dossier<select value={folder} onChange={e=>setFolder(e.target.value)}><option value="">Tous les dossiers autorisés</option>{Array.from(new Set(documents.map(d=>d.folder||'Documents'))).map(f=><option key={f}>{f}</option>)}</select></label>{documents.filter(d=>(!folder||(d.folder||'Documents')===folder)&&(d.title??'').toLowerCase().includes(query.toLowerCase())).map(d=><article key={d.resource_id}><h3>{d.title}</h3><p>{d.folder||'Documents'} · {d.module}{d.superseded_by?' · Ancienne version':''}</p>{access.modules.documents?.sensitive.export&&ownerGrant(d)?.sensitive.export&&<button onClick={()=>void download(d)}>Télécharger</button>}{writable(d)&&<button onClick={async()=>{const title=window.prompt('Nom du document',d.title),nextFolder=title===null?null:window.prompt('Dossier',d.folder||'Documents');if(title===null||nextFolder===null)return;try{const op=await begin();const r=await op.run(()=>op.client.rpc('crm_update_document',{p_resource:d.resource_id,p_title:title,p_folder:nextFolder}));if(r.error)throw r.error;await op.check();onSaved();}catch(e){fail(e);}}}>Renommer / classer</button>}{d.deletable&&writable(d)&&access.modules.documents?.sensitive.delete&&ownerGrant(d)?.sensitive.delete&&<button onClick={()=>void remove(d)}>Supprimer</button>}{d.replaceable&&writable(d)&&<label>Remplacer (nouvelle version)<input type="file" disabled={busy} accept="application/pdf,image/jpeg,image/png" onChange={e=>{const file=e.target.files?.[0];if(file)void replace(d,file);e.target.value='';}}/></label>}</article>)}
 {access.modules.documents?.level==='contribute'&&<form className="unified-form" onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget),file=f.get('file');if(!(file instanceof File)||!file.size||file.size>25000000){setError('Fichier de 25 Mo maximum requis.');return;}setBusy(true);try{const op=await begin();const r=await op.run(()=>op.client.rpc('crm_new_document',{p_collection:collection,p_record:record,p_title:file.name,p_bank:f.get('bank')==='on'}));if(r.error)throw r.error;const upload=await op.run(()=>op.client.storage.from('crm-documents').upload(r.data,file,{upsert:false}));if(upload.error)throw upload.error;await op.check();setError('Document enregistré.');onSaved();}catch(e){fail(e);}finally{setBusy(false);}}}><h3>Ajouter un document classé</h3><label>Module propriétaire<select required value={collection} onChange={async e=>{const id=++selection.current;const c=eligible.find(c=>c.collection===e.target.value);setCollection(c?.collection??'');setRecord('');setRows([]);if(c)try{const op=await begin();const r=await op.run(()=>op.client.rpc('crm_reference_options',{p_module:c.module}));if(r.error)throw r.error;if(id===selection.current)setRows(r.data[c.collection]);}catch(e){fail(e);}}}><option value="">Choisir</option>{eligible.map(c=><option key={c.collection} value={c.collection}>{c.label}</option>)}</select></label><label>Élément propriétaire<select required value={record} onChange={e=>setRecord(e.target.value)}><option value="">Choisir</option>{rows.map(r=><option key={r.id} value={r.id}>{r.name??r.title??r.contactName??r.id}</option>)}</select></label>{collection==='contacts'&&access.modules.contacts?.sensitive.bank_write&&<label><input type="checkbox" name="bank" defaultChecked/>Document bancaire (RIB)</label>}<label>Fichier<input type="file" name="file" required accept="application/pdf,image/jpeg,image/png"/></label><button disabled={busy||!record}>Envoyer le document</button></form>}{error&&<p role="status">{error}</p>}</section>;
}
