"use client";
import {useState} from 'react';
import type {Contact,VendorBankAccount} from '@/lib/types';
import {validateIban,validateBic,formatIban} from '@/lib/vendorBanking';
import {useScopedOperations,isCancelled} from '@/lib/access/operations';
export default function ScopedBanking({contact,revision,canWrite,onResult}:{contact:Contact;revision:string;canWrite:boolean;onResult:(data:unknown)=>void}){
 const begin=useScopedOperations('contacts');
 const [error,setError]=useState(''),[busy,setBusy]=useState(false),[adding,setAdding]=useState(false);
 async function action(kind:string,account:Partial<VendorBankAccount>){setBusy(true);try{const op=await begin();const r=await op.run(()=>op.client.rpc('crm_bank_action',{p_contact:contact.id,p_action:kind,p_account:account,p_revision:revision}));if(r.error)throw r.error;await op.check();setError('');setAdding(false);onResult(r.data);}catch(e){if(!isCancelled(e))setError('Opération bancaire non confirmée.');}finally{setBusy(false);}}
 return <details><summary>Coordonnées bancaires autorisées</summary>{error&&<p role="alert">{error}</p>}{(contact.supplierBankAccounts??[]).map(a=><section key={a.id}><p>{a.accountHolder} · {a.status}{a.isPrimary?' · Principal':''}</p><p><code>{formatIban(a.iban)}</code> · {a.bic}</p><button onClick={async()=>{try{const op=await begin();await op.check();await op.run(()=>navigator.clipboard.writeText(a.iban));setError('IBAN copié.');}catch(e){if(!isCancelled(e))setError('Copie indisponible : sélectionnez le texte affiché.');}}}>Copier l’IBAN</button>{canWrite&&<><button disabled={busy||a.status==='Archivé'} onClick={()=>{if(window.confirm('Confirmez avoir vérifié le RIB par un canal de confiance.'))void action('verify',{id:a.id});}}>Vérifier</button><button disabled={busy||a.status!=='Vérifié'} onClick={()=>void action('primary',{id:a.id})}>Principal</button><button disabled={busy||a.status==='Archivé'} onClick={()=>void action('archive',{id:a.id})}>Archiver</button></>}</section>)}{canWrite&&<button onClick={()=>setAdding(!adding)}>Ajouter un compte</button>}{adding&&<form className="unified-form" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);const a={accountHolder:String(f.get('holder')),iban:String(f.get('iban')),bic:String(f.get('bic')),bankName:String(f.get('bank'))};if(!validateIban(a.iban)||!validateBic(a.bic)){setError('IBAN ou BIC invalide.');return;}void action('add',a);}}><label>Titulaire<input name="holder" required/></label><label>IBAN<input name="iban" required/></label><label>BIC<input name="bic" required/></label><label>Banque<input name="bank"/></label><p>Tout nouveau compte reste À vérifier. Le principal vérifié est conservé.</p><button disabled={busy}>Enregistrer le compte</button></form>}</details>;
}
