/** Isolated browser proof for native PDF/image modules, NOT authenticated product E2E. */
import assert from 'node:assert/strict';
import { createServer } from 'node:http';
import { createRequire } from 'node:module';
import { readFileSync, mkdirSync, writeFileSync, mkdtempSync, rmSync } from 'node:fs';
import { join, resolve } from 'node:path';
import { tmpdir } from 'node:os';
import { createHash } from 'node:crypto';
const root=resolve(import.meta.dirname,'../..');
const artifacts=process.env.IZORD_ENGINE_ARTIFACTS;
assert.ok(artifacts&&resolve(artifacts).startsWith('/Users/vg/.codex/visualizations/'),'Explicit review artifact directory required');
const fixtureDir=resolve(artifacts,'../engine-fixtures'); mkdirSync(artifacts,{recursive:true});
const require=createRequire(import.meta.url);
const {build}=require('/tmp/izord-browser-runtime/node_modules/esbuild/lib/main.js');
const {chromium}=require('/tmp/izord-playwright-runtime-20260917/node_modules/playwright');
const source=readFileSync('/Users/vg/Desktop/IZORD_Invest_Fiche_Projet_Locations_v3 (1).html','utf8');
assert.equal(createHash('sha256').update(source).digest('hex'),'8c3fe11e16c96f80091a8a3b5602d8d324a18c3bae0bb2256539e17a9e7427d1');
const scripts=[...source.matchAll(/<script(?:[^>]*)>([\s\S]*?)<\/script>/g)].map(m=>m[1]);
const crop=scripts[2].slice(scripts[2].indexOf('function cropPhoto('),scripts[2].indexOf("document.querySelectorAll('[data-photo]')"));
const resize=scripts[3].slice(scripts[3].indexOf('async function resizeImported('),scripts[3].indexOf('async function analyzeAgencyFiles('));
const bundle=await build({stdin:{contents:'import * as model from "./lib/izord/model";import * as agency from "./lib/izord/agency";import * as photos from "./lib/izord/photos";window.engine={...model,...agency,...photos};',resolveDir:root},bundle:true,write:false,format:'iife',platform:'browser',target:'chrome120'});
const files=new Map(['fiche-numerique-fictive.pdf','fiche-distincte-fictive.pdf','fiche-incomplete-fictive.pdf','scan-fictif-sans-texte.pdf','photo-fictive.jpg','photo-fictive.png','photo-fictive.webp'].map(name=>['/fixtures/'+name,readFileSync(join(fixtureDir,name))]));
const origin='http://127.0.0.1:3167';
const server=createServer((req,res)=>{
 if(req.method!=='GET'){res.writeHead(405).end();return;}
 if(req.url==='/'){res.setHeader('Content-Type','text/html; charset=utf-8');res.end('<!doctype html><meta charset="utf-8"><title>IZORD fictional engine test</title><h1>Fixture technique, aucune donnée réelle</h1><script src="/engine.js"></script>');}
 else if(req.url==='/engine.js'){res.setHeader('Content-Type','application/javascript; charset=utf-8');res.end(bundle.outputFiles[0].contents);}
 else if(files.has(req.url)){res.end(files.get(req.url));}
 else res.writeHead(404).end();
});
const result={scope:'Native generator module browser checks; fictional inputs, no Auth/application/Storage validation',startedAt:new Date().toISOString(),sourceSHA256:createHash('sha256').update(source).digest('hex'),checks:[],browserEvents:[],remoteAttempts:[]};
let browser,context,page,closing=false;
const owned=mkdtempSync(join(tmpdir(),'izord-engine-browser-'));
const save=()=>writeFileSync(join(artifacts,'results.json'),JSON.stringify(result,null,2));
async function check(name,fn){const start=Date.now();try{const details=await fn();result.checks.push({name,status:'passed',durationMs:Date.now()-start,details});console.log('PASS '+name);}catch(error){result.checks.push({name,status:'failed',durationMs:Date.now()-start,error:error.stack});save();throw error;}}
try{
 await new Promise((done,fail)=>{server.once('error',fail);server.listen(3167,'127.0.0.1',done);});
 browser=await chromium.launch({headless:true,executablePath:'/tmp/izord-playwright-runtime-20260917/browsers/chromium_headless_shell-1243/chrome-headless-shell-mac-arm64/chrome-headless-shell',env:{PATH:'/usr/bin:/bin:/usr/local/bin',HOME:owned,TMPDIR:owned},args:['--disable-background-networking','--disable-component-update']});
 browser.on('disconnected',()=>{if(!closing)result.browserEvents.push({event:'unexpected browser disconnected',at:new Date().toISOString()});});
 result.browserVersion=browser.version(); result.playwrightVersion=require('/tmp/izord-playwright-runtime-20260917/node_modules/playwright/package.json').version;
 context=await browser.newContext();await context.route('**/*',route=>{const url=new URL(route.request().url());if(url.origin===origin)return route.continue();result.remoteAttempts.push(url.origin);return route.abort();});
 page=await context.newPage();page.on('pageerror',error=>result.browserEvents.push({event:'pageerror',error:String(error)}));page.on('crash',()=>result.browserEvents.push({event:'page crash'}));await page.goto(origin);
 await page.addScriptTag({content:crop+resize+';window.originalPhotos={cropPhoto,resizeImported};'});
 await page.evaluate(()=>{
  const urls=new Set(),workers=new Set(),originalCreate=URL.createObjectURL.bind(URL),originalRevoke=URL.revokeObjectURL.bind(URL),OriginalWorker=Worker;
  URL.createObjectURL=blob=>{const url=originalCreate(blob);urls.add(url);return url;};URL.revokeObjectURL=url=>{urls.delete(url);originalRevoke(url);};
  window.Worker=class extends OriginalWorker {constructor(...args){super(...args);workers.add(this);}terminate(){workers.delete(this);super.terminate();}};
  window.activeResources=()=>({blobUrls:urls.size,workers:workers.size});
  window.fixtureFile=async(name,type)=>new File([await(await fetch('/fixtures/'+name)).blob()],name,{type});
 });
 await check('Real PDF worker digital extraction: field evidence, page and embedded JPEG',()=>page.evaluate(async()=>{const reports=await engine.analyzeAgencyFiles([await fixtureFile('fiche-numerique-fictive.pdf','application/pdf')]);const r=reports[0];if(r.fields.asking!=='500000'||r.fields.area!=='120'||r.gallery.length!==1||r.evidence.asking.page!==1)throw Error(JSON.stringify({fields:r.fields,gallery:r.gallery.length}));window.digitalReport=r;return{asking:r.fields.asking,area:r.fields.area,photos:r.gallery.length,evidencePage:r.evidence.asking.page,resources:activeResources()};}));
 await check('Two PDFs stay separate, never merge property fields or photo sets',()=>page.evaluate(async()=>{const r=await engine.analyzeAgencyFiles([await fixtureFile('fiche-numerique-fictive.pdf','application/pdf'),await fixtureFile('fiche-distincte-fictive.pdf','application/pdf')]);if(r.length!==2||r[0].fields.asking!=='500000'||r[1].fields.asking!=='250000'||r[1].fields.area!=='70')throw Error('PDF separation failed');return r.map(p=>({file:p.filename,asking:p.fields.asking,area:p.fields.area,photos:p.gallery.length}));}));
 await check('Missing data remains empty and warned; scanned PDF offers manual completion without OCR',()=>page.evaluate(async()=>{const r=await engine.analyzeAgencyFiles([await fixtureFile('fiche-incomplete-fictive.pdf','application/pdf'),await fixtureFile('scan-fictif-sans-texte.pdf','application/pdf')]);if(r.some(p=>p.fields.asking||p.fields.area)||!r[1].warnings.some(w=>w.includes('Aucun OCR')))throw Error('Missing/scan false facts');r[1].fields.project='Scan fictif complété manuellement';r[1].fields.area='95';const p=await engine.applyAgencyReport(r[1]);if(p.state.area!=='95'||p.state.acq!==''||p.state.monthly!=='')throw Error('Manual apply failed');return{missingWarnings:r[0].warnings,scanWarnings:r[1].warnings,manuallyEnteredArea:p.state.area,targetsStillEmpty:true};}));
 await check('PDF review preparation and cancellation do not mutate an existing draft',()=>page.evaluate(async()=>{const p=engine.createProjectData();p.state.project='Projet existant fictif';p.state.acq='123000';const before=JSON.stringify(p);await engine.analyzeAgencyFiles([await fixtureFile('fiche-numerique-fictive.pdf','application/pdf')]);if(JSON.stringify(p)!==before)throw Error('Analysis mutated current draft');return{unchanged:true,applicationNotCalled:true};}));
 await check('Applying reviewed PDF creates a distinct draft with blank investment targets and original evidence',()=>page.evaluate(async()=>{const p=await engine.applyAgencyReport(digitalReport);for(const k of ['acq','works','resale','weekly','monthly'])if(p.state[k]!=='')throw Error('Imported target '+k);if(p.importMeta.filename!=='fiche-numerique-fictive.pdf'||p.state.asking!=='500000'||p.state.costsReviewed)throw Error('Import metadata failed');window.applied=p;return{asking:p.state.asking,targetsBlank:true,pdfReviewTimestamp:!!p.importMeta.validatedAt,operationFeesReviewed:p.state.costsReviewed};}));
 await check('Worker abort terminates worker and revokes Blob URL before completion',()=>page.evaluate(async()=>{const file=await fixtureFile('fiche-numerique-fictive.pdf','application/pdf'),controller=new AbortController();const read=engine.workerRead(await file.arrayBuffer(),{signal:controller.signal});controller.abort();let aborted=false;try{await read;}catch(e){aborted=e.name==='AbortError';}const resources=activeResources();if(!aborted||resources.blobUrls||resources.workers)throw Error('Abort cleanup failed');return{aborted,...resources};}));
 await check('PDF count, effective byte limit and invalid file signature are rejected',()=>page.evaluate(async()=>{let blocked=0;const file=await fixtureFile('fiche-numerique-fictive.pdf','application/pdf');for(const files of [Array(7).fill(file),[new File([new Uint8Array(25000001)],'too-large.pdf',{type:'application/pdf'})],[new File(['<script>bad</script>'],'fake.pdf',{type:'application/pdf'})]]){try{await engine.analyzeAgencyFiles(files);}catch{blocked++;}}if(blocked!==3)throw Error('PDF guards failed');return{blockedCases:blocked,...activeResources()};}));
 for(const [ext,type]of[['jpg','image/jpeg'],['png','image/png'],['webp','image/webp']])await check('Real '+type+' decoding, JPEG conversion and original pixel parity',()=>page.evaluate(async({ext,type})=>{const file=await fixtureFile('photo-fictive.'+ext,type),data=await engine.fileData(file);const original=await originalPhotos.resizeImported(data),actual=await engine.resizeImported(data);if(actual!==original)throw Error('Resize differs from source');const p=await engine.addPhotoFile(engine.createProjectData(),file,'main');if(p.importGallery.length!==1||!p.importGallery[0].data.startsWith('data:image/jpeg;')||p.photos.main===p.importGallery[0].data)throw Error('Full image/crop separation failed');const expectedCrop=await originalPhotos.cropPhoto(original,engine.RATIOS.main);if(p.photos.main!==expectedCrop)throw Error('Crop differs from source');const size=await engine.photoSize(p.importGallery[0]);window['photo'+ext]=p;return{inputType:type,outputType:'image/jpeg',size,fullAndCropDistinct:true,pixelExactSourceResize:true,pixelExactSourceCrop:true};},{ext,type}));
 await check('Full photo retains edge colors and watermarked center; PNG transparency flattening matches original',()=>page.evaluate(async()=>{const pixels=async(data,points)=>{const im=new Image();im.src=data;await im.decode();const c=document.createElement('canvas');c.width=im.naturalWidth;c.height=im.naturalHeight;c.getContext('2d').drawImage(im,0,0);return points.map(([x,y])=>[...c.getContext('2d').getImageData(x,y,1,1).data]);};const rgb=await pixels(photojpg.importGallery[0].data,[[40,220],[850,220],[450,180],[323,212]]),transparent=await pixels(photopng.importGallery[0].data,[[1,1]]);if(rgb[0][0]<160||rgb[1][1]<130||rgb[2].slice(0,3).some(v=>v<220)||transparent[0].slice(0,3).some(v=>v>10))throw Error('Source image appearance changed');return{edgeColors:rgb.slice(0,2),watermarkBackground:rgb[2],transparentPixelAfterOriginalJpeg:transparent[0],note:'Original JPEG conversion flattens transparent pixels to black; crop geometry unchanged.'};}));
 await check('Changing photo role retains full gallery and produces distinct source-equivalent crop',()=>page.evaluate(async()=>{const p=await engine.assignGalleryPhoto(photojpg,'inside',0);if(p.photoGalleryRoles.inside!==0||p.importGallery[0].data!==photojpg.importGallery[0].data||p.photos.inside!==await originalPhotos.cropPhoto(p.importGallery[0].data,engine.RATIOS.inside))throw Error('Role crop failed');return{role:'inside',index:0,fullImagePreserved:true};}));
 await check('Image abort, MIME spoof and huge dimensions fail without leaked resources',()=>page.evaluate(async()=>{let blocked=0;const controller=new AbortController();controller.abort();try{await engine.cropPhoto(photojpg.photos.main,2,controller.signal);}catch(e){if(e.name==='AbortError')blocked++;}try{await engine.addPhotoFile(engine.createProjectData(),new File(['<svg/>'],'fake.png',{type:'image/png'}));}catch{blocked++;}const png=new Uint8Array([137,80,78,71,13,10,26,10,0,0,0,13,73,72,68,82,0,0,195,80,0,0,195,80]);try{engine.imageHeaderDimensions(png);}catch{blocked++;}if(blocked!==3)throw Error('Image guards failed');return{blockedCases:blocked,...activeResources()};}));
 await check('Real parsed PDF project plus all photos roundtrips IZORD_FICHE_V1 in browser',()=>page.evaluate(()=>{const p={...applied,state:{...applied.state,project:'Parité fictive navigateur'}};const output=engine.exportProjectJson(p);const back=engine.importProjectJson(output);const stable=value=>value&&typeof value==='object'?(Array.isArray(value)?value.map(stable):Object.fromEntries(Object.keys(value).sort().map(key=>[key,stable(value[key])]))):value;if(JSON.stringify(stable(back))!==JSON.stringify(stable(p)))throw Error('Browser JSON roundtrip changed supported fields');return{format:JSON.parse(output).format,galleryCount:back.importGallery.length,roleCount:Object.keys(back.photoGalleryRoles).length,permissionsRestored:false};}));
 await check('Final browser resources and network isolation',()=>page.evaluate(()=>{const resources=activeResources();if(resources.workers||resources.blobUrls)throw Error('Resources leaked');if(localStorage.length||sessionStorage.length)throw Error('Unexpected persistent business cache');return{...resources,localStorageEntries:localStorage.length,sessionStorageEntries:sessionStorage.length};}));
 assert.equal(result.remoteAttempts.length,0);assert.equal(result.browserEvents.length,0);result.status='passed';
}catch(error){result.status='failed';result.error=error.stack;process.exitCode=1;}finally{result.finishedAt=new Date().toISOString();result.passed=result.checks.filter(c=>c.status==='passed').length;result.failed=result.checks.filter(c=>c.status==='failed').length;save();closing=true;if(context)await context.close();if(browser)await browser.close();await new Promise(done=>server.close(done));rmSync(owned,{recursive:true,force:true});console.log(JSON.stringify({status:result.status,passed:result.passed,failed:result.failed,report:join(artifacts,'results.json')}));}
