/** Real local generator UI, independent users, direct owned Playwright; no CDP. */
import assert from 'node:assert/strict';
import { createRequire } from 'node:module';
import { randomUUID,randomBytes } from 'node:crypto';
import {readFileSync,writeFileSync,mkdirSync,mkdtempSync} from 'node:fs';
import {join,resolve} from 'node:path';
import {tmpdir} from 'node:os';
import {assertLocalTarget} from './local-target.mjs';
const require=createRequire(import.meta.url),{createClient}=require('@supabase/supabase-js');
const runtime=process.env.IZORD_PLAYWRIGHT_RUNTIME;assert.ok(runtime);
const {chromium}=require(join(runtime,'node_modules/playwright'));
const status=JSON.parse(readFileSync(process.env.LOCAL_STATUS_FILE,'utf8')),fixture=JSON.parse(readFileSync(process.env.LOCAL_FIXTURE_FILE,'utf8'));
const app='http://127.0.0.1:3159',api=status.API_URL,out=resolve(process.env.IZORD_ARTIFACTS),inputs=process.env.IZORD_GENERATOR_FIXTURES;
assertLocalTarget({api,database:status.DB_URL,app,mail:'http://127.0.0.1:55434',acknowledgement:process.env.IZORD_TEST_ACK});assert.equal(fixture.api,api);assert.ok(inputs);
mkdirSync(out,{recursive:true});assert.ok(!(()=>{try{return readFileSync(join(out,'results.json')).length;}catch{return false;}})(),'Fresh results directory required');
const privateDir=mkdtempSync(join(tmpdir(),'izord-generator-browser-'));
const options={auth:{persistSession:false,autoRefreshToken:false,detectSessionInUrl:false}};
const admin=createClient(api,status.ANON_KEY,options),authAdmin=createClient(api,status.SERVICE_ROLE_KEY,options);
const identities={},clients=[admin,authAdmin],checks=[],events=[],downloads=[];let browser,active='setup',phase='setup',unexpectedCloses=0,expectedClose=false;
const secrets=[status.ANON_KEY,status.SERVICE_ROLE_KEY,fixture.users.admin.password];
function sanitize(error){let value=String(error?.stack||error);for(const secret of secrets.filter(Boolean))value=value.split(secret).join('[REDACTED]');return value.replace(/eyJ[A-Za-z0-9_-]+\.[A-Za-z0-9_-]+\.[A-Za-z0-9_-]+/g,'[JWT REDACTED]').replace(/token=[^\s"'&]+/g,'token=[REDACTED]').slice(0,7000);}
async function ok(p){const v=await p;if(v.error)throw new Error('Local setup/API rejected: '+String(v.error.code||'unknown'));return v.data;}
async function test(name,fn){active=name;phase='running';await fn();checks.push({name,result:'passed',completedAt:new Date().toISOString()});console.log('PASS '+name);}
async function identity(name,role){const email=`lot2-ui-${name}-${randomUUID()}@example.invalid`,password=randomBytes(24).toString('hex');secrets.push(password);const user=await ok(authAdmin.auth.admin.createUser({email,password,email_confirm:true}));const client=createClient(api,status.ANON_KEY,options);clients.push(client);await ok(client.auth.signInWithPassword({email,password}));const invitation=await ok(admin.rpc('izord_invite_izord',{p_email:email,p_role:role}));await ok(client.rpc('izord_accept_invitation',{p_token:invitation.token}));return {email,password,id:user.user.id,client};}
async function context(){const ctx=await browser.newContext({viewport:{width:1440,height:1000},acceptDownloads:true});await ctx.route('**/*',route=>{const url=new URL(route.request().url());if(!['data:','blob:','about:'].includes(url.protocol)&&url.origin!==app&&url.origin!==api){events.push({event:'remote-blocked',host:url.hostname});return route.abort();}return route.continue();});await ctx.routeWebSocket(/.*/,socket=>{events.push({event:'websocket-blocked'});socket.close();});ctx.on('page',p=>{p.on('pageerror',e=>events.push({event:'pageerror',message:sanitize(e)}));p.on('crash',()=>events.push({event:'crash'}));p.on('request',r=>{const u=new URL(r.url());if(['POST','PATCH','PUT','DELETE'].includes(r.method()))events.push({event:'write-request',path:u.pathname,method:r.method()});});p.on('dialog',d=>d.accept());});return ctx;}
async function login(page,who){await page.goto(app+'/izord');await page.getByLabel('Email',{exact:true}).fill(who.email);await page.getByLabel('Mot de passe',{exact:true}).fill(who.password);await page.getByRole('button',{name:'Se connecter',exact:true}).click();await page.locator('[data-izord-generator]').waitFor();}
const statusText=page=>page.locator('[data-izord-generator] > [role="status"]');
async function save(page){await page.getByRole('button',{name:'Enregistrer',exact:true}).click();await statusText(page).filter({hasText:/^Enregistré · révision/}).waitFor({timeout:45000});}
async function open(page,title){const details=page.locator('details').filter({has:page.locator('summary').filter({hasText:/Dossiers accessibles/})});if(!await details.evaluate(e=>e.open))await details.locator('summary').click();await page.getByRole('button',{name:'Ouvrir '+title,exact:true}).click();await statusText(page).filter({hasText:/Enregistré · révision/}).waitFor({timeout:20000});}
async function getDownload(page,button,name,scope=page){const waiting=page.waitForEvent('download',{timeout:45000});await scope.getByRole('button',{name:button,exact:true}).click();const d=await waiting;await d.saveAs(join(out,name));assert.equal(await d.failure(),null);downloads.push(name);return d;}
async function snap(page,name){await page.screenshot({path:join(out,name),fullPage:true,mask:[page.locator('[class*="identity"]')]});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false,'No horizontal overflow');}
async function heldProjectResponse(page,projectId){
 let arrived,release;const ready=new Promise(resolveReady=>{arrived=resolveReady;}),gate=new Promise(resolveRelease=>{release=resolveRelease;});let captured=false;
 const pattern=url=>url.origin===api&&url.pathname==='/rest/v1/izord_projects';
 const handler=async route=>{const request=route.request(),url=new URL(request.url());if(captured||request.method()!=='GET'||url.searchParams.get('id')!=='eq.'+projectId)return route.continue();captured=true;const response=await route.fetch();assert.equal(response.status(),200);arrived();await gate;try{await route.fulfill({response});}catch(error){events.push({event:'held-response-delivery-cancelled',message:sanitize(error)});}};
 await page.route(pattern,handler);return{ready:async()=>{let timer;try{await Promise.race([ready,new Promise((_,reject)=>{timer=setTimeout(()=>reject(Error('Actual project response not captured')),20000);})]);}finally{clearTimeout(timer);}},release:async()=>{release();await page.unroute(pattern,handler);},};
}
const startedAt=new Date().toISOString();let failure=null;let pages=[];
try{
 await ok(admin.auth.signInWithPassword({email:fixture.users.admin.email,password:fixture.users.admin.password}));
 identities.a=await identity('a','contributor');identities.b=await identity('b','contributor');identities.reader=await identity('reader','reader');
 writeFileSync(join(privateDir,'users.json'),JSON.stringify(Object.fromEntries(Object.entries(identities).map(([k,v])=>[k,{id:v.id,email:v.email,password:v.password}]))),{mode:0o600});
 browser=await chromium.launch({headless:true,executablePath:join(runtime,'browsers/chromium_headless_shell-1243/chrome-headless-shell-mac-arm64/chrome-headless-shell'),env:{PATH:process.env.PATH,HOME:privateDir,TMPDIR:privateDir},args:['--disable-background-networking']});
 browser.on('disconnected',()=>{if(!expectedClose)unexpectedCloses++;});events.push({event:'runtime-versions',browser:browser.version(),playwright:require(join(runtime,'node_modules/playwright/package.json')).version});
 const ca=await context(),cb=await context(),cr=await context();const a=await ca.newPage(),b=await cb.newPage(),reader=await cr.newPage();pages=[a,b,reader];
 const suffix=randomUUID().slice(0,8),title='Villa fictive lot 2 '+suffix;
 await test('Real contributor login; blank draft contains no default example or OAR payload',async()=>{await login(a,identities.a);await snap(a,'01-list-desktop.png');await a.getByRole('button',{name:'Nouveau projet',exact:true}).click();assert.equal(await a.locator('#izord-project').inputValue(),'');assert.equal(await a.locator('#izord-acq').inputValue(),'');assert.equal(await a.locator('[data-izord-generator]').getByText(/Dragon Island/i).count(),0);assert.equal(events.some(e=>e.path?.includes('crm_workspace_state')),false);});
 await test('Real PDF import review and cancellation preserve an edited draft',async()=>{await a.locator('#izord-project').fill(title);await a.getByLabel('Importer une fiche PDF',{exact:true}).setInputFiles(join(inputs,'fiche-numerique-fictive.pdf'));const dialog=a.getByRole('dialog',{name:'Vérification de la fiche PDF'});await dialog.waitFor({timeout:30000});await snap(a,'02-import-review.png');await a.getByRole('button',{name:'Ne pas appliquer',exact:true}).click();assert.equal(await a.locator('#izord-project').inputValue(),title);});
 await test('PDF reviewed application, empty targets and manual hypotheses remain distinct',async()=>{await a.getByLabel('Importer une fiche PDF',{exact:true}).setInputFiles(join(inputs,'fiche-numerique-fictive.pdf'));const dialog=a.getByRole('dialog',{name:'Vérification de la fiche PDF'});await dialog.waitFor();await dialog.getByRole('checkbox').check();await dialog.getByRole('button',{name:'Valider et créer la fiche projet'}).click();await dialog.waitFor({state:'hidden'});assert.equal(await a.locator('#izord-acq').inputValue(),'');assert.equal(await a.locator('#izord-resale').inputValue(),'');await a.locator('#izord-project').fill(title);for(const [field,value] of Object.entries({acq:'500000',works:'50000',resale:'750000',weekly:'2200',monthly:'2800'}))await a.locator('#izord-'+field).fill(value);await a.locator('#izord-rentalMode').selectOption('compare');assert.match(await a.locator('[data-izord-generator]').innerText(),/190 000/);});
 await test('JPEG PNG WebP additions preserve gallery plus four distinct synthesis roles',async()=>{for(const [role,file] of [['main','photo-fictive.jpg'],['view','photo-fictive.png'],['inside','photo-fictive.webp']]){await a.getByLabel({main:'Vue d’ensemble',view:'Vue / environnement',inside:'Intérieur'}[role],{exact:true}).setInputFiles(join(inputs,file));await a.getByRole('button',{name:'Enregistrer',exact:true}).waitFor();await a.waitForFunction(()=>!document.querySelector('fieldset').disabled);}await a.locator('label').filter({hasText:/^Choisir dans la photothèque — Photo de la diapositive 2/}).locator('select').selectOption('0');await snap(a,'03-editor-desktop.png');});
 let project;
 await test('Explicit shared save stores no inline photo bytes and authoritative version author',async()=>{await save(a);project=await ok(identities.a.client.from('izord_projects').select('*').eq('title',title).single());assert.equal(project.revision,2);assert.equal(JSON.stringify(project.payload).includes('data:image/'),false);const version=await ok(identities.a.client.from('izord_project_versions').select('author_id').eq('project_id',project.id).eq('revision',2).single());assert.equal(version.author_id,identities.a.id);await snap(a,'04-saved.png');await ok(admin.rpc('izord_assign_project',{p_project:project.id,p_user:identities.b.id,p_assigned:true}));await ok(admin.rpc('izord_assign_project',{p_project:project.id,p_user:identities.reader.id,p_assigned:true}));});
 await test('Second real account reopens saved hypotheses and private photos after first page closes',async()=>{await a.close();await login(b,identities.b);await open(b,title);assert.equal(await b.locator('#izord-acq').inputValue(),'500000');assert.equal(await b.locator('#izord-rentalMode').inputValue(),'compare');assert.ok((await b.locator('img[alt="Vue d’ensemble"]').getAttribute('src')).startsWith('data:image/jpeg;'));});
 await test('V1 JSON recovery roundtrip and editable native three-slide export archive exact saved revision',async()=>{await getDownload(b,'Exporter le JSON','fictional-project.json');const json=JSON.parse(readFileSync(join(out,'fictional-project.json'),'utf8'));assert.equal(json.format,'IZORD_FICHE_V1');assert.equal(json.state.acq,'500000');assert.ok(json.importMeta&&json.importGallery.length>=3);await getDownload(b,'Générer le PowerPoint','fictional-3-slides.pptx');await statusText(b).filter({hasText:'PowerPoint archivé'}).waitFor();const JSZip=require('jszip'),zip=await JSZip.loadAsync(readFileSync(join(out,'fictional-3-slides.pptx')));assert.equal(Object.keys(zip.files).filter(p=>/^ppt\/slides\/slide\d+\.xml$/.test(p)).length,3);assert.ok((await zip.file('ppt/slides/slide2.xml').async('string')).includes('COMPARAISON LOCATIVE'));await snap(b,'05-preview-desktop.png');});
 await test('Optional annex disabled generates two-slide export of a new explicitly saved revision',async()=>{await b.locator('#izord-includePhotoSlide').uncheck();await getDownload(b,'Générer le PowerPoint','fictional-2-slides.pptx');const JSZip=require('jszip'),zip=await JSZip.loadAsync(readFileSync(join(out,'fictional-2-slides.pptx')));assert.equal(Object.keys(zip.files).filter(p=>/^ppt\/slides\/slide\d+\.xml$/.test(p)).length,2);});
 let a2;
 await test('Concurrent writers detect conflict; draft and recovery remain without overwriting newer work',async()=>{a2=await ca.newPage();pages.push(a2);await a2.goto(app+'/izord');await a2.locator('[data-izord-generator]').waitFor();await open(a2,title);await b.locator('#izord-decisionNotes').fill('Modification locale B à rapprocher');await a2.locator('#izord-features').fill('Travail partagé plus récent A');await save(a2);await b.getByRole('button',{name:'Enregistrer',exact:true}).click();await b.getByRole('region',{name:'Conflit de sauvegarde'}).waitFor();assert.equal(await b.locator('#izord-decisionNotes').inputValue(),'Modification locale B à rapprocher');const row=await ok(identities.a.client.from('izord_projects').select('*').eq('id',project.id).single());assert.equal(row.payload.data.state.features,'Travail partagé plus récent A');assert.notEqual(row.payload.data.state.decisionNotes,'Modification locale B à rapprocher');await getDownload(b,'Exporter le JSON de récupération','fictional-conflict-recovery.json',b.getByRole('region',{name:'Conflit de sauvegarde'}));await snap(b,'06-conflict.png');});
 await test('Real SDK session refresh alone emits zero save writes; a subsequent real edit saves',async()=>{const before=events.length;const result=await a2.evaluate(async()=>{let client;window.webpackChunk_N_E.push([[Math.random()],{},require=>{const modules=require.c?Object.values(require.c):Object.entries(require.m).filter(([,factory])=>String(factory).includes('http://127.0.0.1:55431')).map(([id])=>({exports:require(id)}));for(const loadedModule of modules){for(const value of Object.values(loadedModule.exports||{})){if(value&&typeof value==='object'&&value.auth&&typeof value.auth.refreshSession==='function'&&typeof value.from==='function'){client=value;break;}}if(client)break;}}]);if(!client)throw Error('App client unavailable');const previous=(await client.auth.getSession()).data.session;const next=await client.auth.refreshSession();return {error:!!next.error,sameIdentity:previous.user.id===next.data.session.user.id,changed:previous.access_token!==next.data.session.access_token};});assert.equal(result.error,false);assert.equal(result.sameIdentity,true);assert.equal(result.changed,true);await a2.waitForTimeout(1000);assert.equal(events.slice(before).some(e=>e.path?.includes('izord_save')),false);await a2.locator('#izord-features').fill('Vraie modification après renouvellement');await save(a2);});
 await test('Reader sees allowed project but cannot edit, generate, approve or read private source photos',async()=>{await login(reader,identities.reader);await open(reader,title);assert.equal(await reader.getByRole('button',{name:'Enregistrer',exact:true}).count(),0);assert.equal(await reader.getByRole('button',{name:'Générer le PowerPoint',exact:true}).count(),0);assert.equal(await reader.locator('fieldset').evaluate(element=>element.disabled),true);assert.equal(await reader.locator('fieldset input,fieldset select,fieldset textarea').evaluateAll(elements=>elements.length>0&&elements.every(element=>element.matches(':disabled'))),true);assert.equal(await reader.locator('#izord-acq').isDisabled(),true);assert.equal(await reader.getByRole('button',{name:'Télécharger',exact:true}).count(),0);const canApprove=await identities.b.client.rpc('izord_save_project',{p_id:project.id,p_expected_revision:999,p_title:title,p_payload:{},p_status:'approved'});assert.ok(canApprove.error);});
 await test('Authorized publication exposes only the exact finalized presentation to reader',async()=>{const assets=await ok(admin.from('izord_assets').select('*').eq('project_id',project.id).eq('kind','presentation').eq('lifecycle','finalized'));assert.equal(assets.length,2);await ok(admin.rpc('izord_allow_reader_download',{p_asset:assets[0].id,p_allowed:true}));await reader.reload();await reader.locator('[data-izord-generator]').waitFor();await open(reader,title);assert.equal(await reader.getByRole('button',{name:'Télécharger',exact:true}).count(),1);await getDownload(reader,'Télécharger','reader-authorized.pptx');assert.ok(readFileSync(join(out,'reader-authorized.pptx')).length>10000);});
 await test('Mobile 390px editor and original previews fit without horizontal overflow',async()=>{await a2.setViewportSize({width:390,height:844});await snap(a2,'07-editor-mobile.png');await a2.locator('[data-presentation-preview]').scrollIntoViewIfNeeded();await a2.screenshot({path:join(out,'08-preview-mobile.png')});});
 let importedProject,importedTitle;
 await test('JSON UI import creates a new draft and shared identity without restored approval',async()=>{await a2.setViewportSize({width:1440,height:1000});await a2.getByLabel('Importer un projet JSON',{exact:true}).setInputFiles(join(out,'fictional-project.json'));await statusText(a2).filter({hasText:'Nouveau brouillon'}).waitFor();assert.equal(await a2.locator('#izord-acq').inputValue(),'500000');importedTitle=title+' JSON';await a2.locator('#izord-project').fill(importedTitle);await save(a2);importedProject=await ok(identities.a.client.from('izord_projects').select('*').eq('title',importedTitle).single());assert.notEqual(importedProject.id,project.id);assert.equal(importedProject.status,'draft');assert.equal(importedProject.owner_id,identities.a.id);});
 await test('SIMULATED save transport 503 preserves local edits and never confirms saved',async()=>{const before=await ok(identities.a.client.from('izord_projects').select('*').eq('id',importedProject.id).single());await a2.locator('#izord-features').fill('Brouillon fictif conservé après erreur');const pattern=api+'/rest/v1/rpc/izord_save_generator';const fail=route=>route.fulfill({status:503,contentType:'application/json',body:JSON.stringify({message:'Fictional transport failure'})});await a2.route(pattern,fail);try{await a2.getByRole('button',{name:'Enregistrer',exact:true}).click();await statusText(a2).filter({hasText:'Non enregistré'}).waitFor();assert.equal(await a2.locator('#izord-features').inputValue(),'Brouillon fictif conservé après erreur');assert.ok(await a2.getByRole('alert').count());const after=await ok(identities.a.client.from('izord_projects').select('*').eq('id',importedProject.id).single());assert.equal(after.revision,before.revision);assert.deepEqual(after.payload,before.payload);await getDownload(a2,'Exporter le JSON de récupération','fictional-save-error-recovery.json');}finally{await a2.unroute(pattern,fail);}await save(a2);});
 await test('SIMULATED presentation upload failure yields no download or false archive confirmation',async()=>{let downloaded=false;const observe=()=>{downloaded=true;};a2.on('download',observe);const before=await ok(identities.a.client.from('izord_assets').select('*').eq('project_id',importedProject.id).eq('kind','presentation'));const pattern=url=>url.origin===api&&url.pathname.startsWith('/storage/v1/object/upload/sign/');const fail=route=>route.request().method()==='PUT'?route.fulfill({status:503,contentType:'application/json',body:JSON.stringify({message:'Fictional transfer interruption'})}):route.continue();await a2.route(pattern,fail);try{await a2.getByRole('button',{name:'Générer le PowerPoint',exact:true}).click();await statusText(a2).filter({hasText:'Export non archivé'}).waitFor({timeout:45000});assert.equal(downloaded,false);const after=await ok(identities.a.client.from('izord_assets').select('*').eq('project_id',importedProject.id).eq('kind','presentation'));assert.equal(after.filter(x=>x.lifecycle==='finalized').length,before.filter(x=>x.lifecycle==='finalized').length);assert.ok(after.some(x=>x.lifecycle==='pending'));await snap(a2,'09-export-failure.png');}finally{a2.off('download',observe);await a2.unroute(pattern,fail);}});
 await test('SIMULATED photo upload failure leaves explicit pending transfer; authorized abandonment retires it',async()=>{const png=await a2.evaluate(()=>{const canvas=document.createElement('canvas');canvas.width=24;canvas.height=24;const context=canvas.getContext('2d');context.fillStyle='#73519f';context.fillRect(0,0,24,24);return canvas.toDataURL('image/png').split(',')[1];});await a2.getByLabel('Ajouter à la photothèque',{exact:true}).setInputFiles({name:'interruption-fictive.png',mimeType:'image/png',buffer:Buffer.from(png,'base64')});await a2.waitForFunction(()=>!document.querySelector('fieldset').disabled);const pattern=url=>url.origin===api&&url.pathname.startsWith('/storage/v1/object/upload/sign/');const fail=route=>route.request().method()==='PUT'?route.fulfill({status:503,contentType:'application/json',body:JSON.stringify({message:'Fictional transfer interruption'})}):route.continue();await a2.route(pattern,fail);try{await a2.getByRole('button',{name:'Enregistrer',exact:true}).click();await statusText(a2).filter({hasText:'Non enregistré'}).waitFor();}finally{await a2.unroute(pattern,fail);}const pending=await ok(identities.a.client.from('izord_assets').select('*').eq('project_id',importedProject.id).eq('kind','photo').eq('lifecycle','pending'));assert.equal(pending.length,1);await a2.getByRole('button',{name:'Vérifier les transferts',exact:true}).click();const section=a2.getByRole('heading',{name:'Documents privés',exact:true}).locator('..');const row=section.getByRole('listitem').filter({hasText:`photo · r${pending[0].project_revision} · pending`});await row.getByRole('button',{name:'Abandonner ce transfert',exact:true}).click();await row.waitFor({state:'hidden'});const after=await ok(authAdmin.from('izord_assets').select('lifecycle,reader_download').eq('id',pending[0].id).single());assert.equal(after.lifecycle,'withdrawn');assert.equal(after.reader_download,false);await getDownload(a2,'Exporter le JSON de récupération','fictional-upload-error-recovery.json');});
 await test('An actual late project response cannot overwrite a newer draft in the same page',async()=>{const hold=await heldProjectResponse(a2,project.id);const details=a2.locator('details').filter({has:a2.locator('summary').filter({hasText:/Dossiers accessibles/})});if(!await details.evaluate(e=>e.open))await details.locator('summary').click();await a2.getByRole('button',{name:'Ouvrir '+title,exact:true}).click();await hold.ready();await a2.getByRole('button',{name:'Nouveau projet',exact:true}).click();await a2.locator('#izord-project').fill('Nouveau brouillon après réponse tardive');await hold.release();await a2.waitForTimeout(600);assert.equal(await a2.locator('#izord-project').inputValue(),'Nouveau brouillon après réponse tardive');assert.match(await statusText(a2).innerText(),/non enregistr|Modifications/);});
 await test('Actual held project response plus normal logout/account change stays isolated in the SAME browser context',async()=>{const hold=await heldProjectResponse(a2,project.id);const details=a2.locator('details').filter({has:a2.locator('summary').filter({hasText:/Dossiers accessibles/})});if(!await details.evaluate(e=>e.open))await details.locator('summary').click();await a2.getByRole('button',{name:'Ouvrir '+title,exact:true}).click();await hold.ready();await a2.getByRole('button',{name:'Se déconnecter',exact:true}).click();await a2.getByLabel('Email',{exact:true}).waitFor();await a2.getByLabel('Email',{exact:true}).fill(identities.b.email);await a2.getByLabel('Mot de passe',{exact:true}).fill(identities.b.password);await a2.getByRole('button',{name:'Se connecter',exact:true}).click();await a2.locator('[data-izord-generator]').waitFor();await hold.release();await a2.waitForTimeout(600);assert.equal(await a2.locator('#izord-project').count(),0);assert.equal(await a2.getByRole('button',{name:'Ouvrir '+importedTitle,exact:true}).count(),0);assert.equal(await a2.getByRole('button',{name:'Ouvrir '+title,exact:true}).count(),1);assert.equal(a2.context(),ca);const raw=await a2.evaluate(async({markers})=>{const matches=[];for(const [type,storage]of [['localStorage',localStorage],['sessionStorage',sessionStorage]])for(let i=0;i<storage.length;i++){const key=storage.key(i),value=storage.getItem(key)||'';if(markers.some(marker=>value.includes(marker)))matches.push({type,key});}return{matches,cacheStorageEntries:(await caches.keys()).length,indexedDBDatabases:(await indexedDB.databases()).length};},{markers:[title,importedTitle,'Brouillon fictif conservé','Nouveau brouillon après réponse tardive','IZORD_FICHE_V1','IZORD_GENERATOR_V1','importGallery','data:image/jpeg;']});assert.deepEqual(raw.matches,[]);assert.equal(raw.cacheStorageEntries,0);assert.equal(raw.indexedDBDatabases,0);events.push({event:'raw-cache-check',...raw});});
 assert.equal(events.filter(event=>['remote-blocked','pageerror','crash'].includes(event.event)).length,0,'No remote calls, unhandled page errors or crashes');assert.equal(unexpectedCloses,0);phase='completed';
}catch(e){failure={control:active,error:sanitize(e),pages:[]};for(const page of pages.filter(p=>!p.isClosed())){try{failure.pages.push({path:new URL(page.url()).pathname,title:await page.title(),visibleText:sanitize(await page.locator('body').innerText()).slice(0,16000),busy:await page.locator('fieldset').count()?await page.locator('fieldset').evaluate(element=>element.disabled):null});}catch{failure.pages.push({state:'non disponible'});}}console.error('FAIL '+active+' '+sanitize(e));}
finally{writeFileSync(join(out,'result-before-cleanup.json'),JSON.stringify({startedAt,endedAt:new Date().toISOString(),phase,checks,failure,events,unexpectedCloses,downloads},null,2));expectedClose=true;if(browser)await browser.close();for(const client of clients)await client.auth.stopAutoRefresh();writeFileSync(join(out,'results.json'),JSON.stringify({startedAt,endedAt:new Date().toISOString(),checks,failure,events,unexpectedCloses,downloads,cleanup:'owned browser closed; fictitious database retained'},null,2));}
if(failure)process.exitCode=1;
