/** Bounded before/after proof for a delayed REAL post-save list response and project replacement. */
import assert from 'node:assert/strict';
import {createRequire} from 'node:module';
import {readFileSync,writeFileSync,mkdirSync,mkdtempSync} from 'node:fs';
import {join,resolve} from 'node:path';
import {tmpdir} from 'node:os';
import {randomUUID} from 'node:crypto';
import {assertLocalTarget} from './local-target.mjs';
const require=createRequire(import.meta.url),{chromium}=require('/tmp/izord-playwright-runtime-20260917/node_modules/playwright');
const status=JSON.parse(readFileSync(process.env.LOCAL_STATUS_FILE,'utf8')),fixture=JSON.parse(readFileSync(process.env.LOCAL_FIXTURE_FILE,'utf8')),who=process.env.IZORD_REPRO_USER_FILE?JSON.parse(readFileSync(process.env.IZORD_REPRO_USER_FILE,'utf8')).a:fixture.users.admin;
const api=status.API_URL,app='http://127.0.0.1:3159',out=resolve(process.env.IZORD_ARTIFACTS);assertLocalTarget({api,database:status.DB_URL,app,mail:'http://127.0.0.1:55434',acknowledgement:process.env.IZORD_TEST_ACK});assert.equal(fixture.api,api);assert.match(who.email,/@example\.invalid$/);
mkdirSync(out,{recursive:true});const owned=mkdtempSync(join(tmpdir(),'izord-late-export-'));let browser,page,release,expectedClose=false;
const after=process.argv.includes('--after');const result={startedAt:new Date().toISOString(),phase:after?'after':'before',events:[],checks:[],downloads:[],failure:null};
const event=(name,detail={})=>result.events.push({at:new Date().toISOString(),name,...detail});
const sanitize=value=>String(value).split(who.password).join('[REDACTED]').replace(/eyJ[A-Za-z0-9_-]+\.[A-Za-z0-9_-]+\.[A-Za-z0-9_-]+/g,'[JWT REDACTED]');
try{
 browser=await chromium.launch({headless:true,executablePath:'/tmp/izord-playwright-runtime-20260917/browsers/chromium_headless_shell-1243/chrome-headless-shell-mac-arm64/chrome-headless-shell',env:{PATH:process.env.PATH,HOME:owned,TMPDIR:owned},args:['--disable-background-networking']});result.browser=browser.version();result.playwright=require('/tmp/izord-playwright-runtime-20260917/node_modules/playwright/package.json').version;
 browser.on('disconnected',()=>{if(!expectedClose)event('unexpected-close');});const context=await browser.newContext({viewport:{width:1440,height:1000},acceptDownloads:true});await context.route('**/*',route=>{const u=new URL(route.request().url());if(!['data:','blob:','about:'].includes(u.protocol)&&![app,api].includes(u.origin)){event('remote-blocked',{origin:u.origin});return route.abort();}return route.continue();});page=await context.newPage();page.on('dialog',dialog=>dialog.accept());page.on('requestfailed',request=>event('requestfailed',{path:new URL(request.url()).pathname,method:request.method(),failure:request.failure()?.errorText}));page.on('response',response=>{const path=new URL(response.url()).pathname;if(path.startsWith('/auth/')||path.includes('app_memberships')||response.status()>=400)event('response',{path,status:response.status()});});page.on('request',request=>{if(['POST','PUT','PATCH','DELETE'].includes(request.method()))event('write-request',{method:request.method(),path:new URL(request.url()).pathname});});page.on('pageerror',error=>event('pageerror',{message:sanitize(error)}));page.on('download',download=>{result.downloads.push({at:new Date().toISOString(),filename:download.suggestedFilename()});});
 await page.goto(app+'/izord');await page.getByLabel('Email',{exact:true}).fill(who.email);await page.getByLabel('Mot de passe',{exact:true}).fill(who.password);await page.getByRole('button',{name:'Se connecter',exact:true}).click();await page.locator('[data-izord-generator]').waitFor();await page.getByRole('button',{name:'Nouveau projet',exact:true}).click();
 const suffix=randomUUID().slice(0,8),firstTitle='Export tardif fictif '+suffix,nextTitle='Nouveau brouillon protégé '+suffix;result.firstTitle=firstTitle;result.nextTitle=nextTitle;
 for(const [field,value] of Object.entries({project:firstTitle,acq:'500000',works:'50000',resale:'750000',weekly:'0'}))await page.locator('#izord-'+field).fill(value);
 let arrived;const ready=new Promise(done=>{arrived=done;}),gate=new Promise(done=>{release=done;});let captured=false;
 const pattern=url=>url.origin===api&&url.pathname==='/rest/v1/izord_projects';
 await page.route(pattern,async route=>{const url=new URL(route.request().url());if(captured||route.request().method()!=='GET'||url.searchParams.has('id'))return route.continue();captured=true;const response=await route.fetch();assert.equal(response.status(),200);event('actual-post-save-list-held',{status:response.status()});arrived();await gate;await route.fulfill({response});event('actual-post-save-list-released');});
 await page.getByRole('button',{name:'Générer le PowerPoint',exact:true}).click();let deadline;try{await Promise.race([ready,new Promise((_,reject)=>{deadline=setTimeout(()=>reject(Error('Post-save list not captured')),20000);})]);}finally{clearTimeout(deadline);}
 event('before-new-draft',{notice:await page.locator('[data-izord-generator] > [role=status]').innerText(),field:await page.locator('#izord-project').inputValue()});
 await page.getByRole('button',{name:'Nouveau projet',exact:true}).click();await page.locator('#izord-project').fill(nextTitle);event('new-draft-confirmed',{field:await page.locator('#izord-project').inputValue()});release();
 await page.waitForTimeout(4000);
 result.finalField=await page.locator('#izord-project').inputValue();result.finalNotice=await page.locator('[data-izord-generator] > [role=status]').innerText();result.reproduced=result.downloads.some(download=>download.filename.includes('Export-tardif-fictif'))&&result.finalNotice.includes('PowerPoint archivé');
 await page.screenshot({path:join(out,after?'late-export-after.png':'late-export-before.png'),fullPage:true,mask:[page.locator('[class*="identity"]')]});event('result-before-cleanup',{finalField:result.finalField,finalNotice:result.finalNotice,reproduced:result.reproduced});
 if(after){assert.equal(result.reproduced,false);assert.equal(result.downloads.length,0);assert.equal(result.finalField,nextTitle);assert.match(result.finalNotice,/Modifications non enregistrées|Nouveau brouillon/);const sinceNew=result.events.findIndex(item=>item.name==='new-draft-confirmed');assert.equal(result.events.slice(sinceNew).some(item=>item.name==='write-request'&&(/izord_register_generator_asset|izord_finalize_asset|\/storage\//.test(item.path))),false);result.corrected=true;}else assert.equal(result.reproduced,true,'Expected baseline race was not observed; do not infer reproduction');
}catch(error){result.failure=sanitize(error?.stack||error);if(page&&!page.isClosed())result.pageText=sanitize(await page.locator('body').innerText()).slice(0,6000);process.exitCode=1;}finally{result.finishedAt=new Date().toISOString();writeFileSync(join(out,'result-before-cleanup.json'),JSON.stringify(result,null,2));if(release)release();expectedClose=true;if(browser)await browser.close();writeFileSync(join(out,'results.json'),JSON.stringify({...result,cleanup:'owned isolated browser closed; local fictional project retained'},null,2));console.log(JSON.stringify({reproduced:result.reproduced,failure:result.failure,report:join(out,'results.json')}));}
